### ISSUE TITLE
[game/inventory] Schafter V12 only have 50 trunk space

### ISSUE THREAD

**Issue by RandomKilled** [InZidiuZ/op-framework-issue-tracker#1018]
**Reporter:**
RandomKilled#0300
https://steamcommunity.com/id/RandomKilled/

**Summary:**
The trunk of the scahfter v12 has only 5 slots and have a maximum weight of 50

**Steps to Reproduce:**
Check the trunk

**Expected Results:**
Expected more trunk space than 50

**Actual Results:**
50 weight trunk space

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
https://gyazo.com/327c546138abdab25edefef7199ddc25

**Game Resolution:**
1920x1080

**Player Data:**
Write /info whilst ingame and provide the information you're given.
https://gyazo.com/1dc72d4f36dbf4cbc4cb3d81cb889b0d

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
EU/NA

**Notes:**
For anything else noteworthy.

**Comment by manikgoyal04** [comment]
Schlagen GT also have 50 trunk space I think it should be increased! Because it's back side is large enough and it can easily carry 200-400 of space

**Comment by InZidiuZ** [comment]
Is the Schafter V12 an add-on vehicle?

**Comment by manikgoyal04** [comment]
Nope, it's a pdm vehicle but the thing is many of the pdm vehicles like itali gto, schlagen gt, elegy retro custom has 50 trunk space and their back portion is large enough to have like 500 trunk space and some pdm super cars like truffade nero custom has 500 trunk space and this doesn't make sense because the back portion of the truffade nero custom is not that large, I think you should work on this! Cars like elegy retro custom and itali gto should have atleast 300 trunk space!

**Comment by InZidiuZ** [comment]
This issue has now been resolved. Not sure why, but all "Sports Classics" were set to 50 trunk space. Guessing (and hoping) this was just a typo. I've set it to 500 now.
