### ISSUE TITLE
[?] Economy Improvements

### ISSUE THREAD

**Issue by MeerkatRS** [InZidiuZ/op-framework-issue-tracker#1023]
**Name:**
Who is suggesting this? Please include discord name.
LoadingMeerkat#1756
**Summary:**

Write a short summary of what your suggestion is about.
- Remove medical bills or lower dramatically.

- Reduce price of phone to like $100 instead of $500.

**Reason:**
Why would your suggestion be a good addition to Legacy?
I literally was in a rave with like 6 people and everyone said they're all in debt. It's very demotivating to even make money if I know I'm just going to lose it all very soon mainly because of medical bills and cost of phones. It's a public server so you get RDM'ed or die to silly things all the time so when I get killed for RDM/VDM then I get billed $300 I just kinda want to give up as a new player.

**Comment by ravicant** [comment]
when i was new i also faced same thing and after all its a game like we play other game we keep on dyeing and then we start learning so slowly you will get to know about some more job which have like a lot money not a long grind but it take hardly 20 to 30 min to make 10k+ or more so just hope in the server Start Doing Roleplay and small Grind(Grinding is a part of a game) ez

**Comment by DaxterPancake** [comment]
You are given roughly $5,800 when you create a fresh character, that should be more than enough to buy you a phone, some food and a cheap car to start earning money.

The most popular job is Garbage, which rewards you with anywhere between $200-$500 per run, with a run taking you roughly 10-20min. 
As for the phone, realisticly a phone should be costing you upwards of $500. 

This system has been working for many players in the past, hackers have been more frequent lately but that shouldn't mean you're going into the negatives unless you're not doing any jobs at all.

**Comment by MeerkatRS** [comment]
You just explained it perfectly. 20 mins to get maybe $200 at minimum. Then you die because of some BS and you have to pay $300 for medical bills. Now you're in debt. Also potentially it could take over 40 minutes then to just afford a phone just to contact your friends. Most civs are actually criminals in the server so IRL they would be able to buy cheap phones to throw away. Even in the opening of NoPixel the economy wasn't this harsh. I'm all for a fairly tough economy but people want to have fun and not grind jobs 24/7 otherwise why are we on an RP server if it's just to do a job I could be doing IRL and making real money.


> You are given roughly $5,800 when you create a fresh character, that should be more than enough to buy you a phone, some food and a cheap car to start earning money.
> 
> The most popular job is Garbage, which rewards you with anywhere between $200-$500 per run, with a run taking you roughly 10-20min.
> As for the phone, realisticly a phone should be costing you upwards of $500.
> 
> This system has been working for many players in the past, hackers have been more frequent lately but that shouldn't mean you're going into the negatives unless you're not doing any jobs at all.

**Comment by rsk95** [comment]
> You just explained it perfectly. 20 mins to get maybe $200 at minimum. Then you die because of some BS and you have to pay $300 for medical bills. Now you're in debt. Also potentially it could take over 40 minutes then to just afford a phone just to contact your friends. Most civs are actually criminals in the server so IRL they would be able to buy cheap phones to throw away. Even in the opening of NoPixel the economy wasn't this harsh. I'm all for a fairly tough economy but people want to have fun and not grind jobs 24/7 otherwise why are we on an RP server if it's just to do a job I could be doing IRL and making real money. When people are grinding jobs like garbage they're mostly not interacting with other people.
> 
> > You are given roughly $5,800 when you create a fresh character, that should be more than enough to buy you a phone, some food and a cheap car to start earning money.
> > The most popular job is Garbage, which rewards you with anywhere between $200-$500 per run, with a run taking you roughly 10-20min.
> > As for the phone, realisticly a phone should be costing you upwards of $500.
> > This system has been working for many players in the past, hackers have been more frequent lately but that shouldn't mean you're going into the negatives unless you're not doing any jobs at all.

Long post** I second this. And the op. I’ve been on this server for 2 weeks now and The medical bills and cost of certain items that commonly get stolen from my characters that are “expensive” are my phones, med kits and tasers. Tasers I can deal with as the price is reasonable but the other two that everyone takes off my characters have cost them a sh*t tone having to replace them constantly. Being a public server I understand we’re gonna get some sh*tters who’ll just rob you with 0 interaction and rdm you. I’ve had numerous occasions where I’ve been killed for something just as little as scraping someone’s car whilst trying to make some money doing my garbage rounds and being dumped in some place like the Canals with no ems on and having to Respawn @ pillbox get a few items “mugged” off me then on top of that get a $300 medical bill. Which sometimes ends up with me losing up to a grand in money and items. I know my post is long but I also would like to mention last night (Saturday evening) I literally got RDM’d 5 times within 10 minutes three times simultaneously at pillbox, literally as soon as I got treated someone came in the treating room and injured everyone again. Then after my second treatment someone kicked me off my bike and started beating me up and then the third time straight after someone fucking stabbed me as soon as I exited the doors. That all cost me $1500. I then went to go make my money back doing some garbage runs, as I’m driving down south side someone drives in the opposite lane at high speed and flings me in the air and I die and doesn’t come back. = Respawn at hospital another $300 plus more items “mugged” I then go make my way again to the garbage hq for there to be guys on the roofs shooting everyone mass rdm’ing. Thankfully there were some guys trying to sort them out And took me to pill box but yet again another $300. In a space of 10 minutes i lost just under $2k in medical bills and about $600-700 worth of items after having to Respawn twice. 

Sorry for the long post but that’s literally how my yesterday went and we’re not including every time I get held hostage and robbed of my items about 3-5 times Each day I’m on the server killing my bank account even more. Everyday I have to spend an hour- hour and a half on  garbage runs just to make sure I don’t go under 1k for the days like Saturday night where I’ve had to go to pillbox about 10 times because people kill you over the most minor things (that isn’t worth killing over in my opinion I.e accidentally knocking someone’s car) and the sh*tters that come in the server and go on a killing spree to cause chaos. Medical bills are way to high for people like me who aren’t robbing banks and robbing everyone they see. The economy needs to change.

**Comment by twooot** [comment]
> You are given roughly $5,800 when you create a fresh character, that should be more than enough to buy you a phone, some food and a cheap car to start earning money.
> 
> The most popular job is Garbage, which rewards you with anywhere between $200-$500 per run, with a run taking you roughly 10-20min. As for the phone, realisticly a phone should be costing you upwards of $500.
> 
> This system has been working for many players in the past, hackers have been more frequent lately but that shouldn't mean you're going into the negatives unless you're not doing any jobs at all.

This
