### ISSUE TITLE
[game/jail] Working in jail, time reduction readjustment.

### ISSUE THREAD

**Issue by Vedder742** [InZidiuZ/op-framework-issue-tracker#1033]
**Name:**
Ori#4385

**Summary:**
Due to the state team re-visiting the Penal Code in the city to re-adjust charges based on the economy, realism, and need. It has been concluded in the state and public services that the reduction you are able to get due to working in prison is far too high and unrealistic, and is, in turn, breaking the city's RP.

**Reason:**
The current situation allows people who get sent it for 50 months, to be out in less than 10. 
We are a public server that allows people to assault each other with deadly weapons and after being fully prosecuted, get to walk the streets 5 minutes later. The prosecution and police processing is nothing but an unbalanced waste of time as it is now. Without the needed readjustments to the jail system and penal code. The concept of RP or legal consequences in the city is near non-existing. And is turning the city into a chaotic shit show, especially with the number of new players going around.

In order to avoid an overall drastic increase in jail time due to the current need, jail time reductions due to working in jail should be revisited from a development perspective. While it is possible to match the new Penal Code to that new addition to the jailing system in Legacy, (and it is already being worked on minimally as a temporary solution right now) 
it would be far more reasonable to tweak the time reduction system itself rather than drastically scale all the charges up, just because some people, work in jail sometimes, and virtually make the jailing system useless.

**Comment by Seferti** [comment]
Have you actually been to jail and did the jobs? I can assure you that if someone gets sent for 50 months, they will not be out in less than 10. As someone who has been sent in for 85 months, I was out in about 40ish after doing my jobs, I think the system is fine the way it is now.

**Comment by Vedder742** [comment]
@Seferti This situation is being reported and testified by relevant people OOC, there is clearly an issue here that needs to be looked into regardless of your personal experience.

**Comment by skyy-reginald** [comment]
Honestly the jail time needs to be lengthened ALOT. For people who go to jail a lot for bank robberies and shit they shouldn’t be seen on 10-15 mins later. If I get caught for a robbery because I was stupid enough not to plan well enough to not get caught then I deserve to be in jail for a considerable amount of time so that I start planning heists better. I agree with this whole heartily.

**Comment by Livius99** [comment]
The whole Jail System is alright right now , the things to be changed are the "jobs" that reduce your time in prison . as @Vedder742 said criminals can do some jobs and get half the sentence if not more . I'd really love to see more attention on the Jail System and Roleplay that could be created around it : Guards , Prison Inmates , Prison Breaks ,etc so instead of getting less time from jobs maybe we need to create a RP scene around that :/

**Comment by RealJustovia** [comment]
Ya... I dont play cop and im a crim. I love the fact i can rob a bank and kill a cop fail and be out in 20mins, but its honestly its not good for rp I shouldnt be out this quick.

**Comment by twooot** [comment]
I think the DOJ should rather increase jail times instead of forcing a certain RP via DEV changes
