### ISSUE TITLE
[illegal/*] Change drug locations

### ISSUE THREAD

**Issue by jharitesh5** [InZidiuZ/op-framework-issue-tracker#1047]
**Name:**
Jharites5#7232

**Summary:**
A suggestion to make illigal places moveable and weed and cocaine to not easily accessible to other.

**Reason:**
As we know everyone in server know location of cocaine and weed farm even police also know in whitelist as they have visited that place.
Also everyone in server has access to weed and cocaine and anyone can do the work.
Someone come in server and ask for cocaine and weed farm location and next he is grinding in that farm which make gang and illigal work Rp a joke.
My suggestion is that make this work movable by gang who hold this place to specific location only to know by that gang .ex like their are 2 airstrip in city 1 in sandyshore and other in cocaine farm.so if police come know that this airstrip is used by gang to smuggle drug into city they can raid this place and seal it for sometime until then gang can use other airstrip for cocaine work same goes for weed farm their are many farm area which can be used by gang to farm weed. And also weed should be grow by using weed seed,bucket and fertilizer by gang in weed farm not randomly spawn in weed farm it give purpose to weed seed which people throw in whole server and also create a good gang rp and also good illigal economy.only Diffrence is this weed farm can produce weed very fast and cheap compare to produce in house.
And for cocaine their should a cap to how much can a gang get in one day.

**Comment by InZidiuZ** [comment]
Will close this due to it being more of a 'general' suggestion, meanwhile I'd rather have something more specific. If you still feel like this is relevant, feel free to perhaps make a structured POC and/or go into more detail on how these 'movable' locations would work, when they would move, etc.

There are some other dynamic ideas for improved drug systems as well by mixing in missions, a sort of 'capture the flag' kind of thing between groups, items, crafting and such, though no one has been able to put anything solid & structured using these ideas yet.
