### ISSUE TITLE
[vehicles/rentals] Car Rental Service

### ISSUE THREAD

**Issue by adivish** [InZidiuZ/op-framework-issue-tracker#1118]
**Name:**
Aditya
RockstarAdii#9220

**Summary:**
We should introduce a car/bike rental service in the city.

**Reason:**
Say, if a player joins the city then the first thing which he does is to **hotwire*_a vehicle . In real life do we just go and hotwire any random vehicle in the parking? So it will be good that if we introduce car rental service through out the city and specially at spawning location where we can rent car at fair price for a certain time periods with certain rules , it's just like motels which are available for month . so a player can just rent a car on his name and can roam around  the city . This will  help new player but also some old players who just cant afford to buy a new car but can rent . And also rules should be made in certain cases like rental cars and bike cannot be used for robbery and illegal stuffs. Also the rental price should be low as every one can afford them.

This was my suggestion you can make changes to it , to make the rp to the next level.

**Comment by InZidiuZ** [comment]
For players just starting out, it is very difficult indeed, though my plan is to remake the taxi job to make it work way better & ultimately allow new players to be easily transported in taxis when they start off, though rentals could help as well, especially after having left the airport and starting to get situated.

**Comment by iLikeAss3** [comment]
@InZidiuZ Like you said, According to me you should remake taxi jobs. Make it a white-collar job. To get that job you must fill in an application, no interviews just application. I think you should make #rp-taxireviews channel in discord, To help people review the taxi driver. However, my main concern is "freeloaders". What people do is take the ride in taxi. once they reach their destination they pull out their guns. Forcing taxis to run away without paychecks. Since we are already talking about guns, how about adding a license to guns purchased from ammunition and guns that people buy from dark web will have their serial id scratched. That would mean if police catch you with such weapons you could be arrested. 

LAST BUT NOT THE LEAST: Open the police forms for the blacklisted city only. there are basically no cops

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
