### ISSUE TITLE
[external/clothing] Adding /gloves and /armor commands

### ISSUE THREAD

**Issue by Doughnut2001** [InZidiuZ/op-framework-issue-tracker#1134]
**Name:**
@Doughnut#1718

**Summary:**
adding toggle commands like /Gloves that toggle your arms to the variant without gloves and /Armor that changes any armor you have to the first variant, getting rid of the visual aspect.

**Reason:**
This would help people in PD when responding to a scene where there's a downed individual and they have to use surgical gloves to protect themselves while waiting for EMS, adding a lot more of realism to scenarios, it could also help PD when armor isn't too needed on patrol, being able to swiftly put on armor inside of your vehicle and take ti off as needed.
It would help civilians be able to put on visual armor or take it off when it's depleted or when the law requires them without having to go to a clothing store everytime (they would have to stow it somewhere, a small /me puts armor in "X" could do it)
and of course EMS could get the /gloves every time they are responding, or they could RP getting rid of their disposable gloves and getting new ones from a pack by the Beds in pillbox

**Comment by iLikeAss3** [comment]
Yes, Totally agree!

**Comment by novapurple** [comment]
On top of this it could be used for more than the gloves and armor and be used for maybe all pieces of clothing? To add some increased emersion for some RP interactions.

**Comment by Doughnut2001** [comment]
"Some situations" Kappa
![2a982x](https://user-images.githubusercontent.com/52846859/92161374-8e1d9180-edfe-11ea-8e91-654639c47d06.jpg)

**Comment by Nuziatella** [comment]
I believe for a level of enhancing roleplay this is a great idea. Allows people a bit more variety on what actions they can do while in the city. The animation for removing or adding armor could be the same animation used for when you use armor. Gloves is a bit more interesting to pull off.

**Comment by cwisdasaur** [comment]
Criminals could use gloves to potentially fool PD drug tests, provided they remove and discard them?

**Comment by Doughnut2001** [comment]
> Criminals could use gloves to potentially fool PD drug tests, provided they remove and discard them?

Definetly not what i meant, i meant it on a cosmetic way, drug sales are already at a huge payoff for crims.

**Comment by cwisdasaur** [comment]
I know that you were merely suggesting a custume ped with a toggle but actual functionality is just an additional suggestion that could give criminals, police, and lawyers more roleplay.

**Comment by DaxterPancake** [comment]
I agree that selling drugs is already a huge payout that is hard for a cop to catch you for, I don't see a reason for taking gloves on and off to make it even HARDER.

**Comment by cwisdasaur** [comment]
I also agree that selling drugs is a huge payout.  It really should be considering the risk of a Rico charge, which is a life sentence.  The reason for that sort of functionality would only be because it would make the city more realistic.  IRL police departments use residue samples to prove possession charges, for sure.  Say a suspect is evading police after being spotted in what looked like a drug sale, he could consume his product and come up somewhat clean. Police should use the residue results and toxicology of the driver to deduce he consumed or discarded the evidence pre arrest and was guilty of buying or selling whatever drug was present.  So gloves would clearly throw a wrench in that, but say if they were maybe and item with a remove feature, police could also claim they had clean hands because of the gloves.  Again, it would simply add more RP.  I don't want to muddy the water here at all because Doughnut certainly has a decent suggestion imo. These are just thoughts I've had while working multiple drug cases in the past and I appreciate the system we have now.

**Comment by InZidiuZ** [comment]
This has been added with the dpclothes.
