### ISSUE TITLE
Justice

### ISSUE THREAD

**Issue by ALQxZeus** [InZidiuZ/op-framework-issue-tracker#1148]
Make cocaine and weed field/process area free for everyone no one can hold that place please

**Comment by ScotsMan-07** [comment]
why though? that takes roleplay away from people you should be wanting to make contacts and gain a relationship with these gangs to be able to buy it and then sell it to others also stops pepole just grinding constantly

**Comment by Gibby94** [comment]
Well said scotsman, having it like this encourages encounters which should in theory produce some great roleplay

**Comment by BreeZaH7** [comment]
I agree with ScotsMan that they should be held by someone, where I do disagree is I don't believe you should be banned if you use them as the gangs who own territory should either be able to hold them down or be approachable enough where it isn't an issue. As someone who roles with 3/4 people in the city there isn't much we can do once a gang says they don't want to speak with you. But I agree the territories do add to roleplay and encourage people to build relationships rather than just grind all day and night

**Comment by Gibby94** [comment]
Speaking as a member of a gang. If individuals approached us wanting to purchase the product we happen to be selling we would welcome it, it would provide us with buyers and more contacts. 
What gangs will not like is if someone approaches them being arrogant or with weapons out.

**Comment by InZidiuZ** [comment]
Use the available template(s). This is also not framework related.
