### ISSUE TITLE
EMS clocked on? Can't check in for instant revive.

### ISSUE THREAD

**Issue by SteezyRen** [InZidiuZ/op-framework-issue-tracker#115]
**Name:**
SteezyRen#2828

**Summary:**
Currently there is no need for EMS for people who play with friends. They just yank them up and carry them to the hospital and they can just revive. 0 RP for the EMS and the person being revived by pressing 'E'

If we remove the option to "check-in" at pillbox when EMS is clocked on this would encourage RP with EMS and the downed individual. Or the "check-in" feature would instead ping EMS to come to pillbox if they aren't there currently to know they have a call at the hospital.

**Reason:**
With the amount of ways to RP in this server it feels kind of sad to see no interaction or RP for EMS since you can just carry your dumb friends and shove them in a trunk lol.

Let's make EMS great again.

**Comment by essjaybee** [comment]
I kinda agree to this. Maybe it's a process that needs to find itself and settle, I know EMS had it rough initially with pings and/or messages.

Also I will admit that I yesterday witnessed my friend fail a BMX jump at Pink Cage. Two issues that were apparent to me during this time, and that I'd like to pardon myself to the EMS for. My guy does the jump and completely fails, after I'm done laughing to tears I grab the telephone and write the EMS.

First issue:
* I'm not 100% sure when I msg EMS if they got the message or not, or if anybody of them is even available. This is a common thing in servers, at least those I've tried, and the EMS has the ability to answer us. But, having done EMS before, I also know that it at times is very hectic. You have patients, people around the patient talking, people in earpiece talking, and you are trying your best to "/me grabs C collar from med bag" etc while still coming off professional. On top of that you have to answer a message.

The result of this was that we were waiting around a bit impatiently, and after a few minutes (and I will be the first to say we just were impatient) we were like "bah, I'll just carry you there brother!", when I almost get to the hospital I got a message that EMS was on his way. And I felt a bit guilty for leaving the situation.

Second issue:
Ties with the first one really, and I think also is a process that will settle over time once EMS finds how they work best in this new framework. But we get to Pillbox, there is one heck of a scene so I understood why EMS had been busy, I ask if I can take my sick brother in and they let us in. I walk up to the counter, as I always do, and my friend is just about to hit E when the both of us connect that maybe the EMS girl was talking to us. And she asks if we need assistance.

For the last situation, I'm so happy that my friend didn't tap E by gut feeling, because we're both looking for the RP encounter, not a min/max revive. But I also feel it was out of sheer luck cus we happened to run into her.

I don't know what the exact fixes are or how it's dealt with on other servers. I would like it to be that you always try to get help from emergency services first, but if not available or over capacity, the current system is a real life saver. And the whole carry and putting in trunk is in itself just so brilliant (and fun).

Maybe this was just a bunch of personal opinions, but EMS has been in my mind since I started playing here and I hope a balance can be found so that we get more emergency RP encounters, while not being too punishing for an accidental muscle spasm in the middle of the desert with your buddy, perhaps some kind of feedback in phones to know the availability of EMS. Ultimately I think the feedback loop has to be much faster between patient and EMS for them not to go "f it, let's just carry"

**Comment by SATIN187** [comment]
But what about the people that play on the other server where there is no ems because they’re all on the server that is full and has a queue? Not everybody wants to wait in queue they wanna play so they go to a different city hence why there are multiple then it would just screw over those people... you’re gonna have that issue due to these servers being public

**Comment by Scrubject** [comment]
I think the /carry is a total necessity but at the same time I see where you're coming from. The obvious solution to me would be to either make checking in cost dramatically more so that not finding an EMT is actually scary lmao, **or** similar to ARMA Life servers, make it so that being revived by an unprofessional / checking in would cause temporary de-buffs to your character. Possibly reduced stamina, lowered max health, or even just a blurry screen. personally i think that would be the best way to encourage seeing a professional.

**Comment by InZidiuZ** [comment]
Hey,

This ties fairly well in with the enhanced medical system. EMS are now able to mark themselves as a "doctor" when on-duty. People are still able to check in at the hospital, but if there's a doctor, he/she will be notified about a new patient, and the "healing process" won't happen until a doctor comes over to your bed & helps you out.

Injuries were also added recently, so if you get shot in your foot, you'll be bleeding & also have a foot injury. More information soon though. All this will go live after next patch.

https://gyazo.com/0b0b0672d1fdf7c5a95be8f3b4281592

**InZidiuZ**
*OP-FW Developer*
