### ISSUE TITLE
[weapons/weapons] Allow larger guns to remain unholstered while in a vehicle

### ISSUE THREAD

**Issue by JepsonHepson** [InZidiuZ/op-framework-issue-tracker#1150]
**Name:**
@jepson#1379

**Summary:**
I don't know if this would fall under a bug or suggestion whether it was an intentional change but previously you could withdraw bigger weapons such as a rifle from a car and use it when you exit it immediately.

**Reason:**
Currently if you want to use a bigger weapon when you step out of a car you have to stop, draw it and then aim and it makes kidnapping scenarios, general gunfights and other similar scenarios slow down and feel klunky. Imagine you want to kidnap someone and make your presence known by using big rifles. Now you exit the car, take a few seconds to get them out, ample time for the other party to escape. I feel this feature should be added back after the 2.5 update.

**Comment by iLikeAss3** [comment]
I disagree, you need to use /me to pull out your weapon. The game's whole point is to roleplay. If you just want to make your presence felt, I believe you are in the wrong game mode. If you want to kidnap someone a simple pistol will do just fine. However when wars are concerned. you need to use /me for roleplaying and taking out your gun. Rather than just exiting your vehicles with ak47s. That would contribute to power gaming in away and just terrible rp

**Comment by InZidiuZ** [comment]
This has now been done, though you will not be able to unholster any large guns *while* in a vehicle. You can still holster larger weapons already unholstered.
