### ISSUE TITLE
Starting cash transfer timer

### ISSUE THREAD

**Issue by samimenad** [InZidiuZ/op-framework-issue-tracker#1190]
**Name:**
Sami
SAMI#3378

**Summary:**
Essentially, I have an idea for a possible script that might be able to be made, preventing people from farming starter cash. I'm not sure if it's possible, I'm not a code dev myself however I've been told that anything is possible when it comes to scripting. 
The idea is essentially to limit the max amount a new person can transfer to another player, before an invisible 30 minute cool down has expired. For example; Player A is a new player with starter money, Player B is an average player, the maximum amount of cash that Player A would be able to send to Player B (visa versa), would be £3000 total over a 30 minute timer and a maximum of $1000 per five minutes.

**Reason:**
This would prevent people from exploiting starter cash, whilst also not limiting any other factor of the new players experience.

Thanks :) and again I apologise.

**Comment by samimenad** [comment]
I also think, if a new player tries to transfer anywhere between 4000-5800 their account should be flagged and a message sent to the staff panel, or whatever set-up you've got going on.

**Comment by InZidiuZ** [comment]
This was a part of the patch-note for the most recent version, 2.5.
> You will now only receive "starter money" on your first four characters created. This is done to combat all these *roleplayers* exploiting.

Just recently there was a small issue discovered preventing this from actually happening, though that has since been resolved.

Your suggestion is possible, but I think it'd just slow down the process, and other ways of exploiting would appear (i.e. creating 4 characters at once, waiting 30 minutes, sending the cash, starting over) & that would then again have to be prevented in other manners.

With that being said, I'll close this & hope the solution already created works *when there's no bug* preventing expected behavior.

**Comment by BreeZaH7** [comment]
Sami weren't you banned for doing this? 😂
