### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by T4NZIM** [InZidiuZ/op-framework-issue-tracker#1223]
**Name:**
Who is suggesting this? Please include discord name.
@EyePatch#6255 

**Summary:**
Write a short summary of what your suggestion is about.
I've been playing on Legacy server simve January 2020 and that time pillbox check-ins used to refill food bars. That was actually very gppd but from next update, it got removed. Please consider adding this feature back even if it costs money for food. Please add this again. Srry my english is bad*

**Reason:**
Why would your suggestion be a good addition to Legacy?
IRL, medical treatment provide foods to to treat patients. Thats why I guess adding this again would make it easier than the current one. Also low food level doesn't gi e any signal and when food is 0,  character dies. So pls consider adding this again plsssss. Sry for my poor English again bt hope u will understand :)

**Comment by joevapes3** [comment]
I don't think it should fill them, but at least give you a quarter full on food/water maximum. Also make it so it can't be filled above that quarter, even if they check in multiple times since I've seen people when they're hungry just checking themselves into pillbox, instead of buy food. The reason I suggest the quarter is cause when you pass out from hunger you only have a short time to get food again before starving again, and in some cases you end up passing out immediately when getting up from the hospital bed.

**Comment by T4NZIM** [comment]
> I don't think it should fill them, but at least give you a quarter full on food/water maximum. Also make it so it can't be filled above that quarter, even if they check in multiple times since I've seen people when they're hungry just checking themselves into pillbox, instead of buy food. The reason I suggest the quarter is cause when you pass out from hunger you only have a short time to get food again before starving again, and in some cases you end up passing out immediately when getting up from the hospital bed.

I know some people goes for check-in instead of buying foods but if the food level is low then the cost will also be increased...

**Comment by InZidiuZ** [comment]
This was just not working as it was calling removed systems. It has now been resolved.
