### ISSUE TITLE
Change the housing system.

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#1386]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
I think the company system to buy houses should be removed & the same goes for the blocks system If a person likes a house he can buy it individually like the houses should be individual not in bulk so if a person likes a house he can contact the state to purchase it instead if a company owner.

**Reason:**
Why would your suggestion be a good change to the framework?
This will help you to do lease work like changing the block prices/spots/add a house in a block & sometimes if you add a house in a block then the companies need to repurchase the block which is total dumb as some people have made their custom furniture so if the leave that house the furniture also gets removed.

**Comment by InZidiuZ** [comment]
?

**Comment by AdeptCL** [comment]
I can see this working, although in a public server might not work as well it seems.
If this was set up, companies wouldn't exist since what else is there except bars for them to do? You can argue this is roleplay, but it's easier to still roleplay it without paying for a company.

Not only this, the State would rely on themselves to set up the homes, blocks, etc, and again in a public server, I personally don't think it'd work.
