### ISSUE TITLE
Bug report: Trashbag not detaching from ped

### ISSUE THREAD

**Issue by Skonchy** [InZidiuZ/op-framework-issue-tracker#1451]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
Skonchy

**Summary:**
Write a short summary of what you are experiencing.
During peak times, doing the garbage job can result in the trash bag not detaching from the ped correctly when being placed in the back of the garbage truck. I think this may be a result of either the bag model not being validated through a RequestModel loop before being able to place into the back of the truck or something similar where the client does not receive the entity and its model before requesting it be detached and deleted.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Do the garbage job with either a low cpu priority (mock low-end pc) or at peak times when the server is under load

**Expected Results:**
What are the expected results?
Trash bag is detached properly when placing trash in back of truck

**Actual Results:**
What are the actual results?
Trash bag occasionally loads after the event to put it in the back resulting in the trash bag being attached to the entity indefinitely as the reference to the entity is no longer available.

## Additional Information
**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
To be added later

**Server:**
What server/community did this issue occur in?
Legacy RP

**Notes:**
For anything else noteworthy.

**Comment by RajvirSinghMajotra** [comment]
Bro either do refresh skin or change your cloths. It happens with me also i do these and the trash bag gets removes.

**Comment by Skonchy** [comment]
The band-aid doesn't fix the issue. Thanks for a pointless response.

**Comment by InZidiuZ** [comment]
> During peak times, doing the garbage job can result in the trash bag not detaching from the ped correctly when being placed in the back of the garbage truck.

It's never detached nor 'placed in the back of the garbage truck', it's just deleted.

> a result of either the bag model not being validated through a RequestModel loop before being able to place into the back of the truck

...what?

> where the client does not receive the entity and its model before requesting it be detached and deleted.

That makes... no sense.

It's likely to be a networking issue as it's become more of an issue in recent times when there has been more issues related to networked objects and migration of them. I'm guessing the object would migrate and cause issues preventing the creating client from deleting it properly.

As the garbage job is a deprecated system, I'll just be setting the garbage bags to not be networked which will hopefully resolve this issue. Though I wouldn't be surprised if this hasn't been an issue for a few days due to a lot of fixes recently being pushed from FiveM.
