### ISSUE TITLE
Cocaine Cooldown Suggestion

### ISSUE THREAD

**Issue by MrRPDP** [InZidiuZ/op-framework-issue-tracker#1468]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Write a summary of what your suggestion is about.
**Cocaine Cooldown** some of em says its 15 minutes and others says its 30 minutes so assuming its 30 i am suggesting please it should be  10 minutes only its long enough for everyone.

**Reason:**
Why would your suggestion be a good change to the framework?
Because sometimes whole gang comes and just sit there for whole day and we solo players dont even get the chance.

**Comment by AdeptCL** [comment]
The idea of roleplay is that something as illegal as cocaine importing is going to be controlled by a group or gang. If anything, what the gang is doing is healthy for the roleplay within the server. As annoying it may be for someone who likes to be solo, they should not be obtaining cocaine from the original source (the plane). The risk is too high and quite frankly, not very safe for a solo individual to do.

I very much doubt this will ever be implemented or changed, unless for a valid reason. Not because "a group controls it so solo people don't have a chance". 

As a solo individual, you should be considering a relationship with the group who controls it so that you can buy the products off them at a price.

**Comment by Dinoreaper5** [comment]
Cocaine is controlled by a gang, that is why there is always a large group there at all times, because that is what there job is to do. Control coke so nobody else can come in and take the product.

**Comment by InZidiuZ** [comment]
This suggestion has been declined.
