### ISSUE TITLE
[?] Tommy Gun SMG

### ISSUE THREAD

**Issue by novapurple** [InZidiuZ/op-framework-issue-tracker#1550]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.
**Summary:**
Write a summary of what your suggestion is about.
An old school gun that would be great for some Mafia RP with some of the servers trying to do it. This is a very nice gun that gives off that mafia noir vibe. 

https://cdn.discordapp.com/attachments/714462023735574549/782311511552557127/image0.webp

**Reason:**
Why would your suggestion be a good change to the framework?
On the International Server we are in the process of making a Mobster Mafia, heavily inspired by a noir 80s mafia. And I personally think this would gradually increase the RP for anyone else trying to do the same thing as we are. Would also be great to have a new weapon for the city to enjoy 😁

**Comment by Doughnut2001** [comment]
i almost +1 that.
but the idea is a bit too utopic in my opinion, let me explain

The Tommy Gun is in the same category as the heavy MG's in gta due to the ridiculous amount of ammo that it carries in the drum mag.
in real life MG's are used as a very expensive way of supressing a target meaning that they shoot a lot of high power ammo with very low recoil when in a prone or a supported position.

meaning that in order for this gun to not be completely OP, it should either have one of 3 things of which all defeat the purpose.
-1 low damage
-very high recoil
-a smaller mag

I'm a very big fan of Noir style mafias from the 20's (I tried to start one a while back with my perma'd character Vito Cacciatore)
but this would sadly be an MG with no other counter :c 

unless we get a completely new shipment of guns, like other MG's, grenades and sniper rifles this would sadly just be OP since it would be the only high capacity magazine weapon in the city.

**Comment by InZidiuZ** [comment]
There is already a 'tommy gun SMG' in the game if I'm not mistaken. It's called 'gusenberg'. Are you suggesting that that gun should added to the server, or are you suggesting an entirely new, streamed gun? Because the gusenberg is already in the server, alongside with every single other GTA weapon there is.

**Comment by novapurple** [comment]
I was referring to it being accessible. Currently there is no way to get it in the city.

**Comment by InZidiuZ** [comment]
I've added it to the gun heist now.
