### ISSUE TITLE
Charged negative amounts of money for checking in at pillbox.

### ISSUE THREAD

**Issue by mxttx** [InZidiuZ/op-framework-issue-tracker#1551]
**Assurance:**
Yes

**Player Identification:**
https://steamcommunity.com/id/mattxiv

**Summary:**
On inspection of the logs, someone got charged negative money for checking in at pillbox (returning an increase overall). I have no idea but my gut feeling tells me this could be exploited eventually if someone figures out how to reproduce it.

**Steps to Reproduce:**
Check in and pray you get charged a negative amount? I have no idea how this happened.

**Expected Results:**
You get charged from $0 - $X amount of dollars, never below 0.

**Actual Results:**
Looks like it can be negative

## Additional Information

**Server:**
EU/NA 

**Notes:**

(steam:110000103ee056b) was charged $-25 for their stay at the hospital. | 11/28/2020, 7:09:45 PM

**Comment by InZidiuZ** [comment]
The money system already has proper checks in place to prevent such things from happening, so no one ever actually got removed a negative amount of money. The logging for it just went through regardless if the money manipulation was successful or not (which I've changed now with version 3443).

I looked over it though, and it seems that the cause for this issue was already resolved with a commit pushed yesterday.
