### ISSUE TITLE
[jobs/*] Job changes

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#1565]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
I think the Job **"Tow Driver"** & **"Journalist"** should be a whitelisted job that means they should not be in the life invader.

**Reason:**
Why would your suggestion be a good change to the framework?
Most of the divisions of legacy got the "Tow Driver" as whitelisted job to create RP for the mechanic for the "Journalist" job lots of things can be added to it if it's a whitelisted job rarely people pic this job as there is nothing to do in it, making it whitelisted job & adding more stuff (which will be suggested once it's whitelisted) to it will create much more RP to it.

**Comment by KookieNCoffee1** [comment]
Having the "mechanic" job being a whitelisted job just makes sense. In the US/UK Legacy server, many of the mechanic shops are already owned and being ran properly: the Lost MC Repair shop, the one owned by the Sons up north, Flywheels, and Mosleys to name the main ones.

Making these changes and making the "mechanic" job whitelisted would enable more RP to be introduced. Instead of some random Danny just waking up just go to repair their car at a mechanic shop, it just doesn't make sense RP wise (especially since they are already player-owned, referring to the Unofficial Whitelisted Companies on the Public Information channel on the Discord).

There should be a newly-introduced job structure similar to the job structure of bars: 1 Owner, 2 Managers, 2-4 Head Mechanics, and unlimited Mechanics. Pay should be similar to the equivalent bar jobs. Having these jobs enables for people to move up the ladder and actually give a better reason for the mechanic to do well at their job, interaction wise.

By making the "mechanic" job whitelisted, there is also the potential to add some new car-mechanics into the city. For example, having a mechanic install some illegal modifications on your vehicles. 

I think this could be very beneficial. Good suggestion.
