### ISSUE TITLE
[vehicles/los_santos_customs] Mechanic

### ISSUE THREAD

**Issue by Enryy** [InZidiuZ/op-framework-issue-tracker#1568]
**Assurance:**
Yes

**Summary:**
Put all the los santos customs accessible only to mechanics, so players will have to go to the tuners to have their vehicles modified.

Reason:
This modification would be an excellent implementation, to create very intense roleplay scenes, and to give more work to the mechanics and the tuners.

**Comment by SirPiff** [comment]
I was actually going to submit a similar github to this, however also slightly different.

When it comes to it being just mechanics, I feel like people will just swap to a mechanic job if they're not in a whitelisted one, we can't really stop that from happening.

If we potentially had LSC locations as purchasable locations legally with jobs tied to them, with maybe a rework of the LSC script, so everything isn't more expensive than my real-life mortgage, along with possible additions such as custom modded wheels, since a lot of wheels don't fit the entire archway of the custom cars, such as the GTR, the wheels are too small for it.

Could potentially add illegal modifications to the LSC too, only available to senior tuners in the job hierarchy maybe.
Considering currently when you buy turbo, you automatically get engine level 3, and when the server restarts and you still have turbo but bought engine level 4, it'll go back down to 3 (as from what I've seen)

I think it'd be amazing if we used engine level 4 as an illegal mod that adds a really good amount of speed to the car, such as in NoPixel, when illegal mods are installed cars go from their normal like 140ish to 190-200ish.

As we've just done a car meet and a sponsored race by the governor, it'd be really cool to see these in action.

Now there may be the PDM issue of "no ones ever around"

So I may suggest maybe making Liveries/Custom Wheels/Neon/Engine 4 Upgrade be the only ones that are exclusive to owned shops.

Obviously, I'm unsure of how much the Tuner Chip would do if it actually worked, if Engine Level 4 did become an illegal upgrade that did a decent amount, I wouldn't mind it being quite expensive.

I do think this would be great and create more RP around the city regarding cars outside of PDM.

Sorry if this comment is sloppy im tired :(

**Comment by KookieNCoffee1** [comment]
Though I may be biased because of the whole entire Midnight thing, I believe this could be an amazing addition. It would really make the racing scene, and even just the car scene, so much better. I would love this. Big +1.

**Comment by InZidiuZ** [comment]
I have added a config option to lock the LSCs to the "Mechanic" job. The key is `lock_los_santos_customs`.
