### ISSUE TITLE
[game/health] Add scriptwided damage system

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1592]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
You should add damages scriptwisely, for example, if you shoot someone in the head they will get a message "You got shot in the head" or "You got shot in the chest" and they have to RP that they got shot where the message told them to. If you are injured and laying on the ground after getting shot and you shoot the person in the head then the script will tell the person "You died, you got shot in the head" and it's automatically playerkill. System will tell exact spots where the player got shot and they can't bypass that by rping that they didn't got shot to that spot. After shooting the player, anyone near the dead/injured person could type "/damages [ID]" and the server will automatically tell where did he get shot to.

**Reason:**
Why would your suggestion be a good change to the framework?
Easier to playerkill people, improve RP.

**Comment by AdeptCL** [comment]
I really like this. It's funny you suggested this as I've always been a fan of something which EMS can use to actually check what injuries someone has. Instead of just "right shoulder", "left shoulder", etc. It can say "Medium GSW (Chest)" or "Bruised (Right arm)". This would also stop people avoiding medical RP and have to state how they got that particular injury.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
