### ISSUE TITLE
[jobs/mechanic] /Impound command improvement

### ISSUE THREAD

**Issue by Doughnut2001** [InZidiuZ/op-framework-issue-tracker#1640]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
when someone does /impound:
-Add a bar timer of 5 seconds like the /flip command
-Play "cop3" animation
-play this message in any color "Contacting Local Tow..."
-make it possible to cancel the impound by pressing the escape key

**Reason:**
Quality of life, when we're cadets they teach us to do "/me calls local tow" when local towing a vehicle, this can heavily break the immersion for when you are forced to do it in front of someone, by adding a little timer as well as an animation and a purple /do message would cushion the effect of seeing a car dissapear, it would also prevent powergaming by letting other people know what you are doing before the car dissapears, and it would also give you a chance to cancel the impound if you see a tow truck around, or if you go through the chat history and /impound a car by accident.

**Comment by mxttx** [comment]
Impounding vehicles should be the last resort, there will be lots and lots of mechanics around willing to tow vehicles providing you pay them. I.e. Impounding vehicles causes a loss of roleplay for pretty much everyone involved. 

Adding roleplay aspects to /impound will make people want to use it more, instead of less, which is not something I'd like to see.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
