### ISSUE TITLE
Mech twerks

### ISSUE THREAD

**Issue by jaymssmith** [InZidiuZ/op-framework-issue-tracker#169]
**Name:**
Badwolf#3160

**Summary:**
I think repairs should return to LS customs so people can repair cars when mechs are not available even though that isnt an issue now because everybody and their grandma is a mechanic. I think the return of repairs should be a little more expensive than visiting a mech. If it costs about 500 to repair your car but not to full capacity, so for instance it could repair the body to slightly damaged if its below that but never to max repair and engine should go up one step so for instance if it moderate it goes up to slightly damage if its heavy damage it go up to moderate so mechanics retain their importance. But everyone shouldnt be a mech because there is no other way to repair a car if there are no mechs. 
  

**Reason:**
when you visit a repair shop in a stacked server you usually find the shop full with so many people all repairing their own cars and mechanics become somewhat useless at that point.

**Comment by Scrubject** [comment]
Today I went down to the shop to find two people waiting for a mechanic to unlock the door. I did, to repair my bike first and they were able to walk in, buy their supplies and repair their own vehicles. Being as they need me to open the door, they weren't mechanics but they could still fix their cars. I think there're definitely plenty of flaws in the new mechanic system, but I am way against LS Customs repairs being the solution. One thing with LSC repairs is that you can't mod your vehicle until you pay the sometimes ridiculous cost. Perhaps either when there are no mechanics on the server, the door within would unlock (Although i can only imagine how difficult that would be to code), or maybe a similar system to the clinic, where if there isn't a mechanic there you could pay extra to repair your car directly and entirely in the lot. People wouldn't abuse it I don't think because it would cost extra, **and** make you pay for everything to be repaired. (I.e. not the the engine or hull).

**Comment by InZidiuZ** [comment]
Hey,

The new mechanic system is meant to allow for anyone that wishes, to repair their car(s). The "mechanic" job has been replaced with a towing job, but the actual repairs were intended to be possible by anyone, which also let us get rid of the LSC repair which wasn't the most complex one.

Of course, the people that don't wish you repair their cars, are able to "hire" someone else with materials to do so.

Closing this though as there won't be done much about this.

**InZidiuZ**
*OP-FW Developer*
