### ISSUE TITLE
[game/panic_button] Adding a panic button for EMS

### ISSUE THREAD

**Issue by tomdavinci** [InZidiuZ/op-framework-issue-tracker#1699]
**Summary:**
Adding a panic button which ems personal can trigger in a panic or dangerous situation. What it will do is it will send a alert and location of that person to EMS department and LSPD, so that they can they necessary steps. 

**Reason:**
I got this idea from a situation i faced today wherein i was about to get kidnapped

**Comment by twooot** [comment]
I understand having a panic button for PD due to the nature of the job. Does EMS really have a need for a panic button?

**Comment by superiorchicken007** [comment]
Due to the nature of the job I don't believe they would need one.  The only reason I could see them having it if they are on Mt. Chilliad or some other call where they could be downed by a Mountain Lion or something.

Also to add onto #1900 it would be a good idea for the alarm to be triggered for EMS and PD so EMS is awake especially during times where there is only 1 officer on duty.  Of course have SOP's on how they would respond but that would be an IC thing.

**Comment by twooot** [comment]
done
