### ISSUE TITLE
We would like a few new cars in PDM 

### ISSUE THREAD

**Issue by Kennywiseisdead** [InZidiuZ/op-framework-issue-tracker#1779]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Write a summary of what your suggestion is about.

**Reason:**
Why would your suggestion be a good change to the framework?

**Comment by Nuziatella** [comment]
This is not the correct place for this nor did you follow the format.

**Comment by DaxterPancake** [comment]
Closing due to not following the format and not posting in the correct github.

You want to post this suggestion into the ASSET github found [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/new/choose).

You need to provide more information, not just a title. Include links to which cars you'd like to see, etc.

Thanks,
Daxter.
**Project Manager.**
