### ISSUE TITLE
[illegal/cocaine] Revert selling changes

### ISSUE THREAD

**Issue by sheikh2707** [InZidiuZ/op-framework-issue-tracker#1781]
**Summary**
Changing the cocaine selling method.

**Reason**
Hard for selling take much time then previous method and most people didn't like it u can check by community poll.

**Comment by DaxterPancake** [comment]
What would you suggest as an alternative?

**Comment by Masik52** [comment]
I would suggest a method of you standing in an area /corner and the peds will slowly come to you rather than you having to chase down peds.  If you move too far out of the area you started in the peds will stop. There should also be a bit of a cool down on it as well to cops have a chance at responding to drug sales as right now it’s nearly impossible to catch someone unless the crims are extremely brazen or dumb as hell.

**Comment by InZidiuZ** [comment]
This will not be done at this time.
