### ISSUE TITLE
[game/game] Forced First Person View while aiming in a vehicle

### ISSUE THREAD

**Issue by iGreatWhite** [InZidiuZ/op-framework-issue-tracker#1806]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
My suggestion is about making it so when you aim with a firearm inside a vehicle you would instead go into first person view instead of third person view.

**Reason:**
Why would your suggestion be a good change to the framework?
This would be a good suggestion to the framework because in the current state I feel personally vehicles can be abused in a gun fight and make it more unfair for others. This would allow it to be more balanced in a way that people would think more about shooting from their car.

**Comment by nikkoendres** [comment]
+1 Gunfights have become really stale with the current meta being instantly running to a vehicle with the smallest hitbox and biggest spoiler as soon as things get heated. Forcing people to be in first person when aiming a gun in a vehicle would not only break down the meta of reversing in small windowed car but would also promote gunfights that take place on foot instead of inside a vehicle. This change would go along really well with the new changes to recoil and would spice things up in the PvP side of Legacy.

**Comment by lildiavolo** [comment]
-1
scummy cars are already being worked on to make it more fair. cars that are impossible to shoot into are straight up against the rules. offering a drastic solution that would go against a lot of what people enjoy in the server for a problem that's already being worked on is not a good idea.

**Comment by iGreatWhite** [comment]
> -1
> scummy cars are already being worked on to make it more fair. cars that are impossible to shoot into are straight up against the rules. offering a drastic solution that would go against a lot of what people enjoy in the server for a problem that's already being worked on is not a good idea.

I would recommend not bringing up rules with this as from a framework standpoint. I feel like overall not all servers make shooting from cars a rule and it differentiate from server to server.

**Comment by Igna28** [comment]
For me these kind of suggestions are based on the main server experience and not every subdivision. So we can't make this 'big game changing decisions' only because a specific subdivision wants it. I would recommend, if this is going forward, make a framework configuration to leave to every subdivision managers the decision to enable/disable these kind of drive-by shotting.

**Comment by iGreatWhite** [comment]
> For me these kind of suggestions are based on the main server experience and not every subdivision. So we can't make these 'big game changing decisions' only because a specific subdivision wants it. I would recommend, if this is going forward, make a framework configuration to leave to every subdivision managers the decision to enable/disable these kind of drive-by shooting.

Yeah I was thinking about that in the back of my head too. If this was to be implemented, it could toggled through configuration depending on the subdivision. But overall I don’t think this is something that should just be overlooked.

**Comment by panpawn** [comment]
+1, third person shooting from cars is awful. If a vehicle has bad windows to shoot from why should that not matter? This would encourage people to actually get on foot to shoot, which I think is a objectively better

**Comment by twooot** [comment]
This has been added as a config parameter so server managers can decide to turn it on or off
