### ISSUE TITLE
[vehicles/vehicles] Personally Owned PD/EMS Vehicles

### ISSUE THREAD

**Issue by Brundoggy** [InZidiuZ/op-framework-issue-tracker#1826]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Have Officers be able to own their own cars, as it would improve RP immensely by making Officers have to repair and care for their own vehicles.  

**Reason:**
As stated, it would allow officer to be more careful with their own vehicles, not to drive them recklessly as they would need to pay out of pocket for their vehicle.

**Comment by joevapes3** [comment]
This has been discussed at length in the past, and suggested a few times, and while this sounds interesting, it wouldn't be very practical in a public server capacity. To many instances where it can be abused, and the wide array of functional vehicles that's required for PD to operate effectively varies greatly. The goal within the PD is to promote people to join and participate in order to provide a mechanical function to server. If said personal vehicle was owned, stolen, and then taken and destroyed by say a Default Danny after spending 5 minuets in the server. Then you can see how it would be an issue for said officer to continue providing the server mechanic, if they no longer had access to said vehicle anymore, and more than likely they'd just sign off duty. Same could be said if their vehicle became destroyed in an accident, sent into the ocean, stolen and hidden from said officer, as they now they can no longer police properly. It would effectively stop them from providing their mechanical function, and the server would suffer from it. These are just a few of the many logistical challenges this idea would face, and I think the disadvantages for the server health are too great on this subject.

**Comment by Brundoggy** [comment]
> , it wouldn't be very practical in a public server capacity. To many instances where it can be abused, and the wide array of functional vehicles that's required for PD to operate effectively varies greatly. The goal within the PD is to promote people to join and participate in order to provide a mechanical function to server. If said personal vehicle was owned, stolen, and then taken and destroyed by say a Default Danny after spending 5 minuets in the server. Then you can see how it would be an issue for said officer to continue providing the server mechanic, if they no longer had access to said vehicle anymore, and more than likely they'd just sign off duty. Same could be

You are right, however, how many instances have you seen people go out of their way to destroy a PD vehicle? It would allow people in PD to perhaps drive more carefully instead of going everywhere with lights and sirens. Furthermore, people double/triple inside of 1 vehicle all of the time, so they would still be more then able to provide their mechanical function. 

If it were to be "destroyed" in an accident, then that allows more RP for mechanics which allows money to flow through the economy. You cant just base your idea off of a danny from destroying a vehicle, because in my time here, I have never once seen anyone destroy a PD vehicle just because.

**Comment by iGreatWhite** [comment]
Furthermore it would let PD be able to upgrade their cars and such. Also if you’re car gets randomly destroyed wouldn’t you be able to retrieve it like a normal vehicle from a garage.

**Comment by InZidiuZ** [comment]
Closing in favor of #2072.
