### ISSUE TITLE
[jobs/police] /evidencestorage [number] for police

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#1835]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.

**Summary:**
The addition of a command that opens a mini evidence locker that never wipes. Would have an infinite amount.

**Reason:**
Currently FIB has to purchase multiple houses and then mutlple storage spots to store evidence that will be used maybe many months down the line in court. If we had a command like /evidencestorage [NUMBER] then we could assign a whole storage to certain reports. For example, if The Lost MC had shot cops, we could write our report and then assign evidence storage 1 to that report so that 4 months down the line when we need to produce the evidence in court, we could easily do so and wouldn't have to search through our 5+ houses for the evidence.

**Comment by mxttx** [comment]
This should not be necessary, the Staff and DOJ in Legacy International are looking into making a statute of limitations. We would hope the other subdivisions do something similar. 

This means that, as you have described, you should not be holding onto evidence for extensive periods of time. There are enough storage spots in lockers for a case or two at a time, after which the evidence should be thrown due to Double Jeopardy. Currently, we’re looking at a 1 month period for that roleplay to happen. at his gives you enough time to make your case without rushing, and also gives a fair time period for a he evidence to be used. Any more than that, i.e holding onto things for more than a month “just in case” should not be necessary. 

If you have evidence to charge someone with a crime, you should. Then in the end being up past charges if you want to go for RICO on an organisation. Much more balanced that way too, so that not everything starts (and ends) with a RICO case. 

I think an infinite storage that doesn’t wipe would become abused instantly on the fly with people finding ways to hide things, power gaming, etc. Yes, rules can be made to prevent that, but why bother when in my opinion it isn’t needed in the first place.

**Comment by DaxterPancake** [comment]
> There are enough storage spots in lockers for a case or two at a time.
Are you talking about personal lockers or the evidence locker? In my personal locker it is full of my personal items so there is no room for any case evidence. The evidence locker that is public to the whole of PD gets wipes of evidence backs often because they 'clutter space'. We have 3 houses full of evidence that is to be used on RICO cases.

> I think an infinite storage that doesn’t wipe would become abused instantly on the fly with people finding ways to hide things, power gaming, etc.
I don't believe this would be the case, especially if the command was limited to a high rank in PD and above.

> We would hope the other subdivisions do something similar.
I personally don't feel like just because our server does something that it should be shut down. It's a simple change that would add quality of life for people not having to worry about losing evidence, buying multiple houses to store it or worrying that it's going to dissapear in the evidence locker.

In the future, evidence is going to hopefully be re-written and that will add even more evidence into the system, all of which will need to be held onto for cases. 1 month or not, that's a lot of bags to have to keep track of when an easy command that you can store it into and retrieve it when/if court goes ahead could be easily implimented.

**Comment by mxttx** [comment]
> I personally don't feel like just because our server does something that it should be shut down. It's a simple change that would add quality of life for people not having to worry about losing evidence, buying multiple houses to store it or worrying that it's going to disappear in the evidence locker.
> 
> In the future, evidence is going to hopefully be re-written and that will add even more evidence into the system, all of which will need to be held onto for cases. 1 month or not, that's a lot of bags to have to keep track of when an easy command that you can store it into and retrieve it when/if court goes ahead could be easily implimented.

I can second this. You've won me over.

**Comment by panpawn** [comment]
In addition to all that has been stated above, this would also significantly simplify when someone comes to get their items that were marked as to-be-returned back. Sometimes people don't realize they can do this, or the same day the evidence locker is cleared, so this would be a huge qualify of life improvement.

Touching on some of the relevant concerns above, as long as proper logging is done with a new evidence system (who put/removed what in what locker when), I think would alleviate these concerns.

Huge +1 for this suggestion!

**Comment by twooot** [comment]
😎

**Comment by twooot** [comment]
I added a new archive system inside the NOOSE building opposite of the evidence locker.

You can create up to 20 cases. You can create a case using /create_archive [case-no]. Each case is its own inventory with 2000lb of space. You can access all cases in the archive at the marker.
![yes](https://raw.twoot.org/DOFiJuWU78.png)

The case number can be any integer between 1 and 99,999. You can destroy cases again by using /destroy_archive [case-no], **but** you can only destroy empty cases (as a safety measure), so you'll have to clean out a case first before you can destroy it.
