### ISSUE TITLE
[?] Suggestion

### ISSUE THREAD

**Issue by mastersamii** [InZidiuZ/op-framework-issue-tracker#1874]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes 

**Summary:**
O’Malley’s Irish pub needs a few things to make the place all come together, to start it needs locks on the front door the back loading dock and the staff door. I would also like to see where the drinks are bought moved to the kitchen so that only bartenders can access them. A personal locker where the locker is in the loading dock along with a clothing spot right in front of it so that new hires can get uniforms at the job. Also a personal locker where the safe is in the office. 
Lastly I would love to see a boom box that is useable placed into the jukebox at the pub. 

**Reason:**
Why would your suggestion be a good change to the framework?
These changes will make the pub a safer place to work and drink at. It will also allow bartenders to have a locker to store work related items in. It will also give new employees a safe place to get in and out of uniform. The boom box will add a better atmosphere because come on everyone loves music.

**Comment by DaxterPancake** [comment]
None of the other bars (to my knowledge) have a personal locker or a clothing store.
I don't believe that a bar needs either of these things.
You have nothing to store inside of it that would be helpful to your buisness (currently) and the more personal lockers we have, the more they can be abused with illegal items, as police cannot see inside of your personal locker. 
A clothing spot would only be for convenience, therefore I don't think it should be added.

Every other bar has their purchase location in a public area, this is due to the fact that we do not have a way to GIVE an item yet. That feature is being planned in the future though and I believe the locations to purchase alcohol may be changed with that.

**Comment by mastersamii** [comment]
Gotcha thanks for responding so fast! :) Is there then anyway to move the drinks to behind the bar where the ice machine is then? And as well what about getting locks on the doors?

**Comment by iGreatWhite** [comment]
> Is there then anyway to move the drinks to behind the bar where the ice machine is then?
Stated above,
> Every other bar has their purchase location in a public area, this is due to the fact that we do not have a way to GIVE an item yet. That feature is being planned in the future though and I believe the locations to purchase alcohol may be changed with that.
@mastersamii

**Comment by twooot** [comment]
The store has been moved behind the bar. I also added door locks
