### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by Cricketx818** [InZidiuZ/op-framework-issue-tracker#188]
**Name:**
Cricketx818.

**Summary:**
1) So i've seen something that really caught my attention in N* "City" It was a Radio, Ive noticed a lot of cops use Teamspeak and sometimes do not hot mic, I have also seen people such as "us" criminals Talk in discord when dead to come save them, I know this is going to be an issue regardless, but I think If you add a Radio with like over 1000 channels and a unlimited amount if people can join that radio chanel, I think it will be a cool thing to add to legacy. so every will be Hot mic regardless because there is no teamspeak/discord, Keeps the RP going.

2) Since there are no robberies yet, Us as criminals have nothing to do besides kidnap a cop or a civilian to get some Rp going with some cops, Cuffs should have a $ amount drop since it is one time use, until new stuff gets added, reason why? everybody only has a pistol/ shotgun that anybody can buy from anywhere. Really isn't worth much, to spend 1k to rob somebody or kidnap somebody or even add 2 sets of cuffs. 
Example: Zip Ties $500 = Soft cuffs
Hand cuffs $1000 = hard cuffs 
I have had a situation before that after I cuffed somebody he ran away. and i was told by an admin that i can not robb him because he was killed, So some rules should change.

3) Cops should get a raise to pay for hostage situations or have unlimited amount of legal guns, I have asked for $2500 for a cop before witch was kinda had for cops to get since they don't have much money, So i instead requested 2 sawed off shotguns and two cell phones, just to keep the RP going because nobody had the money, Or nobody wanted to give it up because there car payment was due.

4)If the new robbing system is added, I think there should be a couple "safes" in one vault, and have GOLD bars illegal, instead of the robbers getting cash for the bank robbery, they should get "$100 - $600 a safe" and some gold bars, but have it complete RNG 3 Gold bars min, 10 MAX on Each "safe" and have more then 1 safe to hit inside a vault. If this is added, Have selling gold bars  not in the same place it is right now, Somewhere that there is no Pin in the map.

**Reason:**
Why would your suggestion be a good addition to Legacy?
A huge Plus on cops, and criminals.

**Comment by Ninjapex** [comment]
Great Suggestions!
1) This is amazing and would get rid of meta gaming (talking while dead) etc problems but it would be hard to enforce to newcomers. This is mostly a whitelisted perk, also with that. I believe it makes the voice actually sound louder or quieter the closer/farther you are which is awesome.

**Comment by InZidiuZ** [comment]
Hey,

In the future, please create one issue for each suggestion.

1. Guessing you're talking about [TokoVOIP](https://forum.fivem.net/t/release-tokovoip-a-teamspeak-based-voip-system/475479). This would allow for in-game radios for both cops and criminals. This will not be added right now, but I do have plans to add this in the future.
2. Robberies are now a thing, but for now, no changes to the cuffs will be made. They are high to prevent a massive amount of hostage and robbing situations.
3. Due to economy concerns, this will not happen at this time.
4. We ended up doing cash instead of gold bars, but in the future, we may change it up to give items instead of cash, to add another layer to the heist.

**InZidiuZ**
*OP-FW Developer*
