### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by kodaaaaaaaaaa** [InZidiuZ/op-framework-issue-tracker#1886]
**Assurance:**
Yes i have read the rules.

**Summary:**
Most of the bandana masks (mainly used by gangs) dont fit right on peoples faces, their cheeks, chin, and nose will clip through the mask ultimately making the person look very odd with random parts of their face poking through, If this problem was fixed by making the mask slightly bigger the mask would look sleek, and clean, and more people would be happy to wear it.

**Reason:**
Because most people, easily a quarter of the city uses the bandana facemask and it almost always have the face clipping through which causes some annoyances, making the mask slightly bigger so cheeks and noses dont stick through would be an amazing improvement to the bandana mask.

**Comment by iGreatWhite** [comment]
Refer to probably moving this to the [Assets Tracker](https://github.com/InZidiuZ/legacy-assets-issue-tracker). This isn't a framework issue.

**Comment by DaxterPancake** [comment]
This is the wrong tracker. 
Please re-suggest it [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues).

There is also already a suggestion in relation to this which you could just put your opinion on. You can find that [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/309).
Almost all available gang masks are not made for the bigger faces which is why skin is poking through them.

Cheers,
Daxter.
**Project Manager.**
