### ISSUE TITLE
[illegal/chopshop] Removal of Southern Chop shop

### ISSUE THREAD

**Issue by Spitfire2k6** [InZidiuZ/op-framework-issue-tracker#1986]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? 
Yes

**Summary:**
Write a summary of what your suggestion is about.
Removal of southern chop shop ton increase chop RP

**Reason:**
Why would your suggestion be a good change to the framework?
When there was a singular chop it created the roleplay where a group could take control of the area, leading to deals, wars and people trying to do it without  getting caught. Since the addition of the southern chop this no longer exists. It's also much too easy now with multiple large carparks nearby to find the chop vehicles.
In my opinion it'd bring back the roleplay behind chop rather than it being another thing to grind.

**Comment by Smach90** [comment]
I agree with this. With the southern chop area the northern one is never utilized. If the southern one was removed more traffic would go to sandy providing more rp opportunities to places like flywheels.  It would also make chop more of a challenge when getting cars.

**Comment by AdeptCL** [comment]
A group holding down a chop yard offered so much. I've seen in total around 5 groups hold it down before the Southern chop shop was introduced. Since then, not 1 single group has attempted to hold it down, and we've encountered zero roleplay from it. Especially being a player who focuses their time in the Northern half of the city.

**Comment by antihero6713** [comment]
I agree with this.

**Comment by KatLikesTacos** [comment]
Jumping in to say from a business owner's perspective, we had a lot more foot traffic in the area when it was only north chop. Not to mention that south chop's proximity to Second Gear has caused a lot of issues, including low effort RP of non-crims getting gunned down in gang disputes over the chop out back. I think having the high intensity competition of just one chop would help limit access to guns in RP, thus bringing more depth to that crim RP, as well as making holding down a chop viable for a group again.

**Comment by MetaHatter** [comment]
I also agree with this 1000%.  Limits area control gang RP, lowers reasons to go to Sandy and is WAY too close to the airport area selection of cars.

**Comment by lildiavolo** [comment]
100% Agree,
Second gear chop just made things way too easy, and is in an awkward spot anyways. Having Sandy's chop be the only one active will drastically improve traffic up there hopefully making it a spot worth being at again.

**Comment by InZidiuZ** [comment]
This ahs now been done.

**Comment by Maruf2471** [comment]
I don’t think so southern should be removed because if southern chop shop remove we have to go too far to do chop shop, and the holding thing is all about rp , I think the holding thing is happening on your server, but this not happening on our server and about the everyone can’t do chop shop they should know about cars and places,the southern chop got removed the rp will not gone a increase it will gone a decrease the rp

**Comment by stubiewonder** [comment]
I think this should have been handled a little differently.

Keep both chops but change it so the requested cars need to be delivered either to North or South chop. This makes it a little more random and keeps both locations up for possible RP scenarios. 

I don't really agree with the idea of fully removing the southern chop, I think this would be a far better solution.
