### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by WhiteOut03** [InZidiuZ/op-framework-issue-tracker#1993]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:
Can we get some type of garage system added to trash?

**Reason:**
Would eliminate all the clutter of vehicles sitting everywhere and peoples cars getting damaged while their out doing trash

**Comment by DaxterPancake** [comment]
I disagree that this should be added due to the following things:

- People should now only be down there if they are doing the job, therefore there should be less traffic down there
- We need to boost the other jobs, not remove their purpose completely. Take a taxi down there if you don't want to risk your car being damaged. If you have valuable items down there you don't want stolen, then you'd have to find a way through RP to make sure that doesnt happen.

**Comment by InZidiuZ** [comment]
This will not be added at this time.
