### ISSUE TITLE
Green Wonderland Menu Suggestion

### ISSUE THREAD

**Issue by vicarsrd** [InZidiuZ/op-framework-issue-tracker#1999]
**Assurance:**
Yes

**Summary:**
Would like to add a menu (replace one of our posters) in Green Wonderland to help customers

**Reason:**
This would help customers easily see what they can purchase, how much it costs, and how often they can purchase to remain within the city laws and guidelines.  This would also enhance the ambiance of the shop as it is something unique that would draw a customer's attention.
![Menu5](https://user-images.githubusercontent.com/81762234/132622061-334e3832-0b45-4e29-82ec-e3f9d335ca7e.jpg)
![Menu Proposal](https://user-images.githubusercontent.com/81762234/132622068-f9a75bcb-8dd4-4b92-aec2-321bec71c973.png)

**Comment by AdeptCL** [comment]
This is more than likely going to be an assets thing, so you need to use: https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues 

However, I will say, this might not happen because you're relying on the other subdivisions to also use the prices you're requesting to show. They may use different methods/different prices/etc.

**Comment by Nuziatella** [comment]
See above comment. Post this in [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues)
