### ISSUE TITLE
Diamond Casino clothing store

### ISSUE THREAD

**Issue by xplrkai** [InZidiuZ/op-framework-issue-tracker#2001]
**Assurance:**
_Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?_
Yes.

**Summary:**
_Write a summary of what your suggestion is about._
To put it simply: add the clothing store to the casino.

**Reason:**
_Why would your suggestion be a good change to the framework?_
If you're in the casino and you need to change clothes, the clothing store is right there, literally in your face. It's nothing huge or fancy, but it only makes sense and gives use to that small area of the casino.

**Comment by Nuziatella** [comment]
How does this make sense?
Why does one need to be here?
Wouldn't it make more sense to go a clothing store?

This lacks any context on why this would be beneficial to the framework.

**Comment by DaxterPancake** [comment]
> How does this make sense?
> Why does one need to be here?
> Wouldn't it make more sense to go a clothing store?
> 
> This lacks any context on why this would be beneficial to the framework.

1. It's an actual clothing store inside of the casino. It makes sense because it's a clothing store, so you should be able to get changed in there.

2. The closest clothing store is in the middle of the city and due to there being weddings and events being help almost constantly at the casino, it'd be nice to be able to get changed there if needed.

3. See point 1.

**Comment by twooot** [comment]
This has been done
