### ISSUE TITLE
Auto Impound system 

### ISSUE THREAD

**Issue by Maruf2471** [InZidiuZ/op-framework-issue-tracker#2047]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
Auto impound system is killing our mechanic tow rp , people are not getting there cars out from garage for that and it is totally unrealistic because the cars getting auto impounded 
**Reason:**
Why would your suggestion be a good change to the framework?
Auto impound system is killing our mechanic tow rp , people are not getting there cars out from garage for that and it is totally unrealistic because the cars getting auto impounded

**Comment by xEleyna** [comment]
I agree that the impound is the best system. In my opinion it should be changed so that the cars that are left outside get auto-garaged instead of auto impounded, but with the % of body and engine that they currently are while being outside. That way tow and mechanics still have their business flowing and the issue mentioned above isn’t an issue anymore.

**Comment by MsRaynie** [comment]
As well as the 'bug' of getting an impounded vehicle when it stores but your car is still next to you. The one left behind can be towed by a civilian and impounded, making you have to pay the next day. OR when the tsunami hits, either way the 500$ would have to be paid at the end of the day. 
No one is offering to refund money for when the garage messes up, like when it eats liveries. "Shit happens, sorry, can't help ya." is really a shit answer instead of fixing it or helping them, but it is also overwhelming to help 200+ people every day for the same thing. So I understand but it is frustrating.

**Comment by InZidiuZ** [comment]
What 'auto impound system' are you talking about, exactly?

**Comment by CloudTheWolf** [comment]
> What 'auto impound system' are you talking about, exactly?

I think there are 2 "auto-impounds" at the moment

1 is at Tsunami, the other is "local tow" taking vehicles if you leave the area (eg you leave harmony to pick someone up from the hospital and all cars are gone when you return)

**Comment by twooot** [comment]
Auto impound system was removed
