### ISSUE TITLE
Monetarily limit the amount of sales by a single person to NPC vendors for a set time period.

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2051]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Limit the total amount that an NPC vendor (warehouse/tanner/etc) will pay to an individual during a preset time period. 
This should be ideally set to vendor by vendor (and ideally city specific) values.  

Per person Examples (These $ values are for description only):
Gold vendor will buy a max of $2000/day
Scrap vendor will buy a max of $3000/day
Lodge will buy a max of $4000/day

With this it is expected the the buy price for items like leather could be raised, perhaps significantly.

If someone wants to stockpile leather in a day, they would still be able to, they would just have to sell it over multiple days.

**Reason:**
Why would your suggestion be a good change to the framework?
This is intended to address several different issues.
- More granular control for the server over the city economy as a whole (it currently swings WILDLY dependent on population due to limitless cash at these buyers)
- Increase the sale of items to actual people
- Significantly Reduce the downward pricing pressure caused by hard core grinding allowing each item to be made more valuable to the more casual hunter/diver without wrecking the economy
- Incentivizing grinding different things in order to maximize profits (move around the city more)

**Comment by InZidiuZ** [comment]
I like the idea, but I don't quite understand why the economy 'swings widely' depending on the player population. Could you explain more?

**Comment by MetaHatter** [comment]
It was simply referencing the disparity between the income ceiling of a 24x7 grinder vs a more casual player. 

I feel there are cases where an activity isn't "worth it" for more casual players to do because grinders have forced loot to be worth less.

Capping the amount that can be sold/earned would potentially allow for the raising of individual loot value without worrying about 24x7 grinders abusing it and wrecking the economy.  

If done right, hypothetically the grinders will end up teaming up and working together to maximize profit. More player interaction. (The ceiling will still prevent overall abuse)

I hope that clears it up.

**Comment by puppyani** [comment]
Personally, I’m opposed to further restricting and limiting on how much people can sell. Prices were already reduced + the breaks down and addition of different locations to sell the different materials and other things, as well as locations to break items into materials - we already move around the city with these things in mind. + being able to sell certain things to players, a lot of people do move around the city. 

People will end up stockpiling things waiting to sell, and then will stop grinding each day, probably won’t fly in because limited on what they can do (already another issue for some). Not everyone wants to do different things each day, some people just might wanna hunt and that’s their jam - or some people want to just scuba, sell their mats to mechanics and then sell the rest off at warehouses (as examples).

**Comment by vol5** [comment]
Goals as meta highlighted in the github submission.
1. With this it is expected the the buy price for items like leather could be raised, perhaps significantly.
2. More granular control for the server over the city economy as a whole
3. Increase the sale of items to actual people
4. Significantly Reduce the downward pricing pressure caused by hard core grinding allowing each item to be made more valuable to the more casual hunter/diver without wrecking the economy
5. Incentivizing grinding different things in order to maximize profits (move around the city more)
------------------------------------------------------------------------------------------------------------------------
[Cap the vendors on quantity not dollar amount per day]

Mats - Numbers should roughly cover 8 tanks of scuba/two 4 tank trips(Sell price increase for all materials base value 2x)
------
Gold: Uncapped
Steel: 150
Aluminum: 150
Scrap: 200
rubber: 150
glass: 250
------
Jewelry - Should roughly cover 1 JStore for a singular individual. (Sell price increase for all Jewels base value 1.5x)
40 sliver watch, 10-15 neck, 6-8 gold watch, 1-2 diamonds, avg: 55-60k
------
Diamonds: 3
Gold Watches: 8
Silver Watches: 40
Necklaces: 15
-------
Hunting  - Should roughly cover 2 hunting trips. (Sell price increase for Hunting goods base value 2x)
-------
Meat: 250 
Leather: 100 

Potential Issue:
Give mechanic computer mats different item id's where the sell spots would not buy them so mech shops cant sell computer mats for profit.

Personal thoughts - If implemented this would best be served as (Daily cap) and **WOULD ONLY MAKE SENSE WITH SIGNIFICATN PRICE INCREASES** on said goods. Directly benefiting players who do not have that much time to spend without "forcing" base prices to lower because of grinding. Also affording people reason to do other things for money. If people see this as to big of a potential cash influx, they should realize that the past 4 months have been full of money sink implementation and vendor amounts would be limited by quantity for balance. IMO, a potential bad side to this is that if you do all this work to implement (Daily Cap) and the price increase not good enough on items. You essentially just killed peoples option to grind for ZERO reason.

**Comment by twooot** [comment]
I think most of the vendors that SHOULD be limited have been limited now
