### ISSUE TITLE
Reevaluate prices of mechanics materials

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2059]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Adjust the buy prices of items in the mechanic computers to dissuade turning away customers when the mechanic is "out of scrap".  A Critical Repair, missing 4 doors as it currently stands, if using computer prices, would cost $3000 for the materials alone. 

Suggested prices	Reason
Scrap		$150->$75	Scrap is used a LOT. One door is 2 scrap. VERY minor damage is 1 scrap.
Aluminum	$200->$125	Aluminum is not used often but is still WAY too expensive
Steel		$250->$200	Steel isn't used that often as it's for engine damage.
Glass		$80  ->$50	Glass breaks a LOT and is often scuffed, requiring multiple repairs to "fix" it. 
Rubber		$300->$25	Would you pay over $1200 for 4 tires?

In addition to this, the cost to retrieve a vehicle should also be looked at/increased (perhaps progressively).  $250 to lake a vehicle and get it back is... well... why even bother repairing it?

**Reason:**
Why would your suggestion be a good change to the framework?
Currently there is a major issue with repair material availability when players are not selling. Prices in the mechanic computers are insanely high for certain materials causing people to simply turn away repairs or recommending they just lake their car and retrieve it.  Adjusting these prices would incentivize people to get their car fixed, help mechanics stay open and increase character interaction.

If the objective is to get more people to sell scrap to players, reducing the buy prices at the NPC warehouses would likly be more effective as there is a ceiling to what people will spend for repairs.

**Comment by AdeptCL** [comment]
If you decrease the prices of the computer too much, people will not reach out to people to buy materials. They will just use the computer. This is the reason the prices were increased in the first place.

However, if you make the prices too low, the suppliers will also just sell at the warehouse(s) as they are able to gain more. The prices that @CloudTheWolf provided are pretty balanced in my opinion.

If I remember, I will use one of my more broken vehicles and evaluate what the cost would be using Cloud's prices and post it here later on in the day. Unless someone is able to provide information before.

**Comment by CloudTheWolf** [comment]
@AdeptCL this is the Cost to Buy / Price of repair based of Harmony prices based on common repairs I have done, and adding 1 door replacement which includes a 1 window. 

Calculation includes profit to mechanic using all player purchased vs all computer purchased materials  using the proposed pricing, as well as current computer pricing 

| Buying From Player   |   Value    | Amount                             | Total |
| -------------------- | ----- | --------------------------- |----- |
| Scrap Metal          | $50   | 7                           | $350 |
| Aluminium            | $70   | 2                           | $140 |
| Steel                | $90   | 1                           |$90 |
| Glass                | $35   | 1                           | $35 |
| Rubber               | $10   | 0                           | $0 |
||                    |                                   | Player makes $615 |
| -------------------- | ----- | --------------------------- |----- |
| Buying From Computer (Current) | Value    | Amount                             | Total |
| Scrap Metal          | $150   | 7                           | $1050 |
| Aluminium            | $200   | 2                           | $400 |
| Steel                | $250  | 1                           | $250 |
| Glass                | $80  | 1                           | $80 |
| Rubber               | $300   | 0                           | $0 |
|                      |                                   || Mechanic Pays $1780 |
| -------------------- | ----- | --------------------------- |----- |
| Buying From Computer (Proposed) |Value    | Amount                             | Total |
| Scrap Metal          | $65   | 7                           | $455 |
| Aluminium            | $90   | 2                           | $180 |
| Steel                | $115  | 1                           | $115 |
| Glass                | $38   | 1                           | $38 |
| Rubber               | $13   | 0                           | $0 |
|                      |                                   ||  Mechanic Pays $788 |
| -------------------- | ----- | --------------------------- |----- |
| Performing A Repair  |       |                             ||
| Material             | Price | Amount                             | Total |
| Scrap Metal          | $75   | 7                           | $525 |
| Aluminium            | $100  | 2                           | $200 |
| Steel                | $125  | 1                           | $125 |
| Glass                | $40   | 1                           | $40 |
| Rubber               | $15   | 0                           | $0 |
||                      | TOTAL                       || Mechanic makes $890 |
||                       | Profit buying from player   | $275 |
||                       | Profit buying from computer (Currently) | $-890 |
||                       | Profit buying from computer (Proposed)| $102 |

**Comment by MetaHatter** [comment]
As someone with hundreds upon hundreds of hours at the shop, Cloud's prices are ideal (I was going a touch higher intentionally). 

Full disclosure, I also believe they should never have been raised.  The mechanics never bought from the computers. It cut into their profits too much (as Cloud's example shows).  I believe that, in fact, the reason people were having issues selling scrap back then was not due to demand but due to the dozens of divers flooding the supply.  Mechs simply did not need to buy any more (and often joked about the dozens of people coming in asking if we wanted to buy scrap). 

The opposite problem now exists. If there are no scrap sellers, mechanics simply just stay closed.  It would COST them hundreds of dollars if matching "normal" repair pricing with computer mats.

The adjustments to delivery missions have now reduced the number of divers, and thus scrap supply, to a more reasonable level.   The original problem should no longer exist.

**Comment by AdeptCL** [comment]
> The opposite problem now exists. If there are no scrap sellers, mechanics simply just stay closed. It would COST them hundreds of dollars if matching "normal" repair pricing with computer mats.

I agree, but the above is what I will argue. How we've done it, is essentially provide a stock house that allows us to avoid "shutting because there's no scrap". This is something that is tracked, but essentially, if a mechanic's stock goes nil, we can give them a boost based on the upkeeping of the stock for the house. So I do have to disagree that the higher prices have caused this as there are alternate ways to combat it.

**Comment by MetaHatter** [comment]
Agree there are alternatives to avoid the shutting down but it doesn't preclude the shutdowns from occurring.  If the alternatives are too cumbersome, people will, and are, just finding other things to do.

**Comment by twooot** [comment]
This has been done. Glass prices will also be worked on but for the most part this should be implemented

**Comment by Smolnisno** [comment]
So I wrote a whole statement on the prices being reduced not being a good choice which I will paste onto here but I just want retype that the idea of prices being reduced wasn't really a good thing to do because of how hard it is already to make money in the city and as someone who does scuba often this really affects me heavily as I can't spend countless hours diving in the city cause of real life work but I do dive when I can but the prices shouldn't have ever been changed I feel as if they should've left it how it was before. Especially with rubber as very few mechanics use it and most use basic repair kits so it make super pointless and literally I make negative or barely break even now when doing scuba tanks 

Discord statement I made - all prices went down and rubber pricing went down hugely, and its like its already hard enough to make money in the city and scuba already takes 15min a tank and then the amount you collect was already reduced before too. It's as if the city doesn't even want us to make any money, because not all mechanics use rubber majority just use repair kits for tires so it being brought down from 50-40 to 8/ea.
if the issue was cause mechanics weren't having enough mats then it should be fixed onto where scuba divers can still make enough profit from doing a tank and not just barely break even cause that won't change a thing. If anything it'll make people not want to even dive anymore because they won't always be guaranteed to make money from mechanics as they don't need mats all the time and they'll lose money if selling to warehouse spots.

**Comment by MetaHatter** [comment]
This is a single step of a multi-step balance review.  The concerns you raise are valid and the needs of scuba divers are not being ignored. It's just a bad idea to change too many variables at once when balancing an economy.   Let the rest of the pieces fall in place over the coming weeks before stressing too much.

**Comment by twooot** [comment]
The idea of reducing rubber prices is to encourage mechanics to start using them over basic repair kits. Like MetaHatter said, we will be balancing the prices further, this is just a first draft to see how things go and what needs to be changed

**Comment by CloudTheWolf** [comment]
@Smolnisno this was more to balance the buying side of materials rather than cause issues for players selling, hence why the value is higher than what mechanic pay for from other players but bellow what mechanics charge for a repair

From a mechanic perspective this now prevents having to refuse service or even close when running out of scrap or other materials as they can use the computer to buffer while they wait for someone to come with stock to sell. Most, and I suspect all, mechanics like to keep a 750 storage vehicle such as the Rumpo full of materials.  Some even like to have 2 so they can rotate between emptying one while buying materials to fill the other.

**Comment by Smolnisno** [comment]
As I do agree with the statements made, I do have to point out that the main focus for me is the rubber as that is still a huge decrease and I have even confirmed with other mechanics that they mainly use only repair kits for tires and never buy rubber so as for the time I can respect and be patient.  On the other mats being balanced which is fine but for rubber that's an issue I can see growing fast . As well I wanna point out that with this decrease in price has made people who cant work life invader jobs do not wanna dive anymore to make extra cash and that is gonna make a issue for mechanics but for me I will be patient and await the results but I will speak for others and observe how the city reacts as I am one that dive often as well. thank you very much for the responses.
