### ISSUE TITLE
Suggestion: Add ability for cops to put callsign on cop car roofs

### ISSUE THREAD

**Issue by panpawn** [InZidiuZ/op-framework-issue-tracker#2104]
**Assurance:**
_Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?_
Yes

**Summary:**
_Write a summary of what your suggestion is about._
Add the ability for cops to put their callsign (or unit id, possibly) on their roof of their vehicles.

**Reason:**
_Why would your suggestion be a good change to the framework?_
This would help to differentiate between cop cars on a big scene, as well as make it more visible from Air-1 whose driving what car from above.

If/when personally owned cop cars come, this would be a nice addition to come with it. 

I believe every cop car should have a spot for it on the roof behind the light bar, perhaps with the exclusion of the bike unit.

**Comment by CloudTheWolf** [comment]
Would be nice to have this for Ambo's as well

**Comment by twooot** [comment]
This is a bit tricky to do and is more of an asset thing than a framework thing. We would have to add liveries for every single call sign for example or get it working using extras or something similar

**Comment by Sabakyo** [comment]
> This is a bit tricky to do and is more of an asset thing than a framework thing. We would have to add liveries for every single call sign for example or get it working using extras or something similar

It's slightly less clean and might be slightly tacky but something similar to a /description text on the vehicle might be a work around compared to actually modifying the livery?

**Comment by twooot** [comment]
> > This is a bit tricky to do and is more of an asset thing than a framework thing. We would have to add liveries for every single call sign for example or get it working using extras or something similar
> 
> It's slightly less clean and might be slightly tacky but something similar to a /description text on the vehicle might be a work around compared to actually modifying the livery?

that would look really bad and scuffy

**Comment by joevapes3** [comment]
So I thought about doing this, but it would end up being ALOT of work to accomplish. Since I would have to make single tuning mod liveries, not preloaded in our ytd files like our current ones are, for each pd vehicle, with numbers 0-9 in 3 different positions on the roof of the cars. Multiply that by the amount of pd cars there is and your talking somewhere around 480 individual tuning mod liveries that would have to be manually added to each asset. That's just way too much. Maybe in the future I will take the time to do this, but it would be quite the undertaking to make happen. So for now it will be a no.

**Comment by InZidiuZ** [comment]
I am closing this as it most likely won't happen in the foreseeable future, if ever. It would also require a lot of asset changes.
