### ISSUE TITLE
Suggestion: Add changing spot to Governors Office

### ISSUE THREAD

**Issue by claymstehling** [InZidiuZ/op-framework-issue-tracker#2120]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes

**Summary:**
Write a summary of what your suggestion is about.

Add a changing spot to the governors office

**Reason:**
Why would your suggestion be a good change to the framework?

This would allow all of state to be able to quickly change in the office without having to drive to do so. Useful for meetings when outfits need to be different for each kind, useful for sec comes in off duty and wants to change into on duty things, useful for if the people come in from being hidden and tac'd out to wanting to go to normal clothes.

**Comment by TheOneLizard** [comment]
how about lockers for state too? would allow for state sec for example to switch between casual and PSD gear, as I personally don't carry around everything I need for PSD at all times

**Comment by claymstehling** [comment]
I agree I think this would be very beneficial 

> how about lockers for state too? would allow for state sec for example to switch between casual and PSD gear, as I personally don't carry around everything I need for PSD at all times

**Comment by twooot** [comment]
I added the clothing spot, i'm not 100% convinced why we should have the lockers doe

**Comment by DaxterPancake** [comment]
I agree, I see no reason for lockers. 

Lockers aren't meant to be a permanent space to keep things. They were originally only to be used for mechanics to store their parts as we always ran into the issue of.. 'what happens if people start putting illegal things in there' as that's a place literally no one else can access. 

As far as I can tell, there would be no reason for a Governer to need that space. Use a house or a car.
