### ISSUE TITLE
Move Repair Kits to Mech Shops

### ISSUE THREAD

**Issue by claymstehling** [InZidiuZ/op-framework-issue-tracker#2131]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes

**Summary:**
Write a summary of what your suggestion is about.

Move repair kits to mechanic shops worktable.

**Reason:**
Why would your suggestion be a good change to the framework?

This would be a great change to the framework because it would make sense that you would have to buy the kits to repair your cars from the mechanic shop as well as bring more RP to those mechanics. It would be a nice additional source of income.

Currently the prices around town for buying mats are around 
Scrap 50 
Aluminum 70 
Steel 90 
Glass 35 
Rubber 50 

and from the computer is 
Scrap 65 
Aluminum 90 
Steel 115 
Glass 40
Rubber 15

So my thoughts are since basic are $200 and advanced are $500 the breakdown would be
2 scrap  1 rubber for basic repair kits = $160 from computer cost and $150 if they only bought from people selling mats
2 steel 2 scrap 2 rubber  = $390 if they buy from the computer cost and  $380 if they buy from people selling mats

Of course these prices might be off and depending on shops and such it may vary. But it's a rough overall idea and I think the little bit of cash they did make from these would go a long way. Obviously as well the math ended up being closer to the actual $250|$500 number I think that would be fine as well!

**Comment by AdeptCL** [comment]
I do like this suggestion. Similar to a Burger Shot situation, a mechanic shop can add a small increase in price to purchase an advanced repair kit. Basic repair kits should still be available at a tool store, just to give that freedom in case there are no mechanics.

**Comment by claymstehling** [comment]
> I do like this suggestion. Similar to a Burger Shot situation, a mechanic shop can add a small increase in price to purchase an advanced repair kit. Basic repair kits should still be available at a tool store, just to give that freedom in case there are no mechanics.

Oh thats a good catch, yeah I agree keeping basics at tool stores just in case there are no mechs will solve a lot of problems

**Comment by Amoxicot** [comment]
> I do like this suggestion. Similar to a Burger Shot situation, a mechanic shop can add a small increase in price to purchase an advanced repair kit. Basic repair kits should still be available at a tool store, just to give that freedom in case there are no mechanics.

That could be an issue that would be ran into. But at the same time, at the current state of the city, if every mechanic shop position was filled that is available in the city, that would be the only people IN the city and let's be honest, who does not know a mechanic in the city at this point?

There could be times that a shop is not open, but at the same time, what happens when the actual shops aren't open and someone needs a repair? They drive another vehicle until they can get it repaired.

Either way it will add something so I am all for it!

**Comment by AverageStatistic** [comment]
Make an option to buy it at tool stores and mechanic shops. There's not always mechanics around.

**Comment by zyronex** [comment]
I actually think it would be interesting if you could only get the repair kits from a mechanic shop, because it adds another dimension. If the shops are closed, the shops are closed... just like in the real world. If you frequently get into accidents, then you buy 2-3 repairs kits and store them in your car/house. Other than that, you can drive another car or ask a friend to buy you a couple if you're not around during a reasonable time. It could also encourage befriending a mechanic who can get you one when the shops are closed. In any of those cases, I think it just improves the RP and adds some realism.

**Comment by MetaHatter** [comment]
Basic repair kits should always be available. 
Advanced kits locked behind shops is an interesting idea.  Sold at mech computer?

**Comment by claymstehling** [comment]
> Basic repair kits should always be available. Advanced kits locked behind shops is an interesting idea. Sold at mech computer?

My thoughts is they would have to be crafted like wheels and doors

**Comment by joevapes3** [comment]
I think both types of repair kits should be available at both tool store and mechanics shops, however make the tool store cost 35% more than the mechanic shops. That alone will drive people to seek them from mechanics when they are in fact around, but if a mechanic is not available which does happen often, then people are not limited to no longer being able to get their vehicle repaired, or as other suggested a basic kit that would leave their car barely functioning as a result.

**Comment by CloudTheWolf** [comment]
I had a similar thought to remove the tyre repair feature from the repair kits and instead have craftable "spare wheels" that mechanics could make (using 1 rubber and 1 scrap) and could be obtained via chop. And have "Tyre Repair Kits" that are can be used up to 4 times, so1 use per tyre. (Eg if you have all 4 tyre out it takes all the uses)

**Comment by twooot** [comment]
Something like this has been done
