### ISSUE TITLE
Improvement in Delivery Job

### ISSUE THREAD

**Issue by keepcodingstar** [InZidiuZ/op-framework-issue-tracker#2134]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes

**Summary:**
Write a summary of what your suggestion is about.
Problem-I do the GoPostal delivery job very offen and i think it is great (to be honest no glitches no nothing) but the delivery pattern feels a lot forced and non realistic. 
If i am a delivery man in real i would never deliver a package like -
package1-forum drive
package2-roy lawre.
package3-forum drive 
package4-roy lawre.
....
...
..
.
why will I go to and fro for every package between blocks. I can deliver all packages from one block first then go to the other that would be lot more effective and would feel grindy.  
Suggestion- 
If We put a **Choose which packages to deliver Next** from all the remaining packages will help 
(Maybe you can balance this change by adding far away blocks together) 

**Reason:**
Why would your suggestion be a good change to the framework?
It will make the job more realistic and interactive where if a person does sort his packages correctly he will get to complete the delivery in 10 min rather than 15 min.

**Comment by TheOneLizard** [comment]
While this issue comes up, I'd also suggest to change the delivery vehicle to a Boxtruck rather than the big truck. It seems pointless to deliver 9 small parcels in a huge delivery truck. Plus, the big trucks are usually traffic hazards. Plus, the ramp of the truck can make you trip and receive damage. Sometimes that results in otherwise unnecessary frequent visits to the hospital. If the boxtruck worked like a reverse garbage truck, that would improve a lot of it.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
