### ISSUE TITLE
Updates to Pacific Bluffs Country Club

### ISSUE THREAD

**Issue by TheCuppcake** [InZidiuZ/op-framework-issue-tracker#2138]
Hello, 

When and if the interior of pacific bluffs is able to make it into the city, I would like to request the ability to use the mechanic shop. This will not be used as a new mechanic shop but i will be subletting out the shop to other shops as a second location i.e. Shops like SOL and Harmony who often do not receive as many customers. I would want 3-4 bays and possibly an outdoor bay for big rigs if possible. I believe giving the ability for other shops to use a new location could help for shops that are over saturated with employees or do not get enough business. This would also provide a chance for more people to start heading towards the north, encouraging them to maybe visit Paleto where new shops are opening like bubbas steakhouse. 

Also the blip i would like is ID: 803 and color ID: 13 

Thank you so much!

**Comment by TheCuppcake** [comment]
Think i put this in the wrong spot lol

**Comment by DaxterPancake** [comment]
You didn't follow the correct formatting but I'll comment this either way.

I don't believe it is fair to allow you to have a mechanic shop, subletting or not. Your establishment is already so many different things all in one, just because you don't plan to use it as your own Mechanic Shop does not mean that down the line the next owners won't aswell. We have so many mechanic shops, I see no need for your establishment that is already a hotel, resort, gym, casino, bar, etc etc to also be a mechanic shop.

**Comment by TheCuppcake** [comment]
Whereas I can see where u r coming from I do not plan to open the casino the bar or the strip pub in this establishment unless someone is hosting an event there. I agree I should not be able to run all things out of this property and have zero intentions on doing so. My primary every day functions will be the gym and I was hoping for the mechanic shop. I would only be able to open and use that shop because I have a mechanic job prior. I was told originally I would never gain keys to this property so technically this could never be ran as a private mechanic shop because there would be no job associated to it. If it not in the realm of possibilities I understand but please know I do not intend to powerhouse this business. It’s literally just a place I paid 80 dollars to put in the city for people to hang out and host events in. I am sorry if my request seemed at all like I was trying to create a business that does all things. I promise that is not my intent

**Comment by DaxterPancake** [comment]
Wether or not you decide to open them or not doesn't take away from my point that the next owner or the one after that may not respect the same choices you are. Thank you for purchasing the interior but these discussions might have had to happen before doing so, so that you don't feel like you are missing out on anything if these things aren't added.

The casino & strip club have no script need to make them useable nor are there many other competing places (other than VU) so I don't see them in the same ranking as adding a whole new Mechanic Shop for your establishment. If opening the mechanic shop plans to be open on a day to day basis then it only strengthens the fact that it is taking away from the other many mechanic shops, wether or not you're working there or you're allowing another buisnesses workers to work there instead. 

Again, this is my personal opinion and in no way is speaking for Legacy as a whole. I just see no need for it and instead would love the addition of new exciting things that won't effect many other people in the city with its addition.

**Comment by TheCuppcake** [comment]
I would’ve purchased regardless of what could or could not be added :) I ran the business for nearly 6 months with no interior so I would’ve done this either way. I definitely don’t think I am owed anything for purchasing the property either. All my plans were lined out in my business proposal and my original GitHub request though. Again, I am sorry if I’ve stepped on any toes that wasn’t my intent.

**Comment by TheCuppcake** [comment]
Also just want to reiterate that my original intent with the mechanic shop was to give the current shops a second location if too many mechanics were working in one or if one of the more remote shops was busy enough that day and wanted to work closer to the city. They would be encouraged to wear their shops gear and promote their shop and there mechanics. I can see and understand where you are coming from though and appreciate the input.

**Comment by TheCuppcake** [comment]
I am sorry for not correctly formatting this request and will be removing it. I do not want anyone to feel like I am taking business from anywhere else in the city and will work with the property as is for now until I can figure out a different avenue that wouldn’t affect any other businesses in any way. Thank you for your time.
