### ISSUE TITLE
Gun Cleaning Kit and degradation improvement

### ISSUE THREAD

**Issue by nmunson86** [InZidiuZ/op-framework-issue-tracker#2205]
Assurance:
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes I have

Summary:
Adding a gun cleaning kit to the server that would allow you to clean weapons that have degraded from time but not usage.  At the moment, guns degrade from usage and time and a red line replaces the white line to indicate this.  What if shooting degradation stays red but time degradation will show as yellow.  This would allow someone to know whether degradation is from shooting or time as well.  In addition, if you do not clean your weapon for a week, that week’s degradation will become permanent.  You will need to stay on top of cleaning your guns or they will lose value over time and possibly break.  I would say the cleaning kit would be $50 - $100 and fully clean the current time degradation once used on it.  I would think selling the cleaning kit at ammunation would make since and being able to get it from cleaning houses as a 2nd free source.  Or one of the other legal jobs as loot.  I would also have it take a full 30 – 60 seconds to clean the guns as well.  That way someone who has a lot of guns would either need to spend a lot of time cleaning or get a few people to help.  This would allow for RP while a group of people clean the guns.  Possibly a groups stash of guns.

Reason:
I believe this will add incentive to keep stocks low as it will take time to clean large amounts of guns as well as money.  People who want to keep sentimental guns clean as well as ones they prefer to use can do so.  But keeping a large amount of guns and forgetting about them will cost money over time as well as your time to clean them.  This could also add RP regarding businesses.  People could set up businesses around cleaning people’s guns, legal and illegal.  Someone who has a large stockpile of guns might not want to spend the time or money cleaning them.  So, they will either hire someone to clean them, or sell them off so they don’t lose money.  This would keep interest in guns and reselling guns but keep people from hoarding them.  If they are going to hoard them, they will have to spend a lot of time and money keeping them from breaking.

**Comment by CKylezz** [comment]
The weapon degradation, both time and usage was created to encourage a new weapon market. To cycle through weapons more often and dinamically.

Cleaning a gun and removing it's degradation is a lot cheaper then buying one altogether, if the idea is to make it so: it's bothersome, a slow and expensive process, so people still prefer buying other weapons instead of cleaning old ones. This is not the way to do it.

People have been sitting on weapons for years, scared of using them, but now they are being forced to use them or will feel they will go to waste. If you give them a tool to allow them to sit on them again THAT's what they are going to do.

Now, for guns with sentimental value:

I wouldn't mind someone cleaning and keeping a gun unused for sentimental/RP value. But for that, the cleaning cost of that weapon should be at least x1,25 the price of the actual gun. So it encourages people to buy them new unless it's really important for their character.

How you make sense that within RP beats me though

**Comment by AdeptCL** [comment]
Rather than it being a kit that can be purchased.
Why not a new building/area which can be controlled within roleplay? Like cleaning dirty cash... But cleaning / repairing guns?

That way, something is focused on improving and adding to roleplay.

**Comment by ShaquilleOatmeal007** [comment]
I think a kit or an area would be very helpful to everyone. This could allow people to start gun cleaning businesses or for groups to control the location and charge a tax. It could be very beneficial to role play around the city with guns.

**Comment by twooot** [comment]
If i were to add a gun cleaning functionality it would be very very expensive. The intention behind durability is so people dont keep the same gun forever but have to buy new guns, therefor boosting the gun market. Making the cleaning kit 100$ would be WAY too cheap and would completely ruin the whole point of degradation.
