### ISSUE TITLE
[alpha/tow] Local tow calls for tow driver job

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#2219]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.

**Summary:**
Adding local tow 'calls' to allow tow drivers to make money even when there isn't calls coming in.

**Reason:**
I have spent the last few weeks (since the new tow cars were added) being a tow driver and ONLY a tow driver. No repairing cars, just tow driving. It has come to my attention that it is extremely hard to make money as a tow driver. Not only do you have to basically fight other tow drivers for calls but you are having to always speed through the city and risk hurting someone or getting pulled over to get to said calls. You may even text, speed to the call and STILL not get there in time and someone else gets the call. There is also a very low amount of player owned vehicles that are able to be towed just through finding them abandoned. You also get a very low amount of money for towing local cars which doesn't add much of an insentive to do so, especially when you can be running delivery for 15min and make the same amount of money as 5+ local cars impounded. 

My idea to up the amount of money that tow drivers make is make it so that every 10-15min (or longer if you feel) an icon will appear on your map that is a 'local' tow call. This would be completely player based and not shared. You would drive to the scene, ensure you get the correct car (like the old chop shop, maybe you have a specific plate to grab) and then take it to the impound lot for a $300-$500 payout. 

Leaving it to only every 10-15min would mean that it can't be abused by doing it over and over again (not that it'd be any different from garbage drivers and delivery drivers grinding those jobs) and would just add an incentive for tow drivers to continue doing the job ESPECIALLY when it is very late in AU times where there is little to no cops or players in the city so therefore basically no money to be made for tow drivers.

**Comment by xarxesthegreat** [comment]
Towing was one of my favorite jobs I ever had on Legacy but I had to give it up because of the exact reason Daxter said - there's virtually no money to be made from doing the job, and it's a competition with every other driver in the city to get the calls. This would help so much.

**Comment by superiorchicken007** [comment]
I would love to see something like this implemented.  I did towing for a short time and seeing a script where it has you go out and tow a local car would be an amazing thing especially during the downtimes when there is nothing going on.

**Comment by QuantumSGT** [comment]
As someone who tows regularly if my shop is busy with mechanics I agree that side jobs would help out a lot. Granted charging a towing fee generates some income and it’s not too bad but making a thing would be good for those shops with stacked rosters

**Comment by rainymcjay** [comment]
[Lynette] [apologies for the essay]
While yes, more money and rp for tow drivers does sound great and I am totally on board with this suggestion, I personally think that even right now there still is a decent amount of money you can make towing, as long as you're doing it right and are willing to invest some time, even if there aren't any calls coming in. 15 local cars impounded on average equal to 1k made. That's just local cars that are parked illegally or left in the middle of the road. 

After a while towing you will learn of certain areas where local cars are almost always parked illegally, get left behind or hit into the road (source: even I as somebody with literally no sense of orientation am able to easily find impoundable (is that a word?) local cars by now). 

Plus in most of those areas it's several local cars so you can go back and forth between there and the impound lot and more often than not you will be able to find more local (or sometimes even citizen) cars on your way. 

I try to teach our new hires (everybody without previous experience starts off as a tow at Harmony) to do it that way and while some of them don't get it or don't have the patience and/or time required, the ones that do follow through with doing tow that way usually end up coming to me and telling me that they're surprised with how much money they've made "just" towing. 

We even had some people become mechanics and still continue doing tow more often/for longer hours than mechanic work. Then again, Harmony isn't necessarily the busiest shop when it comes to customers so that might also be an important factor.

**Comment by coalaura** [comment]
Towing has changed a lot since this issue was opened, closing due to it becoming partially irrelevant due to the balancing changes and new things added to tow
