### ISSUE TITLE
[alpha/law?] PD/Criminal cuffing revamp

### ISSUE THREAD

**Issue by eatAnus** [InZidiuZ/op-framework-issue-tracker#2228]
Assurance: Yes

### **Summary:** 
I'm gonna try and explain as to how cuffing in OPFW could be improved and enhanced in three different ways.

Firstly being able to resist cuffs with any sort of minigame would be great, but a personal suggestion is that there be no minigame but instead what happens is that whilst cuffing is happening you have to type /resist as the animation is happening, this could also be limited to a amount of 2-3 times.

Another way cuffs could be improved upon is to make it so criminals get two types of lesser quality cuffs(maybe basic shit ERP cuffs and advanced cuffs)and the PD gets stronger top quality cuffs as to make the third idea more viable. 

Lastly and the final way cuffs could be improved on is that individuals who have been cuffed for long amounts of time, the cuffs start to degrade and after so long you are just able to /breakcuffs with a minuscule chance of actually doing so or alternatively you could use a advanced lockpick to attempt to free yourself kind of like hotwiring a car, that also means that the lockpick could break. I'd like to think that these ideas are simple and fit perfectly with OPFWs style.

### **Reason:**
Cuffing in OPFW has to be one of the most outdated and overlooked mechanics in the server, it's been the same since the start, correct me if I'm wrong. I could go over everything wrong with the current cuffing system but why do I have to repeat the constant complaints of others when it's obvious. Not saying it was bad a few years ago but seeing as how OPFW is progressing more towards advanced roleplay mechanics now, it'd be nice if a newer cuffing system was introduced for more quality roleplay instead. Cuffing as it is now is a immediate RP killer, for example: a lowly unknown criminal rolls up to a swat leader, they chat a little, things escalate and then the criminal decides tackle the swat leader and cuff him and place him in his car and take off, vice versa.

**Comment by breadandchicken** [comment]
I think this is a good suggestion. Foot chases are basically nonexistent for the simple fact if you get tazed, you get insta cuffed. If we had a way to break cuffs I think criminals would be more willing to sit and interact with police during a stop instead of immediately hopping onto a bike and speeding off.

**Comment by mxttx** [comment]
~~Skill~~ RP checks like dead by daylight

**Comment by xarxesthegreat** [comment]
I agree with Dex that this shouldn't be a /command due to the fact this is something that someone could just bind through the F8 console and be able to spam that keybind to break out instead of having to type it over and over, which effectively just turns it into a game of people that know about F8 menu binding and those that don't. Putting it as a key you need to press during a small very specific window (call it a quick time event if you'd like) would level the playing field a bit more.

**Comment by twooot** [comment]
Added the ability to lockpick cuffs

**Comment by TheCuppcake** [comment]
The ability to have a minigame to "break" cuffs could be a fun new way to continue an rp scenario and it leaves the outcome fully in the hands of the crim at that point. I dont think they should be able to break hardcuffs though.

**Comment by coalaura** [comment]
> The ability to have a minigame to "break" cuffs could be a fun new way to continue an rp scenario and it leaves the outcome fully in the hands of the crim at that point. I dont think they should be able to break hardcuffs though.

Although considering the majority of opfw servers are public servers with a lot of idiots i already see this being abused tf out of

**Comment by Psycho1952** [comment]
How would it be abused? If its possible maybe to make it like to break out cuffs 2 times while they are getting cuffed ... for example they get cuffed first time he breaks cuffs 2nd time he breaks cuffs 3rd time he tries to break cuffs he gets instantly hard cuffed. This is just my opinion.Because lockpicking cuffs dosent work with some people because officers go instantly for lockpicks.

**Comment by eatAnus** [comment]
bump

> being able to resist cuffs with any sort of minigame would be great, but a personal suggestion is that there be no minigame but instead what happens is that whilst cuffing is happening you have to type /resist as the animation is happening, this could also be limited to a amount of 2-3 times

pls consider resisting handcuffs a limited amount of times as they're being used so police can yell "HE'S RESISTING!"

**Comment by coalaura** [comment]
As a trial, i've added a quick time event now whenever you get cuffed. If you do the thing (press E at the right time minigame) it will cancel the cuffing. Each attempt (no matter if successful or not) will increase the speed for a few minutes to make it harder to do many times in a row. We'll have to see if PD will mald with this change, the second they have someone use it against them and potentially adjust it further.

This also means however that /lockpick_cuffs is no longer a thing. Its either quicktime event OR lockpicking cuffs afterwards not both.

**Comment by coalaura** [comment]
> COOL! did you manage to make it as a thing if they fail the minigame to make it insta going into hard cuffs?

Nah, dont think thats needed. It does ramp up speed wise tho so it will just get harder and harder
