### ISSUE TITLE
Suggestion: Registration of pistols at courthouse

### ISSUE THREAD

**Issue by mxttx** [InZidiuZ/op-framework-issue-tracker#2235]
**Assurance:**
Always ❤️

**Summary:**
Able to pay for an scroll item at the courthouse “shop” which allows for a one time use to be able to register any pistol in your inventory to yourself. This should prioritise 1st slot, and if it doesn’t find a “register-able” pistol, looks at the next slot, and so on. This scroll item should cost more than 2000 ideally, so that people get the idea that this is to be used with pistols you can’t normally register.

 I will re-emphasise, pistols only. It makes no sense for a courthouse to register an automatic weapon at the moment for any subdivision, but I assume that is easily replica table and another item be made in the future to do exactly that (for rifles). 

**Reason:**
We have lots of pistols for use on the framework yet lots of them come as unregistered simply because it is not purchased from ammunition.

This will benefit criminals and legal people alike as they will finally be able to register an illegal pistol to them. 

This will help cops to find who owns the gun if they choose to register it and simultaneously use it in a crime. 

This will help criminals to find out who stole their sentimental pistol of choice. 

This will help legal people as they won’t be able to be arrested for being in possession of a unregistered pistol. Note: I am not sure if other subdivisions have such laws, but regardless if it is illegal to do so, the gun itself wouldn’t suddenly become legal unless the DOJ specific to that subdivision said so. 

Everyone benefits! Thanks 🙏

**Comment by twooot** [comment]
For now i added /register_weapon which is a superadmin command

**Comment by vol5** [comment]
Great breakdown from matt.

Courthouse would be alright IMO. Pistols only is reasonable. Overall, this would be a huge value add. Hundreds if not thousands of players have wanted something like this for the longest time. 100% would be a positive change for the community.

IMO if you are opposed to letting someone freely walk in and register at the Courthouse, make an Ammunation Job Structure and lock the command behind it. This would create more RP around it and a new business for someone to own.

Either way. I feel that this should be provided to the vast majority amongst all subdivisions since its giving players more choice. You can argue the hyper-specifics but from how matt outlined it, a change like this looks worthwhile to me.

**Comment by ravicant** [comment]
And there should be a way to remove and add a Gun Licence buy cops by giving the proper training or some shit in RP which will increase RP too without a license you can buy guns which also reduces the amount of RDM happening on the server mostly new people join the server and buy guns and just start shooting people.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
