### ISSUE TITLE
Remove EMS/PD Medkits

### ISSUE THREAD

**Issue by TheOneLizard** [InZidiuZ/op-framework-issue-tracker#2255]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
- Yup

**Summary:**
Remove the EMS/PD medkits from their stores.

**Reason:**
This will solve part of the problem stated in issue #2249 
Medkits are very affordable, emergency service personnel should find no problem buying them at regular stores. Neither will it be a big deal if they are stolen from their inventory by whoever. Just buy new ones, suck it up, they're really not that expensive.
Additionally, this will resolve the situation of emergency services only having their own medkits at hand, and not being able to fulfill a community service for less fortunate citizens by just giving them a medkit.
Generally speaking, it's not a special item, everyone can have it, so I don't fully see the reason as to why it needs to be specific to these jobs.

**Comment by superiorchicken007** [comment]
I made the suggestion earlier for regular non-ems first aid kits to be added into the pharmacy which was implemented about 1-2 months ago where EMS can buy regular first aid kits that they can use or be handed out to citizens for a slightly cheaper price.  Citizens can also stop at Mount Zonah and go to the pharmacy and buy first aid kits for $5 less as well.  Ever since this was implemented for EMS I have never purchased any EMS first aid kits.

**Comment by twooot** [comment]
Î like the idea however will i not remove them from their store. I'll have them be non-PD when they buy them but PD should have their own store in their PD cause it would make no sense for them to have to go to a grocery store to buy medkits
