### ISSUE TITLE
Suggestion: Lower NOS Refill and Increase Engine Damage

### ISSUE THREAD

**Issue by antonettedorado98** [InZidiuZ/op-framework-issue-tracker#2261]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Summary:**
So far, NOS prices have been directed to avoid the frequency of use during robbery jobs - such as Banks and J Stores. At $3000 per Refill, Resale has been priced between $3500-$4000, this markup making it extremely difficult to sell to a majority of the drivers in the server. 

Pricing refills at $1000, for it to be sold at $1500-$2000 will give more players access to the an amazing addition to the city without pricing and profit being the main factor. With this dramatic price decrease, engine damage should change drastically. As of now, using a whole bottle at once damages the engine beyond use and repair. I believe, if a price change were to be issued, using half a tank all at once should damage the engine the same way a whole tank would right now.

**Reason:**
The racing community in Legacy is a major part of everyone's roleplay. With midnight being included, its only continued to grow. I would love for the pricing to cater to these drivers for them to explore and have fun with. Pricing is still high and quantity can easily be controlled in roleplay. The engine damage will make it a lot harder for robbers in the server to completely take advantage of NOS during chases.

**Comment by SirPiff** [comment]
As much as this is true, I must say I'd rather it be changed differently, as I believe the damage itself is pretty sufficient in the current state.

**Why is NOS such a big issue at the moment when it comes to jobs, and why is it so expensive currently?**
I personally believe it's because it's simply too strong without the modified engine damage & pricetag.

**How I believe the issue should be solved**

- Lowering the boost amount by a **substantial** amount, as NOS should only provide a *small* boost around corners.
- Capping its use at 100mph instead of 180. Currently, NOS stops doing anything at 180mph, lowering this would avoid highway blasting with NOS to quickly escape Speed Units, and encourage its intended use for being used out of corners
- Compensating for the much lower boost amount with a larger reservoir of NOS.

These changes could also possibly work with *lowering* engine damage & the price.

At the end of the day, what both of us would like is more accessible NOS that isn't used as a "strong tool" to get away, but rather a fun one that can be used more widely.

**Other**

Currently, Purging happens automatically after boosting, I believe instead, it should be made into a different function all together as a "cosmetic" thing to be able to do at any time for no cost, and have it not do anything for the car but just look cool for meets and photos.

**Comment by Skai97** [comment]
Honestly, I'm gonna agree with that Piff is saying, NOS should be nothing like it currently is. It should give a small boost like "1.2x multiplier" More boosts per can and way cheaper. Right now when i use it i feel like I'm driving the Scramjet or Voltic thruster that's in GTA online

**Comment by twooot** [comment]
I went over it with Howie (Nott) and we did a bunch of changes
