### ISSUE TITLE
Lockers for green wounderland

### ISSUE THREAD

**Issue by Puucko4090** [InZidiuZ/op-framework-issue-tracker#2277]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
lockers for  green wounderland

**Reason:**
It woulde wastly improve quality of life for us since we buy alot of fertilizer , bucket, seeds, expierd water etc, and get alot of trunk wipes

**Comment by tftwsaaron** [comment]
this would be a great addition to the store. currently we are just renting houses so that our employees have a place to put there product and can have access to more if they sell out and a manager is not around to resupply them.   a simple locker like every other workplace in the city has would be an amazing improvement.

**Comment by twooot** [comment]
I added shared storage in the back of green wonderland which should accomplish exactly this
