### ISSUE TITLE
Weed improvements

### ISSUE THREAD

**Issue by TheOneLizard** [InZidiuZ/op-framework-issue-tracker#2331]
**Assurance:**
Always.

**Summary:**
- Reintroduce the weed field, but limit it like we limit sales.
- Weed field only gives you minor quality weed, not giving you the same effects as weed grown in a house
- Weed grown in a house stays the same.
- Weed picked will only give you quarters, no more ounces.
- Remove the stress reduction induced by food.
- Have Green Wonderland be able to craft high quality blunts, with better effects than normal weed grown in a house.
- Add a paper item to craft blunts.
- Make paper a random item in dumpsters.
- Add paper as an item to the Green Wonderland store.

**Reason:**
- Give weed more purpose again
- increase interactions by having to pack weed to ounces
- give Green Wonderland more purpose again and reward them for their work they've put in so far
- give dumpster diving some purpose again for the paper item
- stress becomes a more interesting issue again, rather than sth that doesn't bother anyone anymore.

**Comment by nunsia** [comment]
The weed field is not based on the developers to put back in. It's server based and I do have the power to turn it back on, however I did not want businesses like Green Wonderland to suffer. 

I have seen a few things added to do with weed, so I'll speak with Ben about the weed field to see if it would be dangerous for GW or not.

**Comment by superiorchicken007** [comment]
I would have to agree with Sia on this but what would be cool is if the weed field does make a come back (in the international server) make it so when you pick the plants you are only able to get it rolled into joints (need to buy rolling papers at green wonderland) or make it that Green Wonderland has to refine/package the weed in order to be sold to locals.  This will bring more RP to both Green Wonderland and also the economy of the server.

**Comment by vol5** [comment]
@nunsia @superiorchicken007 Sia and I spoke on this inside the Legacy discussions section back in June. The goal for this post below to was to address both of your concerns and prevent Green Wonderland from suffering if the weed field is brought back. Suggestion 2232 has been completed thanks to Ben.

https://github.com/InZidiuZ/op-framework-issue-tracker/issues/2332

As it stands, in International, you cannot roll any joints without the papers from wonderland being used. So this would protect from the consumption side of things. Chicken does make an interesting point with having packing involved as well with the business. But I'm fairly certain that (packing) locked behind GW would not fly since it kind of sits as a gang entity that can be controlled if I can remember right? Then again that is up to yall.

**Comment by superiorchicken007** [comment]
I'm not talking about fully locking it behind GW. Have the option of getting it packed at GW for a higher quality product that will sell for slightly more (due to the cost of getting it done at GW) but also have the ability for the other one to be ran by a gang.  

Yeah I knew about Suggestion 2232 which is why I said I said you will need them in order to be able to roll the weed into joints.

Not sure how the "legality" of it will be with GW packaging it due to the current penal code and possibly being charged or have the ability of GW to maybe have a "membership" that they can sell to someone IC where they can go in the back and package it themselves.

**Comment by twooot** [comment]
> Reintroduce the weed field, but limit it like we limit sales.

For the billionth time **this is something configured in the server config** we didn't get rid of the weed field, it was simply disabled for the international division.

> Weed picked will only give you quarters, no more ounces

i dont like the idea, i think picking is good where it is rn

> Remove the stress reduction induced by food

This was done to encourage people to go to restaurants like burgershot or bean machine, so no

> Add a paper item to craft blunts.

We got rolling papers sold my i believe green wonderland now
