### ISSUE TITLE
Physical Pilots License QOL update

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2397]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
Currently we have an out of city Pilots Licenses, in a similar way to https://github.com/InZidiuZ/op-framework-issue-tracker/issues/2361 having this be something that can be issued and carried in city would make it better to check licences in-city.

Example image
![image](https://user-images.githubusercontent.com/7809366/181226453-fa8a47a9-bd38-48ce-b695-f70324ac58bb.png)

**Reason:**
Why would your suggestion be a good change to the framework?
I believe this would be a QOL improvement for hunting with having a physical license that you can carry in the city that can be checked by PD instead of them going externally into a database to look it up.

**Comment by twooot** [comment]
I'll add the pilots licenses but it'd be annoying to have the different pilots licenses display on it so that part wont be added. It'll be lice the hunting license

**Comment by twooot** [comment]
Done

**Comment by TheOneLizard** [comment]
sorry to jump in here again, but for the license list, wouldn't it be possible to just shortcut them, like for the different types of driving licenses irl?

so it'd be:
fixed wing: FW
helicopter: H
fixed wing heavy: FWH
helicopter heavy: HH
performance: P
CFI: C
utility: U
management: M
military: X

In the suggested picture above, instead of listing the licenses on the right, there'd be a photo of the person.

The licenses would be listed with the shortcut names on the left side right under name

Again, sorry for jumping in again, just couldn't react to this early enough (you're hella quick :D )

**Comment by twooot** [comment]
![yes](https://raw.twoot.org/mIkiwetE38.png) with the addition of licenses to the mdt no it would just be a pain to implement cause i would have to treat the pilot license completely different to the hunting and fishing license. I'm expecting to probably add more liceses as they are requested so i'd trather keep them the same
