### ISSUE TITLE
Suggest some changes to Arena and Zombie Pills

### ISSUE THREAD

**Issue by RustyWaters07** [InZidiuZ/op-framework-issue-tracker#2403]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
I would like to suggest adding "Rental VR guns" for zombie/arena pills. As well, for Zombie pills I would like to suggest either 1. being able to pick a spawn area, or 2. randomizing the spawn area when you pop the pill
**Reason:**
Why would your suggestion be a good change to the framework?
We have a bit of an issue with the majority of patrons not wanting to use the VR pills in the arcade. Part of the problem is they may want to use something better than a pistol. Adding Rental weapons (not functional outside of VR) would address that issue by allowing people to use VR weapons inside the simulated environment rather than somehow using a real weapon. I think that would not only balance it but also make it more realistic from an RP perspective. 

Another issue is that people appear to have their own spots picked out where they prefer to grind Z-Pills. This limits interaction to whenever they need to re-up and honestly makes Z-pills a little too overpowered. I would like to see the spawns either randomized, making RNG a factor like most video games or allowing people to pick an area to spawn in so they aren't forced to be in/around the arcade if we end up making them use them here in the long run.

Certainly open to any discussion, just wanted to share some thoughts so we can balance without crushing this in the future.

**Comment by MetaHatter** [comment]
IMHO the "rental weapons" could just be a way to preset a loadout that you get when you enter VR and when you leave they are removed.   Either that or just standardize the loadout with a preset pistol, melee and 2 hander.

The big thing to consider in whatever solve there is... There's a certain fairness in keeping the weapons used accessible and/or lower grade.  Allowing someone to bring in a, much harder to acquire, mk2 two-hander will severely disadvantage everyone else in the match.

I agree with Zpills taking you to a random (predefined list?) location somewhere in VR.  Reduces min-maxxing.

**Comment by scufflord** [comment]
I don't think this would be a good idea, if only for the fact you'll then have a bunch of people running in and out of your establishment with illegal weapons. The current system where the arcade is essentially functioning as a middleman for an object that BY ITSELF isn't illegal but drops illegal items feels like a good point for it to be at. You provide a consumable that people can come through and purchase instead of having to go grind for them from trash if they want instant gratification. Where they use it at doesn't matter as much, because it's still in and out traffic being driven to your business at the end of the day, and usage of them elsewhere in the city acts as good advertisement for you as well. If someone stumbles across people doing z pills on Grove Street and says "Hey, I wanna try where do I get them?" they will then be directed to the arcade to purchase some pills. 

Personally, I like the way z pills work currently where they put you in a random spot in a certain radius from where you take the pill. It gives people the additional challenge of having to hunt for good spots to be able to do them, and it acts as both a fun shooting activity and almost a tower defense type game so you can try to stay alive for as long as possible.

**Comment by coalaura** [comment]
I dont think you should get weapons for Z pills since they drop items that you can then actually use in RP
