### ISSUE TITLE
Are you supposed to be able to see people in your apartment?

### ISSUE THREAD

**Issue by SteezyRen** [InZidiuZ/op-framework-issue-tracker#244]
**Reporter:**
Steezy

**Summary:**
I go into my apartment and find someone who is afk just sitting on the toilet.

**Steps to Reproduce:**
1. Go into apartment
2. Have someone afk in their apartment
3. See that person in your apartment

**Expected Results:**
You see someone inside your apartment that I ddon't think should be in there.

## Additional Information

**Screenshots:**
![FiveM_GTAProcess_2019-07-20_18-39-16](https://user-images.githubusercontent.com/49498560/61585976-436b8800-ab1e-11e9-8d96-7ed0af45bcd7.png)

**Game Resolution:**
1920x1080

**Player Data:**
![FiveM_GTAProcess_2019-07-20_18-44-01](https://user-images.githubusercontent.com/49498560/61585981-5bdba280-ab1e-11e9-8495-a532580cdbaf.png)

![FiveM_GTAProcess_2019-07-20_18-41-21](https://user-images.githubusercontent.com/49498560/61585982-6302b080-ab1e-11e9-8e3b-4c5be8c88026.png)

**Comment by SteezyRen** [comment]
**Note:**
Fortunately, you aren't able to kill them or interact with them.

**Comment by InZidiuZ** [comment]
Hey,

Damn it. I changed the "instancing" method used for the motel rooms, which worked on OneSync (tested it with a secondary client), which was a better method of doing it as it would completely remove any other peds, instead of just removing collision & making them invisible. I'll revert it.

**InZidiuZ**
*OP-FW Developer*
