### ISSUE TITLE
Make Tow Drivers into Tow Drivers

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2443]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Remove the ability to repair and use workbench from mechanic "tow driver" role.

**Reason:**
Why would your suggestion be a good change to the framework?
- To ensure that the city has dedicated tow truck drivers.
- To increase values of individual mechanics
- To create an incentive for promotion in the mechanic role.

**Comment by CloudTheWolf** [comment]
As a mechanic shop Owner I would have to disagree with this.

For Harmony (I can't speak for other mechanic shops) we have this process in place:

- We Hire someone as Tow
- After 4-5 days We show them how to do repairs and once they are comfortable, we authorize them to fix their own vehicles when no one is at the shop.
- After 7-14 days (Depending on activity) we look to promote them to Intern Mechanic

**Comment by DaxterPancake** [comment]
Preferably I would like to see a revamp of the tow job in general then before we remove an avenue for them to make money. As a tow driver people would barely tip me. The most I made on tips was $100. I had bought them a Jerry Can. That was more than $100. People don't tip tow drivers because they pay the mechanic that fixes their car from the tow. Tow drivers can tow other cars but tow calls are rare for abandoned cars and even rarer for player owned abandoned cars. It is VERY hard to make some good income without being a scumbag currently as a tow driver. Don't restrict them further.

**Comment by MetaHatter** [comment]
> As a mechanic shop Owner I would have to disagree with this.
> 
> For Harmony (I can't speak for other mechanic shops) we have this process in place:
> 
> * We Hire someone as Tow
> * After 4-5 days We show them how to do repairs and once they are comfortable, we authorize them to fix their own vehicles when no one is at the shop.
> * After 7-14 days (Depending on activity) we look to promote them to Intern Mechanic

So at 4-5 days they are intern mechanics, but with a lower paying role for an extra 2-10 days for some reason?  The literal definition of Intern is what you describe.  

> Preferably I would like to see a revamp of the tow job in general then before we remove an avenue for them to make money.

I towed as a primary job for 6+ months (I even towed when I was a mech as I enjoyed the loop) and am VERY aware of the difficulties sometimes making money.  But it is an entry level WL job with a very short path to promotion and there is a drought of tow drivers in the city.

I drive around and see disabled citizen cars scattered around EVERYWHERE.  Especially now that Dannys get free cars.  I don't see that 1-2 weeks of "below mechanic" money being a deterrent in any way.

**Comment by CloudTheWolf** [comment]
The only other concern is you'll end up having too many tows around the city. There seems to be a cycle of: Not enough tows on duty -> more tows are hired -> Too many tows on duty -> Tow drivers either get promoted or leave because they are not getting enough work so then there are no longer enough tows on Duty.

**Comment by MetaHatter** [comment]
Fair point.  Things like that tend to equalize with time. Supply and demand.

**Comment by twooot** [comment]
I dont really think this is a big issue rn, more like daxter said maybe revamp the tow job eventually
