### ISSUE TITLE
Add /livery and /extra for buyable emergency cars.

### ISSUE THREAD

**Issue by GasCan42** [InZidiuZ/op-framework-issue-tracker#2451]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Add /livery, /extra and maybe /color where you could repaint your emergency car.

**Reason:**
Why would your suggestion be a good change to the framework?
When you buy an emergency car, in order to apply a different livery or extras, you have to visit the LS customs. I think it's better for police officers and EMS to change their vehicle liverys/extras in their own station's garage without having to go to the mechanic's shop. Since you can already repair an emergency vehicle in the station's garage, I think you should be also able to change your buyable emergency vehicle's livery and extras as well.

**Comment by MetaHatter** [comment]
I think one of the points of emergency vehicle ownership was so you COULD set all of these at LS Customs and not rely on magical / commands.

**Comment by GasCan42** [comment]
But make it that you can do it inside the police stations. Police stations have their own repairshops.

**Comment by ThisIsNotDex** [comment]
At the very least, could the price of emergency vehicle liveries be changed? For people who need to be able to change their livery on the fly, have to spend ~$1500 every time is annoying.

**Comment by MetaHatter** [comment]
That is how it used to be.  It was changed for a reason.  Pricing for Liveries can definitely be looked at, but I don't see the change reverting back to how it was.  

There are very few reasons to need to constantly change your liveries/add-ons aside from "I feel like something different today". In which case, $1500 is not extreme when you can make 10x that in one hunting trip.

**Comment by CloudTheWolf** [comment]
Unless a player is changing departments there is verry little need to change the Livery on the fly.

Eg you would not need to change the livery constantly between BCSO and Police.

As for doing it at PD, there is no need since doing it at a customs shop doesn't require other player, unlike a mechanic shop for repairs. (Hence why it's encouraged to use a mechanic, but if none are open or you need to attend a scene urgently you can /repair)

You just buy the vehicle, go to Benny's next to PDM, change the Livery and paint job if required and your good. 

A thought could be to default the livery based on Department (SASP,SAHP, BCSO), but I don't see a need for that ether since by the time you join other departments you should be able to afford changing the livery.

**Comment by twooot** [comment]
No. Like every other player PD and EMS will have to go customize their vehicle in a customs shop. The whole point of making cars ownable is that we could finally GET RID of /extra and /livery. Like others said, magical commands that change your cars appearance with the press of a button is not something we want
