### ISSUE TITLE
Gang System

### ISSUE THREAD

**Issue by Milan345** [InZidiuZ/op-framework-issue-tracker#2468]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes

**Summary:**
Concept: Gangs will be able to claim territories, by placing or drawing a flag/graffiti. On claiming a territory, the territory will be marked on the live map (https://cdn.discordapp.com/attachments/902193697905598535/1014807149290999819/unknown.png) and there will be spawn of locals of that particular gang. Other gangs will be able to rob the locals for small amount of money or drugs, which will send a notification to the gang. There will be also option of the other gangs to destroy/replace the flag/graffiti, if there are enough number of gang members online.

additional:
- gang holding the territory will be able to collect a small amount of paycheck from the locals
- can sell drugs to the locals(optional)

**Reason:**
Why would your suggestion be a good change to the framework?
As it would be something new.

**Comment by twooot** [comment]
graffiti has already been suggested here: #2402 

Regarding the marked areas on the map i feel like that would ruin so much RP. Gang blocks shouldn't be public knowledge, irl you dont look on your gps and see what gang owns what block.

Allowing them to sell drugs right on their gang block would make grinding a lot easier and ruin any police rp since they can really easily just hop back in their houses since its right on their block
