### ISSUE TITLE
[vehicles/garages?] Ownable Helicopters and Planes

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2488]
Summary: Make most Helicopters and Planes ownable by civilian players. Along with adding repair spots for the helipads/hangars.

With the recent addition of PD starting to purchase their cars. It would only make sense for civilians to have the eligibility to purchase Helicopters and Planes. Storage is the main blaring issue IMO on why this should be possible. The spawnables are not reliable and most of the time eat all the items put inside along with not being able to store them. This is a great moneysink as well. 

Requirements: 

[Repair spots] 
> like PD - accessible via the person inside the vehicle
> one at each heli/hangar

This could possibly open up customizations for helicopters and planes in the future and encourage a lot more usage of these entities. The amount of RP that goes unplayed because of the current state of these vehicles is unfortunate. We can go to Paleto soon tm and it sure would be amazing to store items along the way. 

Reasons:

- QOL

- Encourages use

- Money sink

**Comment by TheOneLizard** [comment]
would anyone be able to buy aircraft, or only licensed pilots? And if only licensed, does that include fake licenses?

**Comment by King2704** [comment]
Only people with a license would be able to purchase helicopters, legal or fake license. If the license gets taken away by PD or someone else you lose access to the garage and can no longer pull out helicopters or planes.

**Comment by vol5** [comment]
> would anyone be able to buy aircraft, or only licensed pilots? And if only licensed, does that include fake licenses?

I agree with what @King2704 said. That would make the most sense.

**Comment by kaycorriher** [comment]
I am not sure this is the best way to go. I can see several people getting mad when their 200K Airplane gets taken away from them because of inactivity and they need a refresher.

**Comment by coalaura** [comment]
I don't like this idea because of a bunch of reasons:

- When someone looses their license, what happens to the aircraft?
- Can people with illegal licenses purchase aircraft?
- How do you get repairs for your aircraft? (And no adding a new job to get repairs would be stupid since there is probably like 2 planes needing repair a month, making it not worth it)
- How do you customize your aircraft? They don't really fit into an LS customs (lmao)

In addition to that, right now, we barely trust people to be able to rent aircraft, I am not comfortable allowing them to be owned.

**Comment by vol5** [comment]
Addressing the points you made.

- The access to pulling out the aircraft would be lost since its tied to the license, but you as a player have the option to sell it back to the garage like officers can with pd cars.

- Yes, Its already hard enough to get the illegal license in RP why gate them from a money sink? This license can also be lost and point 1 above this text applies.

- No job needed if it was something simple like an aircraft/helicopter/boat repair kit.. This would be extremely beneficial. (1k at the airport and or give mechanics the option to craft them)

- There is an existing Benny's for aircraft in gta online. This could potentially be reused and added somewhere like here [Location 1](https://cdn.discordapp.com/attachments/917478094015717387/1049829041596805160/image.png) or [Location 2](https://cdn.discordapp.com/attachments/917478094015717387/1049829556154028042/image.png)

As for your final notes. Please heavily reconsider your position on them being owned. I feel that this would be very beneficial on many fronts. The entire system is heavily gated around RP. Ownership would prevent more people from doing stupid shit with them and or lending them out. Stakes would be added since its a personal vehicle.

**Comment by coalaura** [comment]
> The access to pulling out the aircraft would be lost since its tied to the license, but you as a player have the option to sell it back to the garage like officers can with pd cars

People would be mad they loose their 200k aircraft. Also, officers cannot sell back their vehicles if they get fired

> Yes, Its already hard enough to get the illegal license in RP why gate them from a money sink? This license can also be lost and point 1 above this text applies

Would completely ruin the RP of having an illegal license cause nobody would want to purchase a plane if they have a a very high risk of loosing all that money they just spent

> Ownership would prevent more people from doing stupid shit with them and or lending them out. Stakes would be added since its a personal vehicle.

It wont, people already lend out their personal cars for j stores and bank robberies, knowing they will be absolutely fucked afterwards. Additionally if the repairkit was 1k nobody would care since it'd be insanely cheap to repair your vehicle

All in all i do not believe ownership of aircraft should be a thing. Boats? sure. Aircraft? no
