### ISSUE TITLE
Tablet Command

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#2499]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
If there is a command to open the tablet that would be great, Example: /tab or /tablet as I checked the server-changelogs it shows /email opens up the tab but it seems not to be working.

**Reason:**
Why would your suggestion be a good change to the framework?
You don't have to always open your inventory then open up the tablet to view the tablet screen.

**Comment by CloudTheWolf** [comment]
The /email command is no longer the case (Superseded by the tablet item)
Rather than a command, maybe have it as a keybind (Similar to P for phone) 
Another thought could be to combine all "Tech" into a Tech Menu (Similar to the clothing wheel) which lets you select from all the usable tech in your inventory (Phone, tablet, Raspberry Pi, Tuner Chip, Radioetc)

**Comment by TheOneLizard** [comment]
On the other hand, a phone is something you whip out casually, in a quick manner. Everything else I'd say takes some time to either take into your hands / out of your bag / or to get configurated - in other words, I don't think it's so bad to go into your inventory to grab it

**Comment by twooot** [comment]
done
