### ISSUE TITLE
Suggestion - Expand /drag_out

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2573]
### Assurance

I have read the `README.md`

### Summary

Expand the /drag_out command for use in more situations.

on /drag_out
If the vehicle is locked, break the glass, reach in to unlock the door and drag the person out (animations already exist in GTA)
If the vehicle is unlocked, open the door and drag the person out.

Add an interruptible 3-5 second timer to allow the animations to play and keep it from being abused.

If the target car moves, X is pressed or the extracting person does any action, the /drag_out command is interrupted

Additionally, expand this command to allow PD/EMS/FD to pull non-downed people out of turtled or disabled vehicles.  

### Reason

This will provide several benefits

- The act of pulling a downed person out of a locked car would be more realistic
- It would add to PD RP by realistically being able to forcibly remove a person from a car.
- It would add to EMS/FD RP by making extraction from a damaged vehicle more realistic
- It would reduce the viability of the "keep the doors locked on my turtled car until my friends arrive to hit me" tactic without eliminating it altogether.

**Comment by twooot** [comment]
> if the vehicle is locked

When you go down now, the vehicle unlocks automatically to prevent abuse, so this solves that problem since the vehicle would never be locked when someone is down inside of it. Also, "animations already exist in GTA" those animations aren't animations you can just play or decide what animations should be played when dragging people out of cars. It's simply not possible and for such a small thing i don't want to spend hours searching for a solution that probably doesn't exist just so you play a different animation in .1% of the cases.

> Add an interruptible 3-5 second timer to allow the animations to play and keep it from being abused.

Have you actually tried this out? You can already press X to cancel dragging someone out. If you however are already mid dragging out you cannot cancel and wont be able to.

> Additionally, expand this command to allow PD/EMS/FD to pull non-downed people out of turtled or disabled vehicles.

Detecting if a vehicle is turtled or not is already ass. Also i believe it would be a bit too OP for PD to be able to do it. They can use tasers or simply **tell** the person to get out (RP, yes). And if they are downed use /drag_out???
