### ISSUE TITLE
Suggestion - Nerf Repair Kits

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2580]
### Assurance

I have read the `README.md`

### Summary

Change all repair kits to be single use only
Reduce the weight of basic kits from 10 to 2
Reduce the weight of advanced kits from 20 to 5

### Reason

Currently an advanced kit will repair your car for over 50% of damage, multiple times, for only ~$600.  

For the same amount of repair at a mechanic shop it would cost more. PER REPAIR. This makes going to a mechanic shop, without hitting your car with a kit first, a terrible financial decision.  

This makes repair shops SIGNIFICANTLY less useful, and mostly useless to those that don't care what their car looks like.

Making kits single use only, especially with how common they are now, will correct the HUGE cost imbalance vs. mechanic repair and incentivize people to own, operate and visit repair shops while still providing a reasonably priced option to get back on the road when one isn't available.

PD "could" sell PD versions of kits if it becomes a cost issue for them.

**Comment by CloudTheWolf** [comment]
Agreed,
Potentially also introduce a new repair kit called "Puncture Repair Kit" that can be used 4 times but will _only_ repair the tyres (For like $100, so $20 more than a mechanic to do all 4 tyres)

Or alternatively make them similar to the vapes where they buy them at mechanic shops for like 200 and can then "Recharge" them for 100.

I see no issue from a PD Perspective since as far as I can tell 90% of repair kit usage is putting out fires. with the last 10% being to repair tyres.

Basic repair kits are _extremely_ common from the trucking job and mechanics sell advanced kits for $550 so it's not like it's overly expensive to by 2 - 3 kits in one go

**Comment by twooot** [comment]
i dont like the idea of them being single use but i'm down to buff the chance of it breaking on use

**Comment by twooot** [comment]
done
