### ISSUE TITLE
Suggestion - Mechanic Job improvements

### ISSUE THREAD

**Issue by xplrerin** [InZidiuZ/op-framework-issue-tracker#2589]
### Assurance

I have read the `README.md`

### Summary

I have a multitude of suggestions regarding the mechanic shops/job, might not be problems for other people but these are suggestions I feel would benefit all shops and make the mechanic job a lot more appealing due to the current decrease of mechanics around the city due to the nature of the job.

First suggestion I have would be to introduce a on duty/off duty system _similar_ to PD and EMS to reduce the amount of mechanic/tow texts we receive. As it currently stands, you could be off the clock and doing other activities and receive continuous spam messages from people wanting mechanics. I understand it comes with the nature of the job but it can be very irritating and personally I've heard of people resigning due to it. Alternatively, if we could opt out of receiving texts it would be better too.

Second suggestion would be to allow us to make multiple windows or doors at the one time. I feel that if you have 3 pieces of glass in your pockets you should be able to put all windows in at the same time rather than the constant back and forth from the work bench. If you have 7 missing windows and the shop is hectic, it can be very time consuming which usually results in customers opting out of receiving windows. I also find that computer pricing can be very expensive considering it is difficult to find Steel as it once was. Considering there is multiple uses for materials now and nothing ever changed with pricing.

And my last suggestion is up for further suggestions to the job as a whole. Mechanics are a necessity to the city in order for people's vehicles to be operable, with advanced and basic repair kits doing barely anything to repair a vehicle now, you'd think it would push more people to want to work the job, but it seems to not be a very big money maker as it once was. It would be nice to have other aspects to the mechanic job - a delivery job as such on the side if you could deliver parts to local custom and repair shops for some extra cash that would also bring people in. Or if towing was making a little bit more money on the side rather than the reduction of price if a person flies out.   

### Reason

Again, These are suggestions.. People are allowed their own opinions on the mechanic job but I do find that people are always looking for mechanics in the city at all hours - Shops are struggling to find people that want to work away from Burger Shot, Bean Machine, Arcade etc.. Simply due to the money making aspect. 

 THANKS FOR READING.

**Comment by Mugdha57** [comment]
totally agreed with the mec/tow text part. its so irritating text after text in mnts -_-

**Comment by coalaura** [comment]
> on duty/off duty system

sure thing

> local deliveries

no

**Comment by CloudTheWolf** [comment]
With regards to to On/Off Duty system it would be nice to be able to turn that off whilst working as a mechanic (Eg if I'm up at Harmony running the shop, I don't want to get requests for tow all the way down in the city)

As for the second suggestion I have always said Mechanics should be able to make Doors, Windows and Tyres as Items rather than only when needed, and maybe even allow for more advanced crafting (Craft Door, Hood etc)

This would be something that could extremely enhance Tow RP as they could make a load of Tyres before hand then do "Road Side Assistance" to replace blown tyres. (As in my eyes, if your tyre is completely gone, no amount of repair kits should fix that)

Finally for local deliveries I agree with Laura that this shouldn't be a thing as Scuba and the Warehouses are already the equivalent of that and are not tied to any job.

**Comment by coalaura** [comment]
ok you can now do "/toggle_mechanic_messages" to toggle off and on if you receive tow texts. Making multiple windows/doors at a time makes no real sense since you wouldn't just magically repair all windows of a vehicle in like 3 seconds. The rest is very similar to the other mechanic/tow enhancement suggestions so i'm gonna close this issue
