### ISSUE TITLE
Suggestion - 

### ISSUE THREAD

**Issue by RebirthWS** [InZidiuZ/op-framework-issue-tracker#2594]
### Assurance

I have read the `README.md`

### Summary

Boosting the new gun computer drop rates for one handers (pistols, hand held autos, etc.) 

### Reason

With the new and improved gun computer and there only being one gun comupter the server has seen some changes with it. While the process itself has improved imo, with the On Duty counter being added making it less runnable within a day (no problem with that) I feel as if the drop rates for one handers are quite low. I've done around 49 successful gun runs since the change and only 14 have been one handers. Whilst the computer is to be held by one gun individually I believe boosting the drop rates for most one handers and leaving some like the SNS MK2 the same would be beneficial for the gun economy of the server. Below is a list of the one handers we received during our gun runs.  
1 Skorpion
2 Tec9
2 Beretta
1 Pistol MK2
3 Cermaic Pistol
4 SNS Pistol MK2s
! Heavy Pistol

**Comment by TalosTG** [comment]
Agreed, one handers are a necessity for effective conflict RP and protection. While it may seem at first that low one hander rates will decrease car fighting the truth is much like when cars exploded those who have the more effective tools will force it. This will lead to extremely demoralizing gang wars, and shootouts in general as gangs that are hoarding, and or purchasing first will have far more power than those unable to get their hands on these weapons. 

It is extremely important for majority of established groups to have an avenue to get these weapons in order to protect themselves against others, without throwing into a war (i.e running the computer themselves)
