### ISSUE TITLE
Suggestion - Reduce/Remove Cash Drops from Zombie Pill Rewards 

### ISSUE THREAD

**Issue by kaycorriher** [InZidiuZ/op-framework-issue-tracker#2605]
### Assurance

I have read the `README.md`

### Summary

The current meta is using Zombie Pills to generate your cash flow to buy cars, guns, etc. I have heard most people can make 2-3x the cost of a Zombie Pill during the 8-10 minutes of the pill. By reducing or removing the cash drops from the Zombie Pills there would be more item drops therefore people would have to go RP selling oxygen tanks, lock picks, repair kits, etc. to make money versus immediate cash in pocket. 

### Reason

This is a Role Play city and most people are spending time most of their time in the "Zombie World" and not role playing to get money therefore ruining the economy. 

Ex. Some people are buying 100 Zombie Pills a day and walking away with anywhere from $200K-250K in profits.

**Comment by Puucko4090** [comment]
So i see it like this the monies gained from them arent the issue its the time ppl are spending doing them that creates the to mutch money issue.I suggest slap a cap on how many u can do per day.That way arcade wount suffer a complet no buissnes because the zpills arent worth doing, it will be resonable, and ppl wount make stupid monnies.Then ppl like me can still buy my 100 pills and do a few here and there then go buy a new batch when im out <3

**Comment by coalaura** [comment]
this has been done
