### ISSUE TITLE
Suggestion - Replacement of some Z-Pill Items to improve economy.

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2606]
### Assurance

I have read the `README.md`

### Summary

Currently you can obtain items from Z-Pills that are otherwise only obtainable via Player Ran Businesses (For example food such as Burgers, Fries etc.)

This means someone can grind 1/2 Z-Pills and get a load of food that they share with their group that does not contribute to the city economy.

I'm not sure on all the items available via Z-Pills but would suggest the following changes:

All Food/Drink Items - Replace with Scrap, Steel, Aluminium, Rubber and Glass.
Joints - Replace with Weed (1q)
Adv Repair Kit - Replace with the items required to craft this item 

### Reason

1 - Replacing all Food/Drink items with materials for mechanics not only stops business being taken from Burgershot/Bean machine etc but also gives them something to sell to mechanics for money which they can then use at other businesses, which would boost the economy naturally.

2 - This stops taking business from Green Wonderland and instead gives people more reason to go there to get rolling papers to make joints.

3 - Similar to 2, this changes the way the end item is obtained by encouraging RP.

**Comment by ImArteria** [comment]
Actually with the food items thing, I think I had a pretty good idea. Instead of getting good food, make it fruits. At the moment moonshine is a "barely profit" type of deal. Reward people who roleplay and buy the pills, to create moonshine without the cost of fruits. 

In terms of food/drink I'd just make it low chance for water/tacos/fruits
I think making it mechanic parts wouldnt be too hot, I think attachment parts would be better because youll be able to make even MORE money if you could receive sellable parts.

**Comment by coalaura** [comment]
> All Food/Drink Items - Replace with Scrap, Steel, Aluminium, Rubber and Glass.

I see your point but your replacement idea would drastically improve the value of Z pills

> Adv Repair Kit - Replace with the items required to craft this item

Anyone is able to craft the advanced repair kit, you dont have to be a mechanic to do so

**Comment by coalaura** [comment]
I've replaced the high value foods with fruits now and adjusted some of the other drops
