### ISSUE TITLE
Suggestion - Coke buffs/Changes

### ISSUE THREAD

**Issue by ImArteria** [InZidiuZ/op-framework-issue-tracker#2611]
### Assurance

I have read the `README.md`

### Summary

- Coke process now keeps the $1000 input to get the free coke brick
- Increase the selling price slightly.
- Add a 2nd selling location (Laura if you look over this, me, you and Twentz discussed a possible 2nd location for it)

### Reason

With coke not coming in as prominently, I feel like people aren't selling it as much. Personally I feel like one "bag" of coke should sell for more, but to combat that the process itself isn't just a "free" process by making the keep the $1000 deposit . Possibly to further combat it, lower the timer slightly so it isn't all time based and people can get more out of when cops are on duty.

By adding a 2nd selling location, it would also increase the general locations to sell coke as well and further increase the PD/Crim RP interactions instead of just sitting at Vinewood. Most drugs have 2/3 selling places versus Coke just has one

**Comment by imdiavolo** [comment]
The $1000 being kept by the process will probably be negated by the new price of selling, As I'm assuming bricks will start selling for toward $3000 to adjust to their street value. 
Depending on the location of the second spot, it will either ONLY EVER SO slightly improve the current situation of the lack of selling, or do nothing at all.

I agree with you that coke is not being sold as much anymore but I don't think it has anything to do with the fact that it's limited to one area, Or at least that's not the only or even the major reason. The answer is much more simple : Not as much coke is being distributed to crims as it used to be due to the new minimum cop requirement that every process has now. Back when WSBloods ran the process aka before the change, we were easily pumping 90-100 bricks a week minimum via how we handled the process and the mandatory participation rule we had, that was pretty much enough to supply every gang with a good 15-30 bricks a week depending on their demand and group size. I'd like to think that when that was the case, coke sales were relatively decent regardless of it being a one street sale area. 
Now I know that your suggested answer to the process not being ran as much is to lower the timer on it but I don't think that will solve the issue. It's not that people don't get enough bricks per hour, it's that most of the time EU people are completely unable to run the process to begin with leaving hours and hours of downtime, which will never be negated by being able to do one extra brick or so an hour before you eventually have to go to sleep because you're a college student or have work in the morning. 

The notion I'm pushing for is very clear, The main issue with coke comes from the simple fact that there's a minimum requirement for it to be ran to begin with leading to less frequent selling of it. This issue will always exist for every process unless the gang running it is mainly an NA group which will always leave a bitter taste and a taste of unfairness for EU groups to why they can't have success doing something comparatively just because of their geo location. 

Your suggestion is overall a positive one, I know that the topic of the minimum cop count isn't necessarily the point of this suggestion but I felt like it was fair to point out as to give a more broad picture to the situation rather than equating it to one or two things. 
This suggestion being implemented as a first step before changing the minimum cop requirement is probably the way to go (?). As if it does make not only the generation of coke but also sales of coke go up while still maintaining the "cop rp" then I suppose that's the balance we aim for. Even if it doesn't it will still make a positive change in the long run as the limitation of one street actually becomes more dominant when the opposite is occurring of it being way too many people trying to sell to the same locals making it very frustrating to sell anything, cops showing up only becomes secondary at that point.

**Comment by coalaura** [comment]
> Coke process now keeps the $1000 input to get the free coke brick

no

> Increase the selling price slightly.

i wont comment further on this but something like this has already been done very recently

> Add a 2nd selling location (Laura if you look over this, me, you and Twentz discussed a possible 2nd location for it)

Most definitely a nice idea considering most other drugs have multiple selling locations

**Comment by coalaura** [comment]
done
