### ISSUE TITLE
Suggestion - Real Estate Offers

### ISSUE THREAD

**Issue by xplrerin** [InZidiuZ/op-framework-issue-tracker#2638]
### Assurance

I have read the `README.md`

### Summary

Real Estate has been hella outdated for a long time but I have some suggestions to make it slightly easier for new players to accept offers and work the system as a whole.

As it currently stands, Realtors can send an offer to a CID given to them and it will pop up as text similar to the pictures I attached.
![image](https://user-images.githubusercontent.com/77466954/212179134-0b17d031-4656-4409-96cb-1d04b35381ac.png)

The issue with this system is that new players really do struggle to accept it, especially if it as an apartment like most addresses such as Forum Drive 7 / Apt1 as an example. All offers have to be accepted by being case sensitive and the money has to be in their bank account in order for the transaction to go through.

_**My suggestion is to implement some kind of pop up that is as simple as Accept or Deny.**_
Having a button to click will not only be a lot easier for new players but a lot more immersive for Realtors. We spend a lot of time trying to explain to a newcomer how to accept the offer, and it peaks into ooc talk or having to send them the offer to copy/paste on a notepad/discord.

It would also be beneficial if the money to accept can be taken out of cash or bank rather than just bank as having to send people to an ATM is also very time consuming.

### Reason

Real Estate is very outdated and there is more suggestions I would love to have such as evict buttons, edit buttons etc. But if we can have offers accepted a lot easier - It's a step in the right direction for new players to be welcomed into the city with more immersive RP. The timer on the offer makes it stressful if they're slow typers or just misreading, then Realtors have to spam the offer to them which again, is very displeasing to the eyes.

I'm up to hear other suggestions and opinions from other realtors in regards to the accepting offers process but I just feel this will be so helpful and speed the process up for Realtors.

**Comment by vol5** [comment]
> My suggestion is to implement some kind of pop up that is as simple as Accept or Deny.

This would be a massive QOL change that all realtors would love. Whether it be a single /accept for the recipient or a popup.. Either would do.

**Comment by ImArteria** [comment]
I made a github pretty much rewriting all of the real estate script, idk how devs feel ab that but tis here since seems somewhat relevant in terms of real estate updates
https://github.com/InZidiuZ/op-framework-issue-tracker/issues/2172

**Comment by xplrerin** [comment]
Rewriting the script would be cool - But imo shouldn't be done in the middle of the current system in case it affects current tenants. Would be something implemented with a wipe maybe?
The small changes like my initial suggestion can help better the current system and make it a lot easier.

**Comment by Masik52** [comment]
When accepting the offer you could have it sent to their tablet and have a button to push to accept in the purchases area. All realtors would have to explain is how to pull that tablet up which is not difficult. 

Eliminating the need to use the account tab to store rent money would also be a nice QOL change. Clicking pay rent and just having money pulled from their bank account would be nice. 

Having the ability for company employees to sell a house would also be a huge win. We are typically limited in the total amount of companies that are approved to be real estate companies due to multiple factors. This would allow for more people to be involved with real estate without having to add more base companies. Since there is no evict or contract editing give owners the ability to set a price range their employees can sell the house for.

**Comment by coalaura** [comment]
You still have to explicitly type "yes" to confirm after the /accept so you don't accidentally accept things you may not want to.

![yes](https://i.shrt.day/MQFQJTNCN6.png)
