### ISSUE TITLE
Suggestion - Locals Reporting Unsafe Driving 

### ISSUE THREAD

**Issue by FastestLapp** [InZidiuZ/op-framework-issue-tracker#2678]
### Assurance

I have read the `README.md`

### Summary

A system in which locals in the city would call in the PD and report "reckless/dangerous" driving based on a percentage model based on speed of said vehicle. 

### Reason

So I have been spending a ton of time in city lately and thought of this idea in where the following scenario takes place:

- Crim robs J Store/ Bank / Convenience Store
- Chase Resumes
- PD Loses visual
- Chase Over

In my idea I believe that the locals should be able to report "reckless/dangerous" driving. For example in that same scenario, the crims get away and I feel realistically, if i was a local and saw a dude fly by me at 140+ mph, someone may feel the need to call the police and report the make and model of the vehicle with color as well and maybe even the plate. 

I fell like a good way of implementing this is with a probability ratio so for example, for "x" speed, the locals have an "x" percentage of calling the cops. So for example, the crims get away but continue going 160+ mph the likely hood of a local calling in and saying "xyz vehicle driving dangerously" would help the Cops resume chase. Keep in mind that my role in city is neither police OR crim, its just that i haven't had any ideas for Crim yet. Also, like IRL, not everyone that sees someone speeding calls the cops so it might be best to assign another percentage variable so maybe something along the lines of:

Car Traveling at "x" miles, lets say for the sake of this example (160+ mph), at 160+ mph the likely hood of someone calling PD might be 80%, but out of all locals a RNG of 1-100 likelihood of actual local reporting it to the police. So in this example lets assume RNG is 26%, so the chances of local reporting the crim to the police with last location seen and vehicle description is  20.8%.  And then of course any final chance >50.0% would result in local reporting said driver to PD.

**Comment by FastestLapp** [comment]
And then of course any final chance >50.0% would result in local reporting said driver to PD.

**Comment by enutpeanut** [comment]
I really like the idea but I feel like it would clog up the dispatch, especially during a chase.

**Comment by coalaura** [comment]
I don't think this is a good idea. The majority of the playerbase, including "legal" characters speed like mad through the city. This would clog up the PD dispatch unneccessarily and would also be completely useless for PD since by the time they have responded to the local call the person who sped past would already be on the other side of the city.
Also i don't think the difficulty increase for robberies is needed if you want to argue that point. All the robberies are balanced with the RP of "negotiation -> chase -> arrest or getaway" in mind. It is already somewhat difficult to get away from PD with the tools they have and you need to be a decent driver to manage it.
