### ISSUE TITLE
Suggestion - Add a config option to set local burgershot/Bean Machine delivery limit

### ISSUE THREAD

**Issue by Mugdha57** [InZidiuZ/op-framework-issue-tracker#2680]
### Assurance

I have read the `README.md`

### Summary

Add a config option so that server managers can set a limit of daily local npc delivery limit for burgershot/bean machine delivery

### Reason

we have seen in subdivision some player are just gaining money from npc delivery, they are not interacting with other people. they are not doing any other activity just grinding this npc delivery and making millions. so imo there should be a daily limit for this.

**Comment by coalaura** [comment]
Then you should fire those people imo. Idk if there should be a hard limit to how many you can do

**Comment by scufflord** [comment]
This comes down to an issue that could be handled in roleplay imo. I work at burger shot on the international server and honestly the money isn't that good. I barely do local deliveries because things like zombie pills, mining, and hunting egvery day already give such a large chunk of cash. I only really do them out of boredom or because I have already done everything I can do for the day.

**Comment by Mugdha57** [comment]
Thanks. closing the thread
