### ISSUE TITLE
Suggestion - Further reduce the payouts for mining

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2771]
### Assurance

I have read the `README.md`

### Summary

We all LOVE the mining mechanic, but the strength of it is almost universally considered OP from a money making perspective. (Posting this to collect comments/agreement/disagreement)

One or more of the following:
- Reduce the selling values of all gems by >50%.
- Reduce the drop rate by >50%
- Lower the Daily Sell Limit to $7500
- Dramatically increase the time to mine each gem

### Reason

The time-sink/risk/reward for mining is **significantly** stronger than other activities in the city.  Even Crime, literally, doesn't pay.

- Mining can give you $15k/day easily, where as a job will give each person less money, require them to get away and cost them money and time if they fail.
- The daily cap is only marginally effective as there is no degradation on the gems.  People can simply horde them and sell them the next day.
- Many people are satisfied with their daily income with mining alone and simply have no reason to pursue other activities in the city.
- It takes people away from the city and collects them all, stationary, in the backyard of a random house in a small town for extended periods due to the large numbers of gems that drop

The alternative to decreasing the payout of this activity is to increase the payouts from crime and inflate prices of cars/goods in the city to compensate.

**Comment by coalaura** [comment]
With your suggested change **__nobody__** will be mining. I can drop the payout by a tiny bit but its already where its supposed to be

**Comment by coalaura** [comment]
I'm very much against your suggested changes, however i do see your point and yes mining is a bit overused. I prefer doing multiple smaller balancing changes to approach a good end state rather than doing one big one and most likely overshooting and discouraging players from doing the activity.

I've done a few balancing changes to mining now, nerfing it. Not as strong as you suggested, but still significant. I'd keep an eye on it for the next few weeks and see how it develops

**Comment by MetaHatter** [comment]
Sounds good... like I said above... "One or more of the following:" just as suggestions of some things that COULD be done.

Thanks.
