### ISSUE TITLE
Suggestion - place downed person in heli and boats

### ISSUE THREAD

**Issue by sakar5157** [InZidiuZ/op-framework-issue-tracker#2838]
### Assurance

I have read the `README.md`

### Summary

it would be better to have this. if we can put someone in car seat, why not in others?

### Reason

its imposisble to rescue someone who is down under water.

**Comment by King2704** [comment]
yes please

**Comment by coalaura** [comment]
I feel like this would take away more of the EMS / Fire dep. roleplay, no?

**Comment by King2704** [comment]
Idk why he closed the GitHub without replying to your question but I can tell you what I think about it.
Just having the option to put people in a Helicopter would make things easier since at the current state of EMS there's not always someone around. And if there is EMS around they might not have the necessary certifications to operate the helicopter. With mining on Cayo, there's now a relatively easy way to blow up on an Island surrounded by water so if your friend picks you up they have to swim over to the shoreline to put you then in a car. This could be a lot easier by just putting the downed person in a heli since ems also gets tired of flying to Cayo 3 times every day.
There's a rule about calling ems if they are available on the International server too so if people were to abuse that feature too much staff could start reinforcing that rule more.
Lmk what you think about those points

**Comment by King2704** [comment]
any updates on this?

**Comment by coalaura** [comment]
done

**Comment by coalaura** [comment]
same for boats
