### ISSUE TITLE
Suggestion - Gas Station

### ISSUE THREAD

**Issue by PurpleHzea** [InZidiuZ/op-framework-issue-tracker#2952]
### Assurance

I have read the `README.md`

### Summary

This suggestion is about the implementation of owning gas stations to the server and how I believe it should work.

The gas station owner would have to source a barrel of Crude Oil then refine it into gasoline.
The owner then would take the barrel full of gas and fill up either at each pump or using these 
(Would need to be added at each station if used)
https://cdn.discordapp.com/attachments/1148394687552553020/1148421767245860874/image.png

An empty barrel would be able to be purchased by anybody at a store within the city. Here are a few potential store front locations.
[Location] https://cdn.discordapp.com/attachments/1148394687552553020/1148416309986607266/image.png
[Location on map] https://cdn.discordapp.com/attachments/1148394687552553020/1148416378039177267/image.png
[Location] https://cdn.discordapp.com/attachments/1148394687552553020/1148402004314574909/image.png
[Location on map] https://cdn.discordapp.com/attachments/1148394687552553020/1148402294380036146/image.png

After buying a barrel the player would be forced into walk style ARMORED and will also be forced into this emote
https://cdn.discordapp.com/attachments/1148394687552553020/1148401596200386720/image.png
but with a barrel prop instead
https://cdn.discordapp.com/attachments/1148394687552553020/1148403664608829521/image.png
The barrel would in the players hand until dropped/stored
An empty barrel would weigh about 100 LBS 
A full barrel would weigh about 150 to 200 LBS

Filling an empty barrel with Crude Oil 

The barrel would be taken to any oil rig scattered around the map 
Example:
https://cdn.discordapp.com/attachments/1148394687552553020/1148402673192804412/image.png
https://cdn.discordapp.com/attachments/1148394687552553020/1148411657782038609/image.png
Then would require 1x empty barrel and 1x pipe wrench 
Emote mechanic2, 3, or 4 would play and would take 30 seconds to 1 minute 30 seconds to fully fill up the barrel.

Refining crude oil into gasoline

After a barrel is filled with crude oil the barrel would be taken to a refinery location to be refined into gasoline.
Potential refinery location
https://cdn.discordapp.com/attachments/1148394687552553020/1148425130859569233/image.png
In front of the big GLOBE OIL tanker with the addition of these pipes aswell.
https://cdn.discordapp.com/attachments/1148394687552553020/1148421767245860874/image.png
This would require 1x Full Barrel and 1x pipe wrench and would also take about 30 seconds to 1 minute 30 seconds

After a barrel is filled with gasoline it will be brought to a gas station and deposited into either the pumps themselves or into these pumps that would need to be added at each station.
https://cdn.discordapp.com/attachments/1148394687552553020/1148421767245860874/image.png

Business side of things:

Every time gas is pumped from a gas station the money will go into the owners company account or separate bank account like the tuner shop and governor has. 

Each station would also have paychecks
Owner: $75
Manager: $50
Fuel Driver: $40
Gas Jockey: $30
Janitor: $25

### Reason

I believe the ability to own a gas station will provide more jobs and opportunities for legal individuals that want to own a business other than a mechanic shop or bar. Also more jobs in general for everyone. It would also create a more tame type of roleplay apart from the constant robberies and shooting etc.

**Comment by JennyLynn001** [comment]
I think this would be a great idea and asset for the server. It would bring more interactions and RP. It would also be cool to see the gas stations being put to use other than being robbed and pumping your own gas. I have not seen any other server do this, I think it would attract more people due to it's uniqueness. I really would like to see this happen!

**Comment by Scorch149** [comment]
This would def give gas stations an actual use and also put RP into actually having gasoline and maybe even diesel for the bigger vehicles and puts a need for gas stations to NEED to be refilled and stocked up so they dont go dry

**Comment by Pizzzaa** [comment]
This would be awesome!

**Comment by CloudTheWolf** [comment]
As cool as this sounds I would be hard to implement, especially when it comes to who owns which gas station etc.

**Comment by coalaura** [comment]
I am with Cloud on this one, i feel like its a cool idea in theory but i don't see it working out in rp

**Comment by PurpleHzea** [comment]
What's the main issue with implementing this idea? The amount of time someone would have to put into it within RP, or the mechanics within the server?

I can try to rework some things to make this work but I'd have to know which parts I've got to work on

**Comment by CloudTheWolf** [comment]
> What's the main issue with implementing this idea? The amount of time someone would have to put into it within RP, or the mechanics within the server?
> 
> I can try to rework some things to make this work but I'd have to know which parts I've got to work on

So here's the issue I see (At least from a game mechanic side, rather than RP)

Let's use Burger Shot, PDM and Mechanic Shops as a comparison 

Gas Stations would fall under the same type of business as Mechanic Shops where there are multiple locations, all "Owned" by different people. So this would make the whole "Pay into Business Account" thing a bit hard. Where as Burger Shot and PDM are both 1 location so their would only be 1 owner.

Saying that I feel this _could_ be split into multiple things

1 - Refilling Gas Stations: This could be added as an extension to the Trucking job, After a player does a certain amount trucking they can pay to unlock new cargo types (Heavy Goods, Hazardous etc) which each have their own "Special" requirement.

Refilling gas stations come under "Hazardous" and would start and end at the Oil Fields, where they get the tanker, take to a gas station to "Unload" then return the empty tanker to get paid (And a chance to obtain Crude Oil legally).

2 - Crafting: The Crude Oil could then be used as an ingredient to make Red Diesel (Criminal Activity) or be sold to mechanic shops (Crafting item to make Oil Kits?)

**Comment by JennyLynn001** [comment]
I don't see how this would be an issue RP side of things. I think it would promote good RP, and people would have to interact and actually do something rather than talking to a "door. " or the typical doing things themselves.

The trucking job idea isn't bad. I understand where you are coming from. However, that doesn't give any RP to the city. It's just another way for people to just grind... which I'd like to see change by people actually being able to do something within the city that makes people have to interact with others... 

Take my business, for example, Hidden Gems, I wanted my own shop to be able to make rings, break them down and sell them, bears, roses etc... but I was shot down the idea, and instead just anyone can do it themselves... instead of giving people the chance to make interactions, they now just do it themselves, which has put my business to a hault sadly.. people would rather talk to doors than interact RP side of things...

I don't know. His idea to me seems like a great opportunity to help RP grow within the city. As for the paying side of things and bank accounts i think it could work if thought out and balanced and of course that stuff takes time.

**Comment by coalaura** [comment]
Yeah after thinking about this i don't think this will work
