### ISSUE TITLE
Multiple Bank accounts / Multiple player bank accounts

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#2959]
### Assurance

I have read the `README.md`

### Summary

We would love mutiple player bank accounts where set players can be added and can deposit and withdraw money 

### Reason

My shop would love it and others in city I’ve asked about it said they would use it also

**Comment by ayushpatel1007** [comment]
yes , i think this would be great addition in rp.

Gang Members always have trouble in maintaining funds and keeping records on that. A Group bank account will allow people to Deposite or withdraw the money in group account. 

Permission:
We can have permission level like we have in sharing house key.
level 1: only view bank balance and statements
level 2: View balance and can deposite money
level 3: Withdraw/deposite money and view statement
or we can just selected permission for every players CID.

Statements:
Statements are most important in group account because who added money , how much and when can play important role here. because if a family/gang is using group account and they have to see who really paid gang fund and who didnt then they can check it using statement.

if statement is not introduced with group bank account then it will be useless, because all the efforts that we are doing now, will have to be done also after getting group account. 


Other Uses:
This group bank account is not only for gang members but is for friends who stay in same mansion and split their weekly rent.
this is also for those business that have to take commisions from their employees every week. Group bank account can be used in many others ways.

From where / How to use?
We can simply use by using /comp or /companies and this tablet can have one more section for group bank accounts

**Comment by CloudTheWolf** [comment]
+1 for this.

Currently Gangs / Businesses basically rely on a single person, and if they get banned, or just vanish from the server for any reason, then it can ruin the RP experience for others.

**Comment by coalaura** [comment]
We now have savings accounts that are available via the /savings command

**Comment by coalaura** [comment]
These are savings accounts tho, so while you can give people access to deposit/withdraw you cannot transfer money directly from savings account -> savings account.

![list](https://i.shrt.day/KZE3NXAA87.png)
![account](https://i.shrt.day/L92RUJYZ1Z.png)
![manage](https://i.shrt.day/1SDHLNE9SX.png)

**Comment by King2704** [comment]
whats the interest rate on the saving accounts?

**Comment by coalaura** [comment]
> whats the interest rate on the saving accounts?

There is none rn, maaay add a little in the future MAYBE but thats for the future. For now these are mainly there to allow people to share funds with others. Like gang funds, etc. for example

**Comment by coalaura** [comment]
To avoid most abuse you can also only deposit/withdraw from/to your bank account

**Comment by ayushpatel1007** [comment]
Can we have options on the access type? 

Like access of only withdraw or Deposite or both. 

Because if we see this account being used in gang/family to collect funds, any gang member can betray whole gang by just withdrawing all the gang funds from the accounts.

Maybe than gang owner would think of directly collecting of funds using /bill rather than making his all funds available to like 10-20 people who can withdraw it anytime
