### ISSUE TITLE
Suggestion - PD buff (Battering Ram)

### ISSUE THREAD

**Issue by ImArteria** [InZidiuZ/op-framework-issue-tracker#2970]
### Assurance

I have read the `README.md`

### Summary

Hello, us as PD have been nerfed pretty bad. Battering ram timer is like, 15+ minutes before uses. Can we make this like 5 or so. I dont mind waiting between uses but we lowkey just afking out front of houses. 

### Reason

https://cdn.discordapp.com/attachments/907384115811213383/1158883608841441340/image.png?ex=651dddf7&is=651c8c77&hm=e4826d6131e1f9d98642a397214e68b41f803502eacb729486b14bb452917fd7&

I agree there should be a chance to intervene but I think it's been about 15 mins between uses. 5-7 would be a good number I'd say. Pls ty <3 FIB Buff PD Buff No Essay tag

**Comment by coalaura** [comment]
#2570 Nerf+Buff cancels out right? So i can just close this?

**Comment by ImArteria** [comment]
> #2570 Nerf+Buff cancels out right? So i can just close this?
I already closed it so therefore X does not equal Nerf + Buff therefore leaving X = Buff therefore stating PD Buff.

**Comment by Masik52** [comment]
Most houses aside from like a motel, trailer or small apartment are going to require a couple trips in and out of the place due to the weight of some items.  if it's truly a 15 minute timer between uses you're spending a good amount server mechanic resources (pd) from responding to other crimes in the city while they stand around waiting on a timer.  I know we've waited a while in the past and there seemed to be a bug that only a relog would fix the issue of being able to use the battering ram again.  personally I think a 3 minute cooldown would be sufficient between uses as your typical raid for a search warrant is going to have first use being bringing in a clearing team to sweep the house for any suspects.  Then you start to bring in the people who are there solely for evidence collection after that.

**Comment by coalaura** [comment]
I've rewritten the battering ram functionality. It should now work and give anyone within 3 meters of the person using it access level 3 (max) to the property for 20 minutes. I've also removed the cooldown.
