### ISSUE TITLE
Suggestion - Stockade Robbery Reduce spawn frequency and increase required number of PD 

### ISSUE THREAD

**Issue by Masik52** [InZidiuZ/op-framework-issue-tracker#2981]
### Assurance

I have read the `README.md`

### Summary

My suggestion is that stockades need to be included in the cooldown system with Bank, Jewelry and Store robberies.  As it stands now, we regularly have multiple stockades hit at once or right after we arrive to a scene of one of the aforementioned robberies thus leading to many of them not being responded to.  Additionally with the state of damage disparity between Crim guns and PD guns the amount of PD needed on duty to be able to even hit a stockade should be increased from what it is at.  At least from the international server side of things whenever these are hit, they're taken to locations that are one way in kill boxes.  It makes zero sense for PD to even respond to these when we have 5 officers on duty who are going to be outnumbered and out gunned right off the start.  The only advantage PD has when dealing with shootouts is numbers and a zerg style push.  1 v 1 a crim should never lose to PD when a rifle is involved due to the damage disparity. 

### Reason

These changes would allow PD to actually respond to the calls and not essentially give out a free 30-40k or whatever the trucks pay out now.

**Comment by joevapes3** [comment]
I was would say 8-10 cops at minimum for bank trucks to be hit, crims ALWAYS go for a full stack 6 man and we have been just skipping them cause we only have 4-6 officers on duty and there isn't anything we can do. We've let go probably 4-5 over the last two days alone with 0 PD contest due to low numbers and them being hit during other robberies IE J store or Bank cause they seem to only happen when those are being hit as well.

**Comment by Skai97** [comment]
Fully agree however from a crims perspective bank trucks are shit. They only get taken because we know that they will almost always lead to a shootout or it's free money. 6 crims take 100k+ worth of stuff but you get roughly 14-20k from each of these. 

The rarer items such as maps and the keys for cargo maybe but the risk isn't worth the reward 90% of the time. 

People wait till they see chases etc going on because they know they might be able to sneak it

**Comment by MetaHatter** [comment]
I agree with the 8-10 cop on duty minimum.  Especially since multiple spawn at the same time... often...

Ideally, so crims can have a reason to hit them, we could manually spawn a custom version of the stockade so the spawn numbers/timings could be controlled and the payouts increased significantly.  I'm guessing that might be pretty difficult though.

**Comment by coalaura** [comment]
I've nerfed the bank truck a little, upped the required amount of police to 6 and added a 20 minute cooldown (starting from when the stockade is deleted/impounded)

**Comment by Skai97** [comment]
I know this was closed but this really doesn't fix the issue at all. 

1. Nerfing the bank truck makes the risk to reward even less for criminals as these when taken are shoot on sight pretty much.

2. The loot inside of them was already mediocre and they only get taken most of the time as they guarantee a shoot out with PD. 

3. 6 cops is definitely not enough as they already get ignored whenever there is 8-10 on duty as 6 criminals can easily shoot down 8-10 cops.

This change doesn't fix the issue at all. 6 cops on duty people aren't even gonna respond when they see 6 criminals on a roof top with ARs

**Comment by coalaura** [comment]
@Skai97 

I nerfed the payout only a little, this is to discourage crims a little from doing them all the time as quickly after another as they can, They shouldn't be as common and thats because their loot is better than a bank even. 6 cops is the MIMINUM that have to be on duty and not in training for them to be allowed to spawn. Since we rely on GTA's native spawning, that means once there is AT LEAST 6 cops the stockade has A CHANCE to spawn. I also balanced a bunch of different weapons in the same update.

These are a lot of rather bigger balancing changes. Big changes have big impacts, therefore i don't instantly jump from 4 cops to 10 but rather 6, leave it for a week or 2 and then re-evaluate. I believe that the changes i did (in my original response i only summarized the main ones), will do what i want them to do or at least move in the right direction. IF it is STILL an issue once these changes had a chance to establish, its as simple as changing a 6 to an 8 in the code.

**Comment by MetaHatter** [comment]
100% need to test it before judging... 

Only concern I have is for the groups that use them as shooter bait and could care less about the loot.  I'd propose a big payout buff and nerfing the hit times a LOT. (like 4-5 max per day).  That way it's not a shootout every hour and there's a reason for more pure robbers to bother with them (risk/reward) without butchering the economy.
