### ISSUE TITLE
Suggestion - Midnight Improvements

### ISSUE THREAD

**Issue by CloudCait** [InZidiuZ/op-framework-issue-tracker#2987]
### Assurance

I have read the `README.md`

### Summary

With both the addition to being able to resell EDM & Special Import cars and the increase in ticket pricing Midnight's business has been a lot slower than it was before. Less people are buying cars from here and less people are wanting performance upgrades as they're buying pre-owned vehicles that are already fully upgraded. I want to suggest some things to help the business run better for my employees so they aren't just stood around waiting for that inevitable 'any midnight?' tweet or for someone to walk through the door. 

### Reason

My first suggestion would be to add local deliveries to the business. I know this is primarily used for food businesses however I think it would be a great way to give employees something else to work for as the demand for car upgrades has heavily decreased. It would be similar to food deliveries however they would be delivering car parts, spray paints, wraps, tires e.t.c to mechanic shops/car garages/scrapyards around the city (not just mech shops that are owned/whitelisted as there are some small ones dotted around that aren't functional).

My second suggestion (this is potentially an asset addition so I'm happy to put this in a separate github in the assets section if you need me to) would be new car colours that are exclusive to Midnight. I've seen lots of servers have a wider variety of car colours than us such as lilacs, mint greens e.t.c. and I think it would be cool to spruce it up.

If anyone else has any suggestions please let me know!

**Comment by coalaura** [comment]
> local deliveries

no

> new car colours

car colors are not something we can change, they are given by the game. The only thing we COULD possibly do is limit the selection everywhere else (which i am not opposed to)

**Comment by CloudCait** [comment]
Okay well any other suggestions? Since reducing the EMS5 price and less people coming for upgrades the business is started to get cucked

And is there a reason why a no? Just want some feedback is all.

**Comment by coalaura** [comment]
No to local deliveries cause its a lazy RP avoiding way of making money. Like i said my other suggestion was to limit the normal ls customs in thing like respray options for example or something else other than respray, up to you as long as its reasonable.

**Comment by CloudCait** [comment]
most money making now is lazy rp but fair enough

could do it so people can only access metallic and matte colours in a ls customs whereas midnight has everything

could also have a midnight phone line so ppl dont need to tweet 'any midnight' and it helps staff who have twitter notifs muted

idk at this point cos theres significantly less rp at the business now cos everyone wants to buy a preowned fully upgraded car, and i dont think someone standing around inside a shop waiting for a customer to walk in is good rp either bc who in their right mind wants to fly in to stand around an empty shop for hours

**Comment by coalaura** [comment]
> most money making now is lazy rp but fair enough

I didn't really mean lazy more meant avoiding RP. Since when doing local deliveries the chance of you having to interact with someone is nonexistant.

> idk at this point cos theres significantly less rp at the business now cos everyone wants to buy a preowned fully upgraded car, and i dont think someone standing around inside a shop waiting for a customer to walk in is good rp either bc who in their right mind wants to fly in to stand around an empty shop for hours

I get that but deferring to ways that purposefully avoid any RP is not a good solution imo. That being said i don't have a good idea either...

> could do it so people can only access metallic and matte colours in a ls customs whereas midnight has everything

I like it! I'll come up with something

**Comment by TheOneLizard** [comment]
How about all top upgrades for Brakes, Engine Tunes, Transmission are only available at Midnight?

I feel that colours aren't as important for people to reach out to Midnight, but upgrades always are the centrepiece.

**Comment by coalaura** [comment]
I've now changed it so these things are midnight-only:
- All colors except Metallic and Matte
- Visual engine tunes like Engine Block, Cam Cover and Strut Brace
- All chassis options except Roll cage (Arch cover, aerials, roof scoops, etc.)
- All interior options (trim, ornaments, seats, steering wheels, etc.)

If this turns out to not improve customers we can talk about more or different things

**Comment by CloudCait** [comment]
Hi sorry I've been at work so only just been able to comment but I've also looked at other github suggestions and it's been mentioned before the possibility of test driving the midnight cars. Is that something that could be done because lots of new people come in expecting to be able to test drive them like at PDM

Also thank you for those changes I appreciate it

**Comment by coalaura** [comment]
> it's been mentioned before the possibility of test driving the midnight cars. Is that something that could be done because lots of new people come in expecting to be able to test drive them like at PDM

Yes, its on the TODO list https://github.com/InZidiuZ/op-framework-issue-tracker/issues/2376#issuecomment-1185617247

**Comment by vol5** [comment]
Points 2,3,4 are solid ideas. I like the idea of using a specialist shop for tuner style goods and find that reasonable.

One thing I'm not cool with is removing the players from being able to see all the options available unless they have the job. It's a bit aggressive and will discourage people since they wont even know other options exist. To me its worth leaving the options there and having a popup when trying to put them on the car "Sorry our mechanics aren't skilled enough" or "Sorry we don't have this part in stock". Could have this for ems 5 too so players know its a thing thus promoting the usage of midnight via RP because people will ask questions.

[Point 1]
I don't like the idea of vastly limiting base colors because midnight is a tuner shop. All the ls customs are a pay and spray and you should be able to do just that. This one aspect removes to much of player freedom and is more restrictive than I think is fair. For me this place is about adding new ideas not creating the problem to then sell the solution which I feel this ends up becoming.

Idea suggestions:
- Tuner chips adjustments save upon car storage. (Incentivizes people to get car tuned)
- Custom Rims/Tires only at Midnight
- Underglow and light colors only at Midnight

**Comment by CloudCait** [comment]
The first suggestion I don't understand why it would benefit Midnight since if someone is caught with a tuner chip whilst evading or racing etc they're charged with Possession of contraband in crime. I don't want that being pointed towards Midnight especially considering EMS 5 was illegal in the first place when the business first opened. 

Many new players don't know EMS5 exists until they talk to other people or see adverts about it on twitter. It's just gonna be a case of asking around to see. Won't it be the same case with lights and the tire rims if they're midnight exclusive? New players won't know they exist until they see people with them and talk about it? I don't mind what items are midnight exclusive and what isn't but this whole thing is just to create more ideas to make midnight better. We made EMS5 cheaper and added discounts on performance; now people are only buying fully upgraded used cars.

**Comment by MetaHatter** [comment]
Only caution I would have is basing decisions based on the current influx of cars for sale.  EDM cars are being sold for the first time and, due to that and other factors, at a much higher rate than will be the case 2-3 months from now.  

I personally feel too many options have now been moved to Midnight exclusive (EMS5 is already a HUGE deal) but am going to sit back and see how things go once the EDM sale madness calms to normal levels.

**Comment by Skai97** [comment]
I don't think the EDM sales will slow down, people trade if they can't sell and now we are in a rotation of EDM vehicles.

The only cars that will really be sold from EDM stock are the ones in high demand. 

PDM was already dead as fuck so if midnight took a hit from this, can't imagine how they're doing

**Comment by CloudTheWolf** [comment]
I personally don't see vehicle cosmetics really fitting with midnight as now means that if players can only join the server at times that Midnight is not open they are basically screwed if they want to re-paint their vehicles or do other customisation. (Also, can _every_ player ownable vehicle fit in there? (Including trucks etc)

Would it be better instead to lock some of the performance settings to Midnight to better fit the Tuner Shop?

Additionally maybe make it so they can permanently apply vehicle tuning to a vehicle rather than have to use a tuner chip each time?

Another thing would be also add a LS Customers either showing an item can be added to a vehicle but only at the tuner shop, or just a generic messaging saying Midnight has more customisation Options available.

**Comment by CloudCait** [comment]
That's the same with other businesses except food though, no? No mechs? You gotta make do, drive another car or pop a repair kit on. No arcade? You have to wait to get your z/arcade pills or see if anyone has any. No state? You have to wait. No EMS? Self transport and pay the extra money. No GW? Use a yoga mat, grow your own weed or just wait. As for the comment about when it isn't open, I've only ever seen no staff around during the day for EU (crackhead hours for NA). I fly in everyday at around 5pm BST and I see people clocked in until like 5am BST. I don't want to hire more people into a business where they'll be fighting over a singular EMS 5 because that's the only thing people are coming into midnight for before this change. Increasing the demand for the business is what's going to allow me to hire more people.

Yes tow trucks, semis and ambulances can fit in Midnight. I found when on my other character I struggled getting my tow truck into the smaller LS customs like the one in paleto or the one around the corner from Midnight.

As I mentioned earlier in response to vol5's comment, I still don't really understand why we'd tie tuner chips to a legal business. Yes some employees are good with them but I don't think it should be a service we sell especially since (correct me if i'm wrong) each tune is different per car so it would be a lot of tunes to have to log and train staff on. 

Yes Bill suggested showing the option in LS customs but not letting them be purchased, that would be a good idea.

**Comment by King2704** [comment]
As someone who also spent a lot of time in GTA online customizing cars its kinda of sad to see a lot of customizations being locked to midnight and I'm sure I'm not the only person that feels like that. Some people spend hours on just one car in ls customs and now you can't do that anymore. For the performance upgrades I can see them being midnight exclusive since its a tunershop but things like paint and different skirts should be purchasable at any ls customs. (keep in mind people still get a discount if they go to midnight for it). 
The whole tuner chip topic could be talked to Doj about making car tunes legal and I'm sure there's a couple people that don't mind figuring out tunes for each car.

**Comment by CloudCait** [comment]
Well if everyone hates the idea I suggested then please I'm all ears to other ideas to increase the demand for Midnight because I'm out of ideas at this point apart from making performance upgrades midnight exclusive (which defeats my point bc my point was people are buying cars that are already fully upgraded so therefore that only leaves cosmetics).

**Comment by CloudTheWolf** [comment]
My thoughts are it's supposed to be a tuner shop, but the only thing close to "Tuning" is EMS 5 on the engine, everything else is cosmetic. 
Maybe re-introduce the basic colours back to LS Customs at double the price, then things like metallic, and matte finish are tuner shop exclusive. Maybe also make Custom Headlight Colours and Neon Kits Midnight exclusive.

This way Resold cars would still have a reason to go to midnight over LS Customs (Especially for Gangs who would want to gang under glow etc) while someone who's just bought a new vehicle and just wants to change colour of the paint doesn't have to hope midnight it open

**Comment by Skai97** [comment]
Another suggestion could be removing the stupid crafting steps for NOS. No roleplay involved in spending 30 minutes crafting a bottle for it to be filled at midnight. 

Nos being a purchasable item for people that have the midnight job to then sell from there business. NOS has been around for almost 2 years and has 0 purpose.

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/QalohUVu96.png)

ive now added back the colors but grayed out and with a notice so people know there is more

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/fULupESO50.png)

I've also changed it so instead, whats limited is only:
- Respray colors except metallic and matte
- Neon colors except white
- Xenon colors except white
- Neon Layouts (except going back to stock)
- Bumpers

All of these however are still shown, just with a hint that they cannot be purchased there but rather somewhere else.

**Comment by CloudTheWolf** [comment]
I like that, shows what _is_ available, and encourages RP to find out for new players who don't know about midnight
