### ISSUE TITLE
Suggestion - Real Estate

### ISSUE THREAD

**Issue by CloudCait** [InZidiuZ/op-framework-issue-tracker#2988]
### Assurance

I have read the `README.md`

### Summary

Allow real estate owners to see all left over storage inside vacant homes.

### Reason

When real estate owners enter vacant homes in order the clear them out we only see belongings that were placed in 2000 storage boxes. I've had a lot of clients tell me that they've found a bunch of stuff in a house after I've cleared it out and sold it to them. I've tested this out by purchasing a home that was supposedly empty and placing down smaller boxes where i was met with lots of items that I wasn't able to see prior. I'm not sure if this happens with all properties however I've experienced it in the mansions.

This is an issue for numerous reasons:
1. When someone drops a house all the possessions legally belong to the real estate owner however we aren't able to see all of the possessions
2. In a Franklin's mansion, we're only able to see 4000 worth of storage whereas this interior is supposed to have 7500.
3. Same with Michael's and High-End, we're only able to see less storage than what the property has.
4. If someone dropped a house but realised they left something in there that they want me to retrieve, I'm not able to get that back if it was in a different storage box and it's difficult for me to explain that to them in city as it's a server mechanic
5. It allows new tenants to be able to obtain goods that they shouldn't be getting access to because of a server mechanic
6. If someone drops a home with lots of illegal items inside of the storage that I can see, I can hand these over to police and they're able to deal with that (take the items and write warrants etc) however if there's illegal items left in boxes I can't access it just means the next person has them.

**Comment by xplrerin** [comment]
This would be so beneficial for people who accidentally drop a property and then don’t want it back, but want their items. I’ve taken some amount of abuse, people accusing me of stealing etc just because we only see a portion of the max storage. 
The only way around this is if I resell the property to myself or the individual to retrieve their belongings but this means we have to wait 1 week for it to go overdue, and 1 week for it to fall off. Meaning we lose money too. If we could just evict after selling a property for this kind of thing it would solve a lot of problems.
I believe this happens because of the properties being pre furnished when we do /enter but if the storages had the max storage amount instead of a portion it would be a lot easier.

**Comment by coalaura** [comment]
You are now able to access storages using the /storage command  
![yes](https://i.shrt.day/zibeSemu67.png)

However this only works if:
- The property is no longer being rented
- You are an employee of the company that owns the property
- You are inside the property
