### ISSUE TITLE
Suggestion - More Realtor Suggestions

### ISSUE THREAD

**Issue by CloudCait** [InZidiuZ/op-framework-issue-tracker#3001]
### Assurance

I have read the `README.md`

### Summary

1. Realtors should be able to see garages 
2. Revert back to the system where the arrow will pop up on the door when you /locate

### Reason

1. The number 1 question I get asked when I'm trying to sell a house is 'where is the garage'. Being able to tell potential buyers where it is will make the sale go by smoothly so I don't have to be like 'uh well i don't know i cant see it blah blah blah'. I also didn't even know that one of my blocks had a bunch of houses without garages. Maybe this could appear when a realtor uses /locate on one of their properties? Or maybe this should be a thing everyone should be able to see when they /locate. 

2. I love the new /locate how it gives you suggestions as you type an address. However the old visual for /locate was really useful as it meant if I was in an apartment building I could see which door is the right one however now it's just a big white bubble around a house with no indication as to where the door is. It's not that big of a deal but yeah.

**Comment by ayushpatel1007** [comment]
Yeah I completely agree. I own real estate business in legacy india. And the new /locate is useful but only when we are little far from property. The old one , where we were able to see arrow was great think because in apartment building , arrow helps find which apartment is where and where is it’s door.

Garage think is most asked thing by customer. They always ask where will be the garage and as a company we only don’t know where is garage so it’s feels like what is difference between real estate owner and customer if both can use /block and know same thing.

**Comment by xplrerin** [comment]
These are both really helpful for realtors!! I do like the new /locate system especially when it comes up the properties now but the arrows at the door were super helpful to find their main door. The glove around the property is okay for houses but for apartments it isn’t beneficial.

**Comment by InZidiuZ** [comment]
This has now been changed so that you can see entrances, back entrances and garages clearly. [Here's a preview](https://inzidiuz.com/0lOPKT.mp4).

**Comment by CloudCait** [comment]
This looks great thank you!
