### ISSUE TITLE
Suggestion - Mechanic Locker Storage increase 

### ISSUE THREAD

**Issue by gadjinee** [InZidiuZ/op-framework-issue-tracker#3014]
### Assurance

I have read the `README.md`

### Summary

I see more and more mechanics with multiple Vans all around the city when on duty, that use the locker with materials but also additional vans to have some extra materials. Ether because of garages been a bit too far away or just for convenience. 
my suggestion if possible would be increasing the mechanic locker storage from 1000 to 2000

### Reason

Increasing mechanic storage would allow anyone who is on duty to have all / majority of materials in the locker 

that would prevent unnecessary usage of vans for storage and just used for transportation as well as visual aspect, not having all the weazel news vans around the shops

**Comment by coalaura** [comment]
I'm willing to attempt 1500 storage as a slight increase, but the issue is it affects all lockers. In addition to that, with the amount of materials some mechanics have i don't think the locker would ever be enough to hold them all. It was more intended as a temporary storage. So you'd put materials only in it at the start of your shift and then go through them over time

**Comment by gadjinee** [comment]
Yeah make sense, honestly even getting 1500 is a massive massive change and will definitely help in day to day of mechanic life 

Appreciate it
