### ISSUE TITLE
Suggestion - Judge Repo

### ISSUE THREAD

**Issue by ImArteria** [InZidiuZ/op-framework-issue-tracker#3053]
### Assurance

I have read the `README.md`

### Summary

Hello 

I have a suggestion from FIB/DOJ after some discussion about server health. What I wanted to suggest is a Judge Impound/repo essentially. 

Essentially the command would be /judge_repo (Plate) (Time)
This would work similarly to PD Impound just without a cap.  For this to take place, there would need to be ample investigation by FIB only, than approved by a judge and we are looking at a strike system before just yoinking vehicles. Only judges can do this so not every cop can. 

First Strike is loss of car for 7 days, wait the 7 days and release it from impound.
Second strike is 14 days. 
Third strike is permanent. At this point they have already been warned about that they may lose their car. (/judge_repo (plate) (0) for permanently. 

### Reason

It's a countermeasure to help put a balance and give criminals a perspective on what they can lose. The objective of this is to create a high risk/high reward.

Use an EDM car and have a high risk of a case being built on it to lose it
Use a local car with it being harder to lose PD but also don't lose much in terms of a vehicle. 

This is something Matt, myself, Devyn, Twentz, Brun, and Petroski discussed so we're open to discussion and please ask questions if there is any.

**Comment by sleighwhite** [comment]
+1 on this

I think this would potentially improve roleplay on all accounts. I don't think this is an immediate "fix" or anything, but it will encourage criminals to be more surreptitious in their activities. It will also give FIB more to investigate and build a case around. And it will give Judges something to rule on. 

It is high risk/reward, but I think that it will be situational as well - FIB has to make a good case multiple times before we ever get to "Strike 3" and even when we do, a Judge can decide whether or not they want to grant the permanent repossession. There may be an opportunity for an Appeal to be made which could extend roleplay to Attorneys as well. 

There are also ways for crims to try to allude a repo:
- Using Fake Plates in their chases (and getting away)
- Using different vehicles to throw PD off (instead of the same "meta" car over and over) 
- Stealing local cars to commit crimes in and using them for elaborate getaways 

I think this could be a good first step and see how it pans out and then make adjustments from there.

**Comment by King2704** [comment]
I don't think its a good Idea to give someone the ability to take away someone's car that the person paid irl money to buy in-game. Theres other ways to deal with it in rp if people keep using the same car with no fake plates.

**Comment by coalaura** [comment]
I like this idea

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/VEBEColU94.png)

Works **exactly** the same as /pd_impound just the cap is 6 weeks (for now). The vehicle is put into the regular pd impound so theoretically officers can pull them out earlier but since its logged those officers can then just be fired or smth. not a big deal. The command is only available to judges and works on any non-emergency vehicle as long as you have the plate. If someone has their vehicle withdrawn it wont be despawned tho, so before running the command you'll just have to make sure they have it garaged (it will still always impound but they'll just then have it till the next restart)

**Comment by ImArteria** [comment]
This is epic. Thank you for having trust in us

**Comment by sleighwhite** [comment]
Yes, thank you Laura!
