### ISSUE TITLE
Off road shop! 

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3059]
### Assurance

I have read the `README.md`

### Summary

An off road shop that specializes in Lifts off road tires and trucks! 

### Reason

Something in sandy, that can offer sandy another busy opportunity and RP out there! This would help us who are looking to off road, maybe can even add In some crazy builds like a lift kit for a mustang or camero something silly but realistic! 

would love to chat further about this!

**Comment by coalaura** [comment]
This is not as simple as you may imagine it to be. Adding a "lift kit" for a car requires heavy modeling work for every individual car. In addition to that i don't see the need for it, since midnight which is a lot more in the interest of the general player already somewhat struggles sometimes. This shop would be only interesting for very few people and would require a lot of work.

I think this is a nice idea but it wont work as you imagined it...
