### ISSUE TITLE
Suggestion - Furnishing/Interior decorating improvement(maybe more furniture pls?)

### ISSUE THREAD

**Issue by eatAnus** [InZidiuZ/op-framework-issue-tracker#3137]
### Assurance

I have read the `README.md`

### Summary

make things easier by adding a feature that makes it so that people could easily stack objects on top or next to each other for precise decorating
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/46156400/44b1da88-37cf-4d53-992c-3c27fb6e10cf)
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/46156400/50158cdb-d12b-422a-ae32-0394c9725114)

(also more furniture, people would love that, thanks in advance)

### Reason

as things are now it's beyond frustrating when it comes to decorating homes and making them look unique from the others with what we have to work with, it'd be a big help in saving time and also improvement for RP environment immersion

**Comment by coalaura** [comment]
what would the furniture snap to tho

**Comment by coalaura** [comment]
Regarding new furniture, there was a lot of new furniture added not too long ago and more is already in progress

**Comment by eatAnus** [comment]
> what would the furniture snap to tho??? 

idk how to really explain it but basically a feature that makes it so that objects could connect to each other rather then us have to precisely try and put things together symmetrically, sorta like minecraft/rust building. you can see the flooring i tried placing on the ground has some lines and that tweaks me tf out

> "making them look unique from the others" this would make them even less unique cause everyone would have their things exactly in the same place.

????

**Comment by coalaura** [comment]
> you can see the flooring i've tried placing on the ground has some lines and that tweaks me tf out

This would not get rid of that issue, the texture is simply not-repeatable

**Comment by coalaura** [comment]
Okay, so, since all furniture props are not perfect rectangles making an easy to use snap to grid system is quite a bit task. Especially with props of different sizes. I've implemented a very basic snap-to-floor system now but i will not be implementing any more than that since its a pretty niche use case that requires huge amounts of work. Making props of different sizes snap to each other while respecting their rotation, ignoring the floor, checking collisions with other props, etc. is not a simple addition.

In addition to that a lot of props have weird large bounding boxes that would require manually configuring offsets for over 200 different props.

While holding CTRL you can now press Z to have the object snap to the floor and Q to have it snap to the ceiling (as far as thats possible given its bounding box). I played around trying to get WASD to snap properly too but due to the before mentioned issues it ends up only being a pain/scuffy to use, Q and Z snap were the only ones that didn't feel as scuffy
