### ISSUE TITLE
Suggestion - disable pd lights option added to anti-seizure toggle

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3166]
### Assurance

I have read the `README.md`

### Summary

Add the ability to turn off the flashing pd lights, tow truck lights, ambulance lights etc 

### Reason

For people with light-sensitive health issues or sensory issues.

**Comment by scufflord** [comment]
also, whatever weather cycle that the thunder storm weather spells uses should probably be added to it as well.

**Comment by scufflord** [comment]
after thinking about it, this could be abused and cause issues. not a good idea

**Comment by vol5** [comment]
This should be brought back as a suggestion since as you mentioned it would help with seizures/epilepsy. Along with that it might help massively with fps issues from the lights flashing and people being subject to the entire game freezing from police driving by. 

Curious as to what ways you see it being abused? From what I can tell its more of a benefit because audio from the sirens would still be there.
