### ISSUE TITLE
Suggestion - Increase Wages for Bar Jobs

### ISSUE THREAD

**Issue by Kay32** [InZidiuZ/op-framework-issue-tracker#3244]
### Assurance

I have read the `README.md`

### Summary

Update the Specific Business bar job paychecks to match the untitled business "bar and club" paycheck. 

| **Position** | **Bar and Club Position** | **Specific Business Position**|
|--------|--------|--------|
| Owner | $70 | $40 |
| Manager | $54 | $30 |
| Bartender | $35 | $20 | 

### Reason

There are a lot of bar positions open or not sought after because of the lack of pay for this position. There is no other way for these people money from their jobs outside of the paycheck like other whitelisted jobs in the city. (IE Burger Shot/Bean Machine Runs, Mechanic Tips)

Additionally, there are clubs without a specific job titled (O'Malley's, Hen House, Kissaki Sushi) that don't have special jobs so they are already getting this paycheck.

**Comment by stardome101** [comment]
I currently co-own Bahama Mamas. We only have two members of staff, myself and my co-owner Dougie.

We currently face several challenges that are hindering our ability to function effectively and create a positive experience for both staff and civilians. These issues all stem from a common root cause: inadequate compensation for staff. 

Firstly, our current staff shortage presents a significant obstacle to our operations. With only two individuals managing the workload, it becomes difficult to maintain efficiency and provide a high standard of service. This understaffing not only impacts the quality of our events but also creates a stressful and unsustainable environment for us both. 

Secondly, the high cost of prizes, particularly the large cash rewards or cars often demanded by civllians, is preventing us from turning a profit on our events. While attractive prizes generate initial excitement, their financial burden ultimately hinders our ability to reinvest in the company. This is an unavoidable situation as individuals will not attend an event unless there is a chance of a monetary gain for them. 

Finally, the most concerning consequence of our current situation is the toll it takes on the enjoyment and well-being of the staff. With only two individuals responsible for all aspects of event planning and execution, the workload becomes overwhelming, leaving no room for us to truly enjoy the events we work so hard to create. 

It creates the question: Why would we want to host events if all it does is cause us stress? We have no assistance and nothing compelling to offer. All having a job at our establishment currently is taking away aspects of money making from individuals which, frankly, is a huge part of the city now over interesting RP. Sorry. 😞
