### ISSUE TITLE
Suggestion - Increase maximum purchase limit of PD cars

### ISSUE THREAD

**Issue by T4NZ1M** [InZidiuZ/op-framework-issue-tracker#3260]
### Assurance

I have read the `README.md`

### Summary

Back in the release days, only a maximum of 4 PD cars could be purchased at a time, which later increased to 6. However, with the introduction of Speed Unit cars, the limit remained at 6. Personally, I believe all 3 speed units are crucial in different ways. Additionally, new PD cars are set to be added very soon. Therefore, I suggest increasing the limit to 8 or more.

### Reason

Police cars are uniquely designed to perform their specialized duties as needed, such as the Ram/F250 for off-roading, rather than for regular pursuits. Given the advancements in car tampering, it's essential to utilize different cars for various classes. Therefore, we require specific cars to respond accordingly. Additionally, since speed units are purchasable, so the speed limit should be increased to more than 6.

**Comment by scufflord** [comment]
There's a lot of new cars planned in the pipeline for PD, an increase to 10 would be better

**Comment by TacticalTyl3r** [comment]
I personally would like to own 1 of each depending on what I want to drive for the day. But I do agree an increase to 10 would be a good middle ground. I dont see any disadvantage of owning more since we can't own more than 1 of each. If it becomes a problem of someone pulling out a new one during a chase that could be handled on a staff level.

**Comment by coalaura** [comment]
I don't see a reason to own more than 6 police cars

**Comment by T4NZ1M** [comment]
> I don't see a reason to own more than 6 police cars

Chargers can't do off roading as good as a RAM or F250 can and so can the  RAM or F250 do regular speedy pursuit, so it's needed, then speaking of speed units, the Corvette is good at acceleration and has a con in handling while on the other hand Hellcat and Mustang is opposite. IDK how it's done in main server but in our sub division, we use different cars for different class, so we need to switch cars for different classes. Driving a same car always kind of feel boring and also new cars are being added. So overall considering, I find it actually being a good adddition.

**Comment by rustyjohn1** [comment]
As a police officer, we should be able to use the tools provided to us in this case being different vehicles that are good in their own way but also to give more options when getting on shift rather than being locked to 6 set cars.  and with what has been said more cars are being added, I remember when we could pull out whatever car we wanted to patrol in as they were not owned but the change to owning them was a big win for all, I think increasing the count from 6 to 8 perhaps 10 would go along way and push seeing different cars rather than just 18s the trucks caprice for cadets and the odd other units. with new cars, people are going to want to try them out but my first thought is which car do I sacrifice to buy it?  :)
