### ISSUE TITLE
Update to plush toys (Burger Shot)

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3273]
### Assurance

I have read the `README.md`

### Summary

Rare ones + shoulder pets or similar 

### Reason

I assume there is already a good chunk of different ones after opening 21 today I got around 7 different ones, meaning I assume there is some really low % ones to get if not would be a cool addition! 

Also a lot of suggestion I heard was making them show on the shoulder as the pets do, that could work or something similar to it, something to show off the different plush toys and rare ones we obtain!

**Comment by coalaura** [comment]
I didn't wanna make them shoulder pets since you cant really name them and they are so cheap. The ones i used are base-game and i picked the 7 coolest looking ones out of 9. Made em all the same drop chance but i'd be down to make the 1-2 remaining ones super rare

https://forge.plebmasters.de/objects?search=plush
