### ISSUE TITLE
Green Wonderland Update #2 

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3300]
### Assurance

I have read the `README.md`

### Summary

Strains and effects

### Reason

Kinda like the Sushi menu you can have different strains do different things, I think to start, farming it will be the same just when you go to harvest a random strain pops out, this will only happen from the Green Wonderland seeds. 

For example; 

Pineapple Express - 50% more trash luck for 69 seconds

Gorilla Glue - 2x Sprint for 20 seconds

AK-47 (strain) - No stress on next mag used

different things all the effects are changeable to your liking ofc, but this could add some good rp and value to growing and farming certain strains and what not. Cayo would not follow suit that would jsut drop regular weed still. No effects on use

**Comment by HollaYalla** [comment]
I’ve tried asking about something similar to this and she said Nuh Uh

**Comment by coalaura** [comment]
I've put 8 plants in the back of GW. Those plants have the same timeouts & respawn rates as the weed field, but they give 1-2 q of weed of a random strain. This is intentional since strains should be a lot rarer that your usual weed. When rolled as a joint, it will have the strain in its name and give a certain effect based on the strain.

![yes](https://i.shrt.day/XI6XHLUY61.webp)
![yes](https://i.shrt.day/WGM7KHXTUR.webp)
![yes](https://i.shrt.day/FE5DYLPCMP.webp)

**Comment by coalaura** [comment]
They can't be processed tho, to keep the quality
