### ISSUE TITLE
Suggestion - Replace meth table with gas mask

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3342]
### Assurance

I have read the `README.md`

### Summary

Since we need to get a specific RV already to create meth we don't necessarily need a "meth table" since there should be a table built into the RV anyways. To make it a bit simpler for people + add to the realism of it I would suggest replacing that prerequisite item with gas masks. As is, they only have a use during holdout situations to combat BZ gas, this would give them an additional use.

### Reason

Meth tables don't make sense.

**Comment by gadjinee** [comment]
I like the idea of using the mask instead of the table, it makes sense as we are using the RV already

- Mask
- batteries 
- Acetone 

Maybe we could even add ammonia, for example 

With normal ingredientes you will get somewhere up to 30 meth bags, if you get 5 ammonia to the batch as well you can get up to 50 bags type of thin ( between 10 to 20 extra ) 

Ammonia is harder to come by and means there will be more interest for people to look for it

**Comment by coalaura** [comment]
We can't really get rid of the item, so to add a new item to be used just for "realism" idk if thats worth the effort, i really don't see the meth table as a huge immersion breaking thing

**Comment by scufflord** [comment]
Was more so just cause the table weighs so much, plus the weight of all the stuff you need to do a cook

**Comment by coalaura** [comment]
> Was more so just cause the table weighs so much, plus the weight of all the stuff you need to do a cook

weight would stay the same if i were to replace the item
