### ISSUE TITLE
Suggestion - Change flavor of a brand new vape

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3357]
### Assurance

I have read the `README.md`

### Summary

Currently if someone wants to buy a vape with a flavor in it other than plain or THC we have to take a hit off the vape first and then refill it with the flavor. It would be nice if the vapes could be "refilled" even when full just so it saves some time

### Reason

quality of life, had someone buy 5 apple vapes earlier and it took me forever to do it lmao

**Comment by HollaYalla** [comment]
Instead of doing this because otherwise you could just infinitely refill full vapes maybe add a new item in the store along with the already filled plain vape let us buy Empty Vapes that cant be hit and only can be refilled then they can be hit like a normal vape but they cost 200 less than the already filled vapes as they technically dont have any vape juice in them to add that extra amount

**Comment by scufflord** [comment]
That would also work, just something cause it feels weird having to hit every vape i sell LMFAO

**Comment by HollaYalla** [comment]
I mean its a good perk of working at GW because you get free stress relief

**Comment by coalaura** [comment]
don
