### ISSUE TITLE
Bug report - State Vehicle Spawner

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/op-framework-issue-tracker#3371]
### Assurance

I have read the `README.md`

### Reporter

rakibulhasan456

### Summary

There's a State vehicle spawner in front of the Mayor office, but it's not accessible for all role.

As far as I know, the Mayor and State Security has the spawner. **State Advisor, Employee, and Assistant** doesn't have the spawner.

I'm not totally sure about the Deputy Mayor and Manager role. They might have the access or can be the opposite.

### Steps to Reproduce

Requires State Advisor, Employee, or Assistant role.

### Expected Behavior

I don't if it's intentional or not, but every State representative should have the access to the vehicle spawner.

### Actual Results

State Advisor, Employee, and Assistant role doesn't have spawner access.

### Server

Bangladesh (c10s1.op-framework.com)

**Comment by coalaura** [comment]
These positions have access to it:
Security
Manager
Deputy Mayor
Mayor

This is intentional. The thought is that state security is driving the state employees around while they are providing security for them. Otherwise, State employees can use their personal cars in the garage accessible by the elevator.
