### ISSUE TITLE
Suggestion - Spawn at highway pd

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3418]
### Assurance

I have read the `README.md`

### Summary

highway need love too even tho they made a speed cert into their whole division. let em wake up at their highway pd and go on duty there

### Reason

escobar asked nicely

**Comment by CloudCait** [comment]
In addition to this can we be able to spawn at the FIB building?

(I can make a separate issue if needed)

I've had instances where I'm tryna do some super secret fib work as soon as I fly in or I'm running late because of the queue and need to meet at that building super quick and get followed from MRPD by criminals or I'm getting asked to take cadets out etc

**Comment by coalaura** [comment]
both done
