### ISSUE TITLE
Suggestion - Ability to lookup who pulled a heli out (PD)

### ISSUE THREAD

**Issue by TacticalTyl3r** [InZidiuZ/op-framework-issue-tracker#3432]
### Assurance

I have read the `README.md`

### Summary

I am not sure if this is a thing or if it just scuffed for me but it would be a cool idea if you can use /vin_lookup to see who pulled out a helicopter.

### Reason

This would help PD with seeing who pulled out a helicopter during a scene and they needed to document information.  In theory if you are renting a Helicopter or pulling one out that you "own" there would be paperwork associated with it on who is renting it. It would also help aviation management find out who may have landed a helicopter in a non-authorized area.

**Comment by coalaura** [comment]
I don't think vin would make sense since its a rental thats going to be registered to the owner and not the renter. But i can look into maybe adding a way to trace back who pulled out which vehicle

**Comment by coalaura** [comment]
Ok, so i've made it that the registration is displayed on the tail of the aircraft/helicopter when you look at it (not constantly). When you look at it using a PD camera you also now get shown the registration instead of the plate. You can look up a registration and it will tell you who last rented out the aircraft/helicopter with that registration. (Doesn't work if the aircraft is not around anymore (has been parked/deleted)).

![yes](https://i.shrt.day/ACH5DA5FUD.webp)
![yes](https://i.shrt.day/Q4XAZODMV1.webp)
![yes](https://i.shrt.day/YO59DV2SIP.webp)
