### ISSUE TITLE
Suggestion Bank robberies Cooldown

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/op-framework-issue-tracker#344]
**Name:**
Who is suggesting this? Please include discord name.
Sercan#0001

**Summary:**
Write a short summary of what your suggestion is about.
Adding a cooldown for the bank robberies. 
Cooldown timer should be atleast 30mins.

**Reason:**
Why would your suggestion be a good addition to Legacy?
99% of the robbery includes a hostage, which takes a lot of time. People shouldnt be able to rob a bank without having PD be involved. It would also benefit the economy of the community.

**Comment by ZurxeyH** [comment]
This definitely needs to be implemented.
Cops have been getting extremely discouraged at the moment. People are power gaming the actual shit out of the bank robberies at this time. Having 4 robberies in 5 minutes. It gets repetitive, people putting their vehicles inside banks, having 4+ people to one robbery, 2 people leaving with the money, 2 people staying behind with hostage.

**Comment by HybridSquirrels** [comment]
As a cop I second Zurxeys comments above, tbh it makes me not really wanna play cop right now, In tonight city 1 we had 4-5 robberies happen within 30 mins of Tsunami, as i sate din another thread right now the city feels very power gamed towards criminals, especially when you consider now they are getting faster cars than PD etc

**Comment by Sleezybeezy** [comment]
I agree as well. Finally deal with a good RP'd bank even though they were upset with the outcome it was an interesting RP experience until the end when people started just running up to a live bank robbery with no care in the world. During that same time, in the time it took us 3 cops to deal with this robbery, there were 3 other banks hit at that time. Its getting a little out of hand how easy Thermite is to get and the fact they can run as many banks as possible as long as their are the minimum required amount of cops.

**Comment by KoreeXD** [comment]
Cooldowns need to be addressed, Not an increase of police to rob a bank.

**Comment by KoreeXD** [comment]
> As a cop I second Zurxeys comments above, tbh it makes me not really wanna play cop right now, In tonight city 1 we had 4-5 robberies happen within 30 mins of Tsunami, as i sate din another thread right now the city feels very power gamed towards criminals, especially when you consider now they are getting faster cars than PD etc

This is a funny reply, The reason I find it funny because you say criminals powergame, and get forget that the police powergame as will with helicopters that can lock on, WITH thermal. And also pulling out AUTOmatic weapons during any situation almost.  So sure I can get where you are coming from but you can't tell me for a second that the police don't powergame as well. Even after the PD meeting about thermal on the helicoptor, And police stacking. POLICE still stack in one city, 10 cops in one city, and ur argument is criminals hit 3 different banks at once, Maybe the owner should of put a cooldown on the banks, Sorry that he didnt. But making it seem like criminals are the only powergamers is complete bullshit. The only thing we need is a bank cooldown. Then problem solved.
