### ISSUE TITLE
Suggestion Increase the amount of PD members to rob a bank

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/op-framework-issue-tracker#345]
**Name:**
Who is suggesting this? Please include discord name.
Sercan#0001

**Summary:**
Write a short summary of what your suggestion is about.
Increase the amount of PD member in order to rob a bank to 5 or even 6 cops

**Reason:**
Why would your suggestion be a good addition to Legacy?
99% of the robbery includes a hostage, which takes a lot of time, 4 cops aint enough especially when one of the PD members is the hostage. PD usually response to all kind of calls/reports. implementing this will increase the quality of the role play between PD and Criminals.

**Comment by stormin88** [comment]
would like to see an increased cooldown, but increasing the number of cops would be silly at this point since you guys dont spread out to begin with, 10 cops on 1 server 0 on the rest.

**Comment by jaymssmith** [comment]
Exactly there are never cops on 3 other servers, they are usually all stacked up in one server

**Comment by IceHolyz** [comment]
I Totaly Agree With @sercanatici With this Suggestion and it's Too much Realistic To Rob a Bank should be 6 Cops on duty to Rob it +1

**Comment by HybridSquirrels** [comment]
I am fine with a minimum of 4-5 cops (its 4 now) but i think if its possible only 1 bank should be robbable at a time to allow RP to actually happen. And then if that bank is robbed maybe even a longer cooldown given there are lot of banks that can be robbed. (tbh not sure what current cooldown even is)

To give you an example-
![DIspatch Right now](https://user-images.githubusercontent.com/52386249/62563595-3c14e000-b87b-11e9-8781-e92c58ce5e5b.PNG)
I am literally watching DeadEyes stream right now and they have had 3 bank alarms go off in the space of 1-2 minutes with 4 officers on the server (1 of them a cadet who has to stay with a senior officer for training purposes), this means 2 of those robberies are guaranteed to succeed.....that is basically power gaming all be it within current server mechanics as I cannot see how its pure luck that all 3 banks are being robbed together without it being coordinated, this is further corroborated by 1 suspect in the first bank (the one Deadeyes at) being on their phone probably coordinating the other robberies. 

This is an RP server, people shouldn't care about winning, losing or getting rich its about story and conversation and fun....this mechanic right now does not allow that.

**Comment by AmokBSN** [comment]
Hybrid, thats the most refreshing response I've seen in a long time. Your suggestion and comment melted my heart.

**Comment by samsn8** [comment]
or instead of doing that just have ben make it to where there can only be one bank hit at a time and theres a universal 10min cooldown on all banks. theyll still be open but you just cantt thit them

**Comment by KoreeXD** [comment]
This is an absolutely terrible idea, In my honest opinion, Its already hard enough to have enough active cops in one server, LET ALONE 2, Because they all like to stack in one server to buddy up. I'm sorry I've seen 10 cops in 1 server and it's absolute bullshit. Maybe a Minimum of 5, i could see that, 3 to chase, 1 to watch with heli, and one to take care of the hostage. But even then cops still have the upperhand pulling out SMG's in every situation when criminals don't even have access to class 2's unless they bought as weapons that were removed from ammunation. The quality of Crim and Cop rp has plummeted anyway, There is rarely any RP when somone robs a bank, its a bit of banter and them running away, I agree on both sides some things need to be changed, but definetly not increasing the minimum, Since it is the only real criminal RP interaction with cops that last for a good few minutes before the chase. There should absolutely 100% be a 20minute cooldown on ALL banks the second the officer closes the bank thats currently being robbed. And all banks should be deactivated once a bank has started being robbed. This will allow the PD to get there people where they need them.

**Comment by Vexzarkov** [comment]
I agree, right now with how things are the Econ is going to be in a bad place with 6 banks being hit at once thats at least 90k floating if they do that. i have worked a total of 7 days in PD making 64 an hour to get at least 64K. this invites alot of Bad RP choices and honestly using BAD rp to rob a bank just to grind needs to be fixed. i say at least 7 to 8 cops need to be on duty to have a proper RP correctly.

**Comment by InZidiuZ** [comment]
Hey,

This will not be added. A decrease in the maximum amount of group members allowed to contribute in criminal activity is more likely.

**InZidiuZ**
*OP-FW Developer*
