### ISSUE TITLE
Suggestion - Add flag to allow video on /no_copyright

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#3486]
### Assurance

I have read the `README.md`

### Summary

Add a new parameter "audio" to /no_copyright to allow televisions to display video but have the audio disabled.

Default /no_copyright behavior works as it does now.
/no_copyright audio - would only block audio output from TVs/boomboxes

### Reason

Many televisions are used for menus in restaurants or otherwise have video that would not cause issues for streams.  This would allow people a means to opt-in to a more granular, audio only, block.

**Comment by coalaura** [comment]
TVs generally are not a problem since most restaurants/businesses use them mainly to display their menu which already has no audio. Since boomboxes are generally more the issue when it comes to copyright things, there is already the /mute_boomboxes command which works the same as /no_copyright but only for boomboxes.
