### ISSUE TITLE
Suggestion - Pizza This Local Delivery

### ISSUE THREAD

**Issue by Z3KE337** [InZidiuZ/op-framework-issue-tracker#3520]
### Assurance

I have read the `README.md`

### Summary

We would like more food options in pizza this like Cheese bread sticks, verious smoothie otion similar to burger shot, it would great if any iteam bought from pizza this lowers stress. Additionally, I would like to have local deliveries to be added to Pizza this. This will help my employees make money and let them have a stable income.

### Reason

Adding these features would provide more business to Pizza This. The local deliveries will also help my employees financially giving them more incentive to keep working hard, and it will be easier to keep employees.

**Comment by coalaura** [comment]
So, the thing is, every restaurant that got local deliveries went downhill very quickly afterwards. I'm kinda trying to move away from the easy money grab that has employees just grind deliveries all day and never actually be in the restaurant to serve players. I like the player-player interaction more which is why i don't want to add more local deliveries to businesses

**Comment by Z3KE337** [comment]
How about reducing the money from the NPC delivery instead of completely removing it so that employees won't be bored while customers are not coming? 1 pizza fills up the food bar, and because of this customers buy food from Pizza This once a day and they are good to go for almost 1 and a half day.  Speaking of food please add some team that can reduce stress at Pizza this

**Comment by MetaHatter** [comment]
Although it will reduce boredom, local deliveries take those employees away from the location that we want them to spend more time at.  Could definitely use some ideas to keep people entertained while being at the businesses.
