### ISSUE TITLE
Suggestion - Quality of Life Changes for Yellow Jack Bar

### ISSUE THREAD

**Issue by MissPianist43** [InZidiuZ/op-framework-issue-tracker#3546]
### Assurance

I have read the `README.md`

### Summary

We at Yellow Jack Bar are reaching out to explore potential modifications that could enhance our operations within the city. We are interested in integrating several features that would significantly improve both efficiency and the overall experience for our patrons. Below, we have outlined our key requests, each in its respective category, with accompanying details.

**Topic #1: Consolidation of Ingredients within the Bar**
Currently, we face challenges in sourcing ingredients for our menu due to the need to collect items from four different locations:

- Alamo Fruit Stand for buckets, cherries for drinks, and water
- Paleto Grocery for Pigeon Milk
- Paleto Market for BBQ Sauce, bread, salt, cucumbers, pancakes, eggs, and beans
- Paleto Hunting Store for charcoal
- Time Spent Hunting for meat or buying it from people
- 
This process, on average, takes an hour and fifteen minutes (as timed) before we can open with a full menu. This extended preparation period delays our operations and often results in excess inventory, leading to food wastage and potential financial loss.

We propose that our bar stock these ingredients directly at a set bar price. This change would allow us to streamline our operations, enabling faster openings, reducing waste, and improving cost efficiency by preventing the over-purchasing of ingredients. Having our necessary supplies readily available in the bar will ensure a smoother and more reliable service for our customers. Even if some can get moved, anything to specifically lower the opening time, would be amazing! We strive to open Yellow Jack daily, but with the extensive time constraint, it is difficult to remain open if you do not have the ample time to prepare.

**Topic #2: Installation of a Permanent Grill (Similar to Burger Shot)**
To further improve our service, we would like to request the addition of a permanent working grill at Yellow Jack, similar to the setup at Burger Shot. Currently, the lack of a stable cooking facility hampers our ability to efficiently prepare meals for our customers.

With the permanent grill, we would be able to cook directly at the bar, enhancing our ability to serve fresh food quickly. Combined with the implementation of Topic #1, this would lead to a more streamlined kitchen operation, reducing wait times and enhancing the overall customer experience at Yellow Jack. Even if it is an electric grill that removes the need for charcoal, or a permanent charcoal grill with more slots than 4 so it results in less coal usage and faster multi-food cooking time.

**Topic #3: Addition of Bar Food to the Menu**
In alignment with the improvements discussed in Topics #1 and #2, we would like to introduce new items to our menu. We would like Bar food that would add a unique offering that could set Yellow Jack apart as a standout venue in the city. Subject, but not limited to, Chicken Wings (one or multiple flavors), BBQ Ribs, Stuffed Peppers, Kebabs/Skewers, Chips, Fries, etc. Maybe not all of those, but those are some options that would definitely fit the bar vibe.

This addition would be feasible and practical only if the ingredients were consolidated as described in Topic #1, allowing us to maintain a consistent supply. We envision offering different flavors of wings or simply serving traditional options as a Yellow Jack special, creating a “wow” factor for our patrons.

### Reason

**Conclusion**
We believe these modifications would significantly improve the operational efficiency of Yellow Jack Bar, enhance the customer experience, and contribute to a more immersive gameplay environment within the city. We kindly request your expertise in evaluating the feasibility of these changes and look forward to discussing potential next steps.

Thank you for your time and consideration. We are excited about the possibility of collaborating with your team to bring these enhancements to life.

**Comment by coalaura** [comment]
> cherries, water, pigeon milk

i dont mind adding these to the bar store

> BBQ Sauce, bread, salt, cucumbers, pancakes, eggs, beans, charcoal, meat

these i will not add as they are not really bar items

> Installation of a Permanent Grill 

This would be something for the [asset issue tracker](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues)

> Addition of Bar Food to the Menu

No, bars are not meant to be restaurants serving food, there are various snacks available but food is for the restaurant businesses in the city

**Comment by Dibbey** [comment]
I would like to add, that having worked at Yellow Jack and seen the business activity of the current businesses, Yellow Jack is the only "Food providing" business in Sandy at the moment (and at all), and overall for I don't know how long the entire north of the island (since Steak House barely survives ever). While they also don't get as much traffic as the Steak House in Paleto or the repair shops Paleto Bay and Harmony, Yellow Jack has been rather active in the last weeks providing a good source of drinks and food for the city bringing more people away from the city and up north.

I gave MissPianist the suggestion of suggesting the Ribs, Skewers, and Stuffed Peppers next to the Chicken Wings, in the hope one of them might get added to provide a good consistent business food for Yellow Jack and the North, so that they can open with something to provide the city, without having to go on a tour of an hour of preparation that they instead could use to have the business open, just to make pancakes, beans on toast, eggs, bbq sandwiches etc. so they have anything satiating to sell and attract any customers outside of simply being a bar when other food businesses like Pizza This and BurgerShot are not open (the only other active businesses currently). Hopefully, the addition of one of those food items could be re-visited as an addition to their already BBQ-style menu. 

If not, that's okay. But I wanted to add my thoughts nonetheless having seen how much work they've put into Yellow Jack, plus the fact they've established themselves so well and are still going strong is admirable seeing as other similar businesses usually fall apart after a couple of weeks.
