### ISSUE TITLE
Suggestion - Pizza This Apple Juice and Baking

### ISSUE THREAD

**Issue by MEOWkasan** [InZidiuZ/op-framework-issue-tracker#3590]
### Assurance

I have read the `README.md`

### Summary

it will be great to be able to bake more/multiple pizza at once as one can bake only 2 at once. and adding an item to the similar to green apple 

### Reason

in IRL one oven can bake many different types of pizza at once and  increasing the baking quantity will reduce time each order and helpful for the employees. And as for the Drink people commonly ask if we sell any drink which will give them a boost similar to green apple adding it will be a great addition to pizza This

**Comment by coalaura** [comment]
i don't think the speed of making pizzas should be reduced further, it should take a moment to get food from a restaurant like irl. We are already much much faster than irl ofc.

I like the idea of apple juice, however i don't see how it would give you a speed boost. Green apple gives you a speedboost since its an energy drink. I don't mind adding green apple to the pizza this store tho.

**Comment by MEOWkasan** [comment]
I was suggesting a drink more like pink lemonade which will reduce stress and will  give a speedboost, if apple juice isn't a thing then pink lemonade will also work great

**Comment by coalaura** [comment]
> I was suggesting a drink more like pink lemonade which will reduce stress and will give a speedboost, if apple juice isn't a thing then pink lemonade will also work great

Like i said, i added green apple to the store. Pink lemonade is a beanmachine thing
