### ISSUE TITLE
[illegal/meth] Addition of a proper meth system

### ISSUE THREAD

**Issue by thefinalgamer** [InZidiuZ/op-framework-issue-tracker#435]
**Name:**
Who is suggesting this? Please include discord name.
th3finalgamer

**Summary:**
Write a short summary of what your suggestion is about.
Meth los santos aint los santos without a little bit of meth in the city 
**Reason:**
Why would your suggestion be a good addition to Legacy?
so I got showed this script
 https://forum.fivem.net/t/meth-cooking-like-in-breaking-bad-esx-release/740096

people are asking for more things to do in the city together making this a 2 player thing having  people work together. having red smoke coming out will make people target them so maybe they need more than 2 to help defend them while cooking ? could bring some rp gang war type. also if police spot the red smoke then police can chase them down just a thought

**Comment by MICWIK4U** [comment]
This idea looks awesome.

**Comment by Aspratic** [comment]
I think this can add a little bit of roleplay into the city but I think instead of the meth van there are better ways to enable rp throughout the city.
Think of how many people are going to go to spots on the edge of the map that you shouldnt even be allowed to drive the van on, and have no interaction other than pressing 'E' and talking with someone theyve already rp'ed with for a long time.

**Comment by twooot** [comment]
Meth was added with the recent update
