### ISSUE TITLE
Gun Crafting

### ISSUE THREAD

**Issue by Bowchikahonhonk** [InZidiuZ/op-framework-issue-tracker#458]
**Name:**
BowchkaHonkHonk#5146

**Summary:**
For gun crafting at the start we could have schematics across the map like we did for the chips. The schematics show how to make each weapon/attachment.  

**Reason:**
This would help with having a gang control the gun market and people wanting to fight for said schematics

**Comment by SATIN187** [comment]
This would just cause more people to RDM and rob a guy that found one like it did with the bank chip and tuner chip... but it’s a good idea

**Comment by Aspratic** [comment]
Have 2 gangs be whitelisted for crafting guns. It forces people to RP with the gangs and learn how to talk to people outside of their circle. Creates so much RP and is good for the server

**Comment by Aspratic** [comment]
the reason for 2 gangs to control it is so if one gang doesnt like you then there is another opportunity for you to purchase guns.

**Comment by Trasaraj** [comment]
Or State Sends a Guy in the city who will auction Guns for gangs, The gangs can buy it from him, I mean Special guns. Once a month.

**Comment by AdeptCL** [comment]
I do like the idea of "the State sends one guy".
However, I feel like there should be a period of 2-4 weeks of higher ups watching how whitelisted gangs are working in the city. The "best" ones should be rewarded as being the whitelisted operation starter for things like crafting/etc.

**Comment by Aspratic** [comment]
My understanding is there already is a gang that will be given the whitelist for gun crafting. won't meta and say who but i'm already sure there is a gang that is whitelisted for something.

**Comment by Aspratic** [comment]
The government should definitely watch more gangs and their RP to incoperate more whitelists though for things other than guns, such as attachments, new drugs, tunershop etc

**Comment by Sleezybeezy** [comment]
The only problem i have with this idea is same as last city i was in with this feature. You piss off or attack a gang, and you get cut off from the craftable guns. (blacklisted). Which makes it to where no one will attempt to anger that said organization because then they are unable to buy guns. As stated i had this issue in my last city, only difference is i paid off one of their employees to work for me under the radar. I like the general idea but having organizations controlling that big of a market isn't good in my general opinion for that exact reason. The people who get that right to control guns, are basically untouchable. Even if there are 2 organizations, you piss off one, you still have the other, but if you piss off both you are completely screwed. Drugs or anything else of that nature is perfectly fine to be ran by organizations, but having 1 or 2 organizations strictly the only people that can craft wouldn't be ideal.

**Comment by selb97** [comment]
I think there should be a job which you transport goods for "materials" to transport guns. Gun materials are illegal and can be confiscated by the cops.

Then these materials are being used to craft weapons. You start at gun crafting level 1 and have to work your way up through the levels to craft the heavy weapons. E.G:

Level 1: pistols. (Have to craft 20 pistols to level up)
Level 2: SMG's (have to craft 50 smg's to level up)

^ just an example.

**Comment by Aspratic** [comment]
having "levels" is not very realistic. there aren't levels to get guns irl, doesn't make much sense and in my opinion isn't the best roleplay

**Comment by InZidiuZ** [comment]
Hey,

If this is still relevant, please create a new, more detailed issue.

**InZIdiuZ**
*OP-FW Developer*
