### ISSUE TITLE
[companies/stocks] Changeable rent amount

### ISSUE THREAD

**Issue by iGreatWhite** [InZidiuZ/op-framework-issue-tracker#489]
**Name:**
Who is suggesting this? Please include discord name.
iGreatWhite

**Summary:**
Write a short summary of what your suggestion is about.
Adding a way for the landlord to change the price on a property. If he was to increase all tenants would have to pay the difference before the week ends. If it was lowered some of the rent played would overlap to next week

**Reason:**
Why would your suggestion be a good addition to Legacy?
This way people can keep paying on their house but the landlord can adjust pricing to the needs and wants of his tenants

**Comment by FilipQeh** [comment]
Would be great.
Only work around for this is to wait for the contract to terminate and then re-rent the house to them for a lower or higher price. It's all a bit clunky so I definitely feel like this would help out a lot.

**Comment by InZidiuZ** [comment]
The only way I think we could "safely" add this would be by creating a sort of "contract change" in which both parties would have to agree & confirm on the change, as otherwise this could be quite heavily abused by the landlord.

Another idea is to create an actual "contract" system which would let you sign a lease with a company/landlord for an X amount of time for an agreed weekly rent, which could later be (dis)continued on new terms.

**Comment by AdeptCL** [comment]
Couldn't you do a similar process of when you rent the house to someone.

"<person> rents you this house at <price>. Type /accept to accept."

You're then able to see if they're scamming you from an agreed price + decline it if you think they're abusing it.

**Comment by InZidiuZ** [comment]
Yes, @AdeptCL, like I said...

> The only way I think we could "safely" add this would be by creating a sort of "contract change" in which both parties would have to agree & confirm on the change, as otherwise this could be quite heavily abused by the landlord.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
