### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by hcboss** [InZidiuZ/op-framework-issue-tracker#495]
Reporter:
@mj Legacy Gaming#0001 INDIAN LEGACY SERVER ADMIN

Summary:
I BOUGHT AN BLOCK FOR 9k SHOWING 2 SLOTS IN IT AND ONLY GOT 1 HOUSE IN IT
MAYBE A BUG OR WRONG BLOCKING OF HOUSES
Additional Information

Screenshots:
https://cdn.discordapp.com/attachments/603653826427486217/631383375868854272/Screenshot_103.png

https://media.discordapp.net/attachments/603653826427486217/631383380503822336/Screenshot_102.png?width=1201&height=676

Notes:
MAYBE MAKE 2nd HOUSE VISIBLE OR CHANGE SLOT NO TO 1.

**Comment by InZidiuZ** [comment]
Hey,

It's due to one of them being an MLO interior, and was therefore removed afterwards. You're only paying for one of them, so don't worry about that. I've updated the /blocks with the latest properties/costs, though, so it should now display correct information for *all* blocks.

**InZidiuZ**
*OP-FW Developer*
