### ISSUE TITLE
Armor Gets Removed

### ISSUE THREAD

**Issue by Cricketx818** [InZidiuZ/op-framework-issue-tracker#513]
**Reporter:**
Cricketx818

**Summary:**
When I smoke joints to get armor, and I leave the city & come back, My armor is gone, it happens every time I wake up in my house, Not to sure why, I even go to the back of my house and (Log out) before I quit FiveM and I still Dnt have armor once I wake up.

**Comment by AdeptCL** [comment]
Sometimes for me it stays. Sometimes it doesn't.
It would be better to know that it doesn't stay or if it does 100%.

**Comment by InZidiuZ** [comment]
Hey,

As it comes & goes, I'm gonna guess it's due to the terrible way we do the "player loading" as of now. As this is a pretty core thing, I won't start messing with it right now, but plan to rewrite it entirely in the near future. You'd be more 'exposed' to this issue the higher latency you have, so you being in California while the servers are in the UK, it makes sense you'd experience this.

**InZidiuZ**
*OP-FW Developer*
