### ISSUE TITLE
Suggestion: Bank Robberies

### ISSUE THREAD

**Issue by triatomic** [InZidiuZ/op-framework-issue-tracker#520]
**Name:**
tria#6025

**Summary:**
Remove the added bank cool-down.

**Reason:**
-Because artificial barrier which cant be role-played is bad.
-Cops get more roleplay with more robberies.
-bank robberies can be hugged by the same group which makes normal people who wanna rob banks not able to.

**Comment by iGreatWhite** [comment]
+1

**Comment by ZroonX** [comment]
+1

**Comment by Cricketx818** [comment]
-1 Keep cool downs because cops complain how there is more then 1 bank getting hit at the same time, when there was not a cool down it was "oh okay another bank job" and now there is a cool down cops are "omg nobody is hitting a bank"

**Comment by iGreatWhite** [comment]
You gotta think about it from an RP perspective. We go through all the hassle to get together a heist with outfits, changing our voices to not be recognizable, searching for the hostage which can be tricky sometimes, pre planning the escape. For it all to foil when we go to the bank and can’t hit it because there is a bank currently being robbed. Cops should just utilize the amount of troopers and spilt them on bank robberies.

**Comment by HybridSquirrels** [comment]
-1 from me because it just ends up in a bank farming sim.

Whilst I appreciate there are many people like myself and clearly several here commenting so far who want to RP those situations with a full prep etc alot of people don't and tbh even in the time banks have been available it has thrown the economy out in a big way....if you want proof of that look at how many people own 5+ vehicles as well as entire mansion districts. My guy has 1 chopper bike, a van and a tow truck and even then only 15k because I refuse to farm banks/drugs etc excessively as personally that's not good RP doing it all the time, have some downtime hang out, do legit jobs a bit etc. Secondly cops will get tired of trying to RP bank jobs and start just nope out of RP as they will be so rushed off their feet which was how it started getting before cooldowns were introduced.

If it bothers you that much to have wasted the time then all you need is an easy way of checking if banks are active which might be a better solution?

Outfits can be 'bought' and reused whenever if you save them so that prep can be done anytime therefore you'd only be talking about getaway vehicle prep and grabbing a hostage (last ones fairly easy most of the time)

**Comment by AmokBSN** [comment]
Okay, so you go through a lot of hassle to get equipment. Changing your voice and outfit isn't even a valid argument because that's simple to do. It's also up to you to determine whether you have a hostage or not 5 head. It's not like you are getting caught by _attempting_ to rob. 

Also pre-planning escape? Please, no spike strips, heli or whatever is the general norm is these days or even using your own car. Cooldowns exist because it means PD doesn't have to always head to banks. It would be insane if they had no cooldown. Goodbye economy.

**Comment by iGreatWhite** [comment]
See you’re just thinking I chain rob banks. I like to pre plan my escape so I know exactly where I’m going. Also when we get 4-5 people all in the same outfits with a little variety it can take some time. Not every robbery of mine is me standing at the door telling the cops, “no spiky spiky”. Like if people aren’t here to RP and rob a bank very fast and rushed it’s just not good RP and can be punished accordingly. And isn’t it the PDs job to serve and protect if they don’t wanna try to stop people from robbing banks why are they a cop?

**Comment by W1lsonCodes** [comment]
This isn't a good idea,

When there was no barrier on this the police had to respond to 2-3 different banks all being robbed at the same time. This is very unrealistic and trash. If the barrier was removed it would start up again.

Limiting the robbery chances allow's police to have a breather and allows criminals to perhaps have a better plan on escaping since they would be using alot of recources.

Wilson

**Comment by HybridSquirrels** [comment]
@iGreatWhite Not what I said. I know there many people with good robbery RP who wouldn't abuse but this is a public server and there are/will be many who do. 

My comment was meant as a general reason not targeted  at you and I stand by it for reasons stated

**Comment by Lankovich** [comment]
-1 The barrier is effective, before the PD could have 2-4 bankrobberies at the same. If we're lets say 5 cops on duty, and 4 bankrobberies show up pretty much at the same time, it will just make the officers job so much harder according to processing and even to have a chance catching any crim. We can't respond to another bankrob with suspects being handcuffed in the cruisers. This problem is being abused I think by some people or atleast it could be, by a big group splitting up to different banks at the same time.

**Comment by Trasaraj** [comment]
-1

**Comment by pxyeb** [comment]
-1. It's effective, since we got this we have only good robberies and no one is chain robbing anymore which was bullshit to deal with. The roleplay we were getting (sometimes having 3-4 robberies at the same time) was shit. The cooldowns were especially made to prevent this.

**Comment by psyCOSMO** [comment]
Barrier is necessary to keep bank jobs with higher level of roleplay, when you get chain robbing you actually start not to care about it, and usually it ends up in a rushed roleplay which is boring.
I'd say have a like news pop ups, and so you won't go and check if there is a cooldown, you'll have a pop up like:
"Weazle news: Bank at Legion recently had an attempt of a heist, in result all the banks in the city is closed at the moment" something like that...

**Comment by InZidiuZ** [comment]
Hey,

This probably won't happen, looking at the feedback on this issue... :p 

**InZidiuZ**
*OP-FW Developer*
