### ISSUE TITLE
With the addition of class 2 and 3 weapons need something to stay competitive.

### ISSUE THREAD

**Issue by PanchoGarcia** [InZidiuZ/op-framework-issue-tracker#587]
**Name:**
Pancho#0001
**Summary:**
Cops need to have some sort of counter to the long guns that are going to be coming in the upcoming weapon heists, perhaps a semi-automatic carbine rifle?

**Reason:**
As it stands right now the cops don't have the ability to fight at any sort of range. Right now as cops we have 2 main weapons assigned to us. a regular pistol and an SMG. as seen [here](https://imgur.com/oPjZSpx)  the Smg and the pistol are almost the same guns, save for one being full auto and having a slightly higher range (although that doesn't matter because of recoil) When compared to something along the lines of a musket or the Ak, There is no real comparison to be made. With the incoming weapons coming into the city, situations, where officers are being shot at from a distance they cannot effectively shoot back, are going to increase significantly. [Here](https://plays.tv/video/5db87d1af2c1e88770/is-why-we-need-some-sort-ranged-weapon-as-cops) is one instance, for example, there is a sniper shooting at us from a rooftop, yet in order for us to shoot at him at all and actually hit the mark we have to be somewhere in the 100-yard range for us to able to do anything back. where the bank robbery was taking place, the officers on scene could see the guy but they couldnt do anything at all. At certain range bullets in GTA, no matter how accurately they are fired will be ineffective at doing any sort of damage. I've heard the argument that we shouldn't bring in long weapons because of the difficulty of acquiring the new long guns for criminals. and while that argument is a good one it is one easily solved. Make it so long guns are locked behind a rank if thats what would make it fair. A criminal heist, even if it took a player a full week to complete is nothing compared to the amount of time and work it takes to get to the rank of Sgt. in the SASP. People have a well-known fear of cops becoming attached to the weapon but I can tell you this is not going to be the case, there are systems such as IA to prevent the abuse of such tools the police have, much like in the same way we do with the already powerful tools PD has, like cars, cuffs and various other tools in the cops toolbox. Conduct is held to a high standard, we can make rules for it and they WILL be followed. if they are not, then people will be held accountable. Adding a grip, while its a step in the right direction will not solve the issue, the gun is still shit, doesn't matter how accurate it is. I know people are hesitant but we have had great success with other things people were concerned about, like the mustang and that has not been abused in the slightest. This is not a matter of it being cops always have to win mentality, it's more of cops need the proper weapons to do their jobs sort of deal in this situation. It is incredibly frustrating as a cop to not, no matter how much you prepare, be able to deal with a situation criminals are going to be presenting to you. If we continue the way we are going right now, adding in more and more weapons to crims and not taking a look at the weapons the cops have, to deal with them, the crims are going to continually become overpowered more and more as the days go on. Im not asking for an MG or a minigun to make it a cops win everytime situation, im just asking for them to get a fighting chance.

Here is a video showcasing the issue https://plays.tv/video/5db8977f2386183c9c/the-smg

**Comment by Karpenkooo** [comment]
I agree with this. Given that the rifle is only for Sgt+. The PD Mustang is actually a really good example of PD getting a tool that is as good as what the crims have. I've not seen it getting misused at all. I'm all for this if it's SGT+ !!!

**Comment by Aspratic** [comment]
Okay allow you guys to get big guns but criminals need to be able to take the weapons off of the officer. 
The counter argument for this is that criminals will go around robbing cops, if this is true that is FailRP and should be met with a ban
There is no justifiable reason to not allow criminals to takes guns off of cops.
If caught there should be a huge fine and jailtime.

**Comment by iGreatWhite** [comment]
Needs to be marked as a PD Weapon. So that you guys know very well that’s a PD issued rifle.

**Comment by Lankovich** [comment]
> I agree with this. Given that the rifle is only for Sgt+. The PD Mustang is actually a really good example of PD getting a tool that is as good as what the crims have. I've not seen it getting misused at all. I'm all for this if it's SGT+ !!!

I agree as well, but I think it should be a AR training for Corporal+. Not too many are SGT+ and not even close to everyone will even get there. I can't even count on how many times I've been shot at by muskets etc when there's no SGT+ on duty with me. 

This is just my thought tho ^^

**Comment by joevapes3** [comment]
First I agree that PD needs stronger weapons with the introduction to class 2 weapons for crims. PD is already having a real hard time in any fire fight now with muskets, and shotguns currently. I think Corporal and up would for rifle training would be sufficient since if you are at a rank of Corporal you've clearly dedicated some time into the PD at that point. If someone by Corporal rank has not displayed the characteristics of being trusted with a PD rifle then there is a bigger problem then just being trusted with a rifle.

Second, if a trooper is abusing the PD Rifle then the certification should be suspended pending a review. This addition of a rifle to PD should be viewed as a tool and anyone that does not understand that would not be a good candidate for carry any assault weapon period. Pistols should only be used when faced with pistols, and when an officer observes the use of class 2's, only then should they transition over to the rifle at that point.  

Finally limiting the potential use a PD rifle to SGT+ would be very limiting to the usefulness of the tool. SGT+ is currently the smallest group of PD currently, and when one of them is not on duty then ranks under them would be at a huge imbalance during a fire fight involving class 2 weaponry. If the use of a PD rifle becomes clear that it is too powerful for PD to have then it can always be removed. However PD has been at a extreme disadvantage with the use of muskets, and shotguns currently. So much so that crims are no longer even bringing hostages to bank robberies since they know they will be able to kill every PD member present without the need of class 2's. So to conclude, in my opinion the implementation of a PD rifle would really bring a positive balance to the server.

**Comment by ZurxeyH** [comment]
> I agree with this. Given that the rifle is only for Sgt+. The PD Mustang is actually a really good example of PD getting a tool that is as good as what the crims have. I've not seen it getting misused at all. I'm all for this if it's SGT+ !!!

Sgt+ is too much. Should be Senior Trooper or Corporal+ with a training camp.

**Comment by InZidiuZ** [comment]
Hey,

To honor your reinstatement & the community's interest, PD will now be given 'Carbine Rifles'. Apologies for the short delay. These must be heavily restricted and overlooked by higher-ups, otherwise they might be removed in the future.

**InZidiuZ**
*OP-FW Developer*
