### ISSUE TITLE
Content changes

### ISSUE THREAD

**Issue by Cironite** [InZidiuZ/op-framework-issue-tracker#641]
**Name:**
Who is suggesting this? Please include discord name.
Ciros#2048
**Summary:**
Write a short summary of what your suggestion is about.
I would like to suggest new content to force interactions with players and as well as changes to already implemented content.
1. Make Mechanics Whitelisted again.
2. Buff Reporter job? Maybe have State reward them for good news.
3. Maybe new/changes to make some content  CO-OP to force players to interact with others.
**Reason:**
Why would your suggestion be a good addition to Legacy?
1. As of right now we have "Mechanics" Who do not respond to calls, and only use the job for their own benefit, and Mechanic Roleplay is dead as of now, I took me 3 days to get my car fixed and the one who fixed it is a close friend of mine, The only mechanic roleplay we have right now is the Lost Mechanics, And they are in 1 server, which is no problem but they are the only Mechanics who do their job as actual mechanics, Now having Whitelisted Mechanics again would only get people who want to be mechanics and roleplay as one do their actual job instead of people just doing it for their own benefit and them being an actual Criminal/Civilian instead of a mechanic.

2. I believe Reporter job should be buffed to get more people using it, For example we can have them get Paid by State/Government an X amount of money that is related to their content/success
I believe this would give players an incentive to get creative with it.

3. As well as changes to Mechanics and Reporter job, Me as a staff member and a member of the community would like to see changes to some of the Civilian Content, As of right now they are too grindy, And we have people in our community that just grind all day, Yes its supposed to be a roleplay job, but I don't see any reason for players to do them right now when Criminal Roleplay is Low Risk High Reward when it should be the other way around, As of now, A new player would do the following: Grind Garbage for 3 hours, get enough money to buy tools for house robberies, farm house robberies, use the keys, get the crate and boom Class 2 weapons, So simple and so easy to obtain, Then they can either sell to profit more money then repeat the cycle or they can keep it and use it, Now how would we fix it? Honestly the best idea i could come with is Making some of the criminal content CO-OP as in Requiring you to have more than 1 person to be able to finish it, Forcing players to interact with each other instead of doing solo grinds, which completely ruins the point of Roleplay, You cannot roleplay with yourself, So maybe forcing players to interact with others could be considered taking initiative and opening most of the community eyes to the possibilities of roleplay, and you don't have to juice money 24/7, The objective is not money money money and money, it should be about having fun especially with others, And I believe having Co-op content would enable that, Especially since we are a public server, a lot of people come here, they know no one and they have a hard time breaking out of their shell, and they start doing the complete opposite of the server purpose, All in all, I believe implementing these changes would massively affect our current community positively.

**Comment by InZidiuZ** [comment]
1. No. It *won't* be turned into an 'official' white-listed job. The idea is to eventually let companies set themselves up as different "company types", and let them focus on other things such as vehicle sales, *mechanics*, resellers/pawn shops and the one we currently have, real estate.

2. Possibly. The state already has this ability, as they have access to the money obtained through tax.

3. Create an issue dedicated to a full-on "CO-OP" job, don't just go "pls add coop man".

> As of now, A new player would do the following: Grind Garbage for 3 hours, get enough money to buy tools for house robberies, farm house robberies, use the keys, get the crate and boom Class 2 weapons.

You're explaining a new player *that doesn't push towards roleplaying*'s situation. Roleplaying with grind-mechanics is still possible, take N* as an example. There's meant to be an economy within the items, which should encourage RP between players. When this is better set up & balanced, this would have the same effect as the 'CO-OP' missions you're talking about.

It seems you're forgetting we're still just in alpha, and probably won't be out of alpha & beta before months, if not years, considering how I'm the only *main developer* scripting this, and I also have little time due to IRL.
