### ISSUE TITLE
[illegal/oxy] Oxy Change

### ISSUE THREAD

**Issue by Aspratic** [InZidiuZ/op-framework-issue-tracker#742]
**Name:**
Who is suggesting this? Please include discord name.
Aspratic#3121
**Summary:**
Write a short summary of what your suggestion is about.
Changing oxy to make it less grindy and a bit more risky

I know oxy is currently up north to try and get people to go up north more often but this is limiting rp. My suggestion is to move oxy down into the city, where it is more realistic for people to be buying it. On top of this, have set vehicles that will come up as stolen if pulled over (car has to be used). And make the oxy sale locations in highly patrolled locations/locations where criminals could get caught or rp with other crims. Also add a period in between the sales, maybe 15-30 seconds. Lastly it would be best if other players could see the NPC you are selling to and they can see the NPC handing over money.
**Reason:**
Why would your suggestion be a good addition to Legacy?
This suggestion would be good for legacy because instead of forcing players up north we can change this into possible RP. We should always focus creating RP rather than using the entire map as RP is the focal point of us playing here. The benefits of creating this RP drastically outweighs the negatives of people grinding in their hypercars and interacting with no cops and no players with no risk of getting caught.

**Comment by Pyrotimegamer** [comment]
Personally think this would be pretty bad.

And i have multiple reasons for it there is currently no reason to go up north but to execute someone. Oxy is the only reason people would go up north. I agree completely with making it more risky then it currently is but I honestly believe that moving Oxy to the city or anywhere else on the map would be really bad for the groups up north I would even go as far as to sugest to bring more things up north (and in the server in general) so that locations are pretty spread

**Comment by Livius99** [comment]
Pyro is right

**Comment by iGreatWhite** [comment]
I didn’t want to repost a sample of the same issue so I will just comment my thoughts out. If we moved Oxy back into the city it would create more of a dynamic for cops to see criminals passing off drugs and speeding around. As of right now there is minimal risk to selling oxy because you take highways and that’s it. I also feel as if you should be required to use the car it gives so that people aren’t speeding around in super cars doing pill runs. This is all you’ll see up north is super Cars running oxy.

**Comment by DaxterPancake** [comment]
I do agree that there does need to be a change because it's currently no risk, high reward. I disagree with forcing them to use the car that spawns as that would then make it so that any time cops see you in that vehicle, they will pull you over and grill you over what you're doing. An easy fix to that is to make the car it gives you be chosen out of 6 or so different cars. Also having it up north means that that area of the city is actually being used instead of barely anyone going out there.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
