### ISSUE TITLE
[player/health] EMS "/status" check for when not in Pillbox

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/op-framework-issue-tracker#744]
**Name:**
AdeptCL#0402

**Summary:**
Allow anyone with Paramedic+ rank in EMS to be able to do /status when out on-call to an EMS call.

**Reason:**
As someone who tries to focus on Paramedic duties, rather than doctor's duties going out to a call is inevitable with the ambulance. Occasionally, we run into people that don't necessarily interact back with our questions/commands, or understand they can "/me" to show injuries. Being able to do a /status check on downed individuals will allow us to see any injuries they may have and carry on with the roleplay accordingly, even if they're in their heads and/or not responding back.

It also allows us as Paramedics to continue the roleplay through to dispatch when there is a doctor, preparing them with knowledge of the injuries so they can get prepared with what they "need" for the procedures.

**Comment by DaxterPancake** [comment]
+1 Would be great to be able to inspect injuries while on calls, gives more roleplay other than loading them into the ambulance.

**Comment by superiorchicken007** [comment]
I believe this was implemented a few updates ago by using /inspect

**Comment by ekhowan12** [comment]
I think there should be more injuries to add. Most of the time nothing shows when we do /inspect .

**Comment by CloudTheWolf** [comment]
> I think there should be more injuries to add. Most of the time nothing shows when we do /inspect .

There are 3 variations form what I have seen

1) Sometimes it will so No Injuries or Bleeding. (Can't always be trusted, have to /inspect 2/3 times to verify)
2) Sometimes it'll say Multiple Injuries. (Somewhat useful, but what are these injuries?)
3) Sometimes it'll say a specific injury. (Useful)

This looks to be based on if the target player sees a message on their side the EMS will also see the same thing rather than getting all the information.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
