### ISSUE TITLE
[illegal/weed] Suggestion

### ISSUE THREAD

**Issue by kap-10** [InZidiuZ/op-framework-issue-tracker#747]
**Name:**
KAP10#3649

**Summary:**
Opening 'Smoke On The Water' down by Vespucci beach and have 'legal medicinal marijuana available to purchase.

**Reason:**
1. Creating supply and demand with weed

With this I would like the Smoke on the Water store down by Vespucci Beach to be accessible to the public and be able to serve medicinal marijuana for purchase. This will allow civilians to get it easier, creates some RP down by the beautiful Vespucci beach and creates an incentive for people looking to make money in my next point

2. The store stock will depend on its suppliers and economy. What I mean by this is that, players will be able to sell their product as bulk to smoke on the water store if they wish to get paid more than the street price but at a legitimate expense. The benefits of this will be that if players decide they want to grow weed, they can at least profit from their hard work and sell the fruits of their labour. If the store has little to no stock, players will be able to earn more as the demand will be high for weed. Where as if the store is already stocked up then the price will be much lower and this will tie in with the economy. Each week the store will have a different level of stock depending on the previous week. If the store had a good week with no shortages and always stocked up, then the cap stock level might increase the following week, thus allowing players to donate more, however if the store has a bad week and struggled to keep stock then the cap amount available to purchase will also decrease.

3. Perhaps maybe make the Smoke on the Water store a whitelisted role such as people would have to fill in an application in order to be the store owner/manager/employee etc and this will create more RP such as more stoner type characters and other sorts, more business and a more Civilian friendly job. furthermore, it will make the role more in check like PDM salesman, EMS, LSPD etc so that not just anybody can run the store and will be monitored properly to avoid players exploiting for self gain.

4. And lastly this will benefit or at least create a change in the economy so that people who grow their own weed can at least sell in bulk if they want to avoid the hassle of selling to crazy locals and I believe this can create more business to business type RP if that is what people are into but yeah I am interested as to what peoples thoughts are on this and what they would like to add as well?

Thanks for reading.

**Comment by Djmeowzle** [comment]
This is actually a fantastic idea, This would bring a lot to legacy, but would have to be very closely controlled, Prices would maybe have to be static, but I feel that if you only sold joints, it would be a lot better, otherwise, people would just come to buy weed cheap and sell it on the street for more, or when they can't sell at a good street price they sell to you for an inflated price. you could make joints something like $50-$80 or something, but selling weed itself wouldn't be a good idea + people would 100% meta/power game the fact you have all this weed, and just rob you to sell it themselves, joints can't be sold to civilians, and are only used to relieve stress, so it would work out better if it was joints. That's just my 2 cents :)

**Comment by twooot** [comment]
We have the dispensary on sinner street now
