### ISSUE TITLE
[companies/businesses] Used cars dealership

### ISSUE THREAD

**Issue by kucej** [InZidiuZ/op-framework-issue-tracker#761]
**Name:**
dugzy#9752.

**Summary:**
A place or a parking spot within the city, where you could do 2 things:
1. Drop off your used vehicle with the description (car backstory, upgrades etc.) and specify a price (How much would you like to sell it for).
2. Browse the database of all the vehicles dropped by other players in the lot and the option to buy them at the price specified. (+state tax)
When the vehicle is bought by another player, the money would be added to the sellers bank account.

Since theres no way you'll do this rn, might be something to think about for beta?

**Reason:**
People are scared to buy vehicles off of each other, due to so much scamming in the past in the city. All the car sales circle arround "I'm not going first" and it usually ends up in no-deal. This could also be applied to all other items, not just cars, a marketplace.

**Comment by Livius99** [comment]
I like this idea but you know... the scam is real, if u think people try to scam others IRL every second so... I think it's better if we focus on Roleplaying

**Comment by Cricketx818** [comment]
I believe this will be coming out once the company can own businesses

**Comment by iGreatWhite** [comment]
This is an interior that could be used for the used car shop. The only main issue though is that this would replace the fact of the current Grove Mechanic Shop. But overall, I feel like being able to sell your car at a shop versus just advertising it is better. Because you can leave it there and it could sell at any time,.

Link to the interior: https://www.gta5-mods.com/maps/mosley-s-auto-shop-interior-sp-fivem

**Comment by twooot** [comment]
We have the Luxury autos shop and job for this
