### ISSUE TITLE
Maximum Performance Repair Shop

### ISSUE THREAD

**Issue by iGreatWhite** [InZidiuZ/op-framework-issue-tracker#792]
**Name:**
Who is suggesting this? iGreatWhite#0001

**Summary:**
I am suggesting the addition of a new interior for us, Maximum Performance, to work out of and bring customers to. We feel as if this could bring loads of potential as the location we want to put it would be near the city compared to the repair shop down at the docks. We are also a State Approved business in game and feel like with the plans that me and the CEO of the company have going forward from here are nothing but great. The interior in mind is paid from a developer who makes MLO interiors.

Video: https://youtu.be/Qvb7ZS03vCw

DM me for the link and more information.

**Reason:**
Why would your suggestion be a good addition to Legacy?
We feel as if we had a shop closer to the center of the city that we can provide better RP and people would have a more central repair shop. We are also trying to grow this brand into more forms than just a repair shop. We can host car shows and such out of this garage.

**Comment by Camdaddy34** [comment]
+1 to this, as I think it would also open up some competition between mechanic companies.

**Comment by AdeptCL** [comment]
Having interacted with Max, I understood immediately what the company is about and what the plans to move this forward were. I feel like with all the business roleplay spiking, this is definitely one that should be considered for it's own area. 

Not only will this improve roleplay, but it will provide a stepping stone for civilian roleplay too.

+1

**Comment by Livius99** [comment]
You want competition? THEN U GOT IT XD

**Comment by Imaghost1337** [comment]
Like if there isn't enough repair shops in the city already..

**Comment by AdeptCL** [comment]
> Like if there isn't enough repair shops in the city already..

There is theoretically 2 active ones. Public at Dock, and public at Grove.
The Lost MC shop no longer is usable.

Why not have another private company?

**Comment by Camdaddy34** [comment]
The thing is, don’t see it as there being too many repair shops, because that completely voids the idea of having a company shop. The Lost MC has their shop, scuffed or not, Grove St seems like it’s utilized by a few companies if not everyone,  but the only privately owned mechanic shop belongs to a gang. No one runs the docks, it’s too far out of the way. There isn’t one up north that you can purchase materials out of, so it wouldn’t make sense to only have two shops in city that you could go to. I hate going down to grove consistently for repairs, especially since there’s not an actual company running it in that fashion. LM runs out of it, but they don’t run it ya know. 

While adding another spot in the actual city for people to head to for repairs is awesome, it’s about creating competition in the mechanic world to hopefully create drive for more business. You’ll have your preferred mechanics for whatever reason that may be, but the big thing to draw from is the fact that there’s now a larger selection - and it’ll be run by someone who really wants to put an incredible amount of effort into

**Comment by Livius99** [comment]
Dude I love the competition idea. Can't wait to see some races against racing clubs

**Comment by Livius99** [comment]
As I've seen max competition is not only a repair shop, also racing n drift (drifters r weak)

**Comment by InZidiuZ** [comment]
Hey,

Will close this as it does not comply with the framework standards of FFA RP features. The only exclusive features should be actual game-implementations such as 'Vanilla Unicorn', 'The Lost MC', 'Tequi-la-la', etc.

If you'd like to rework this suggestion, feel free to create another issue.

**InZidiuZ**
*OP-FW Developer*
