### ISSUE TITLE
Chop - Currently Chop is only giving Vodka and Repair Parts

### ISSUE THREAD

**Issue by b-hess** [InZidiuZ/op-framework-issue-tracker#796]
On 1/31, I ended up chopping 6 or 7 cars, and the only items that I recieved are the three car parts, and Vodka.  No other items dropped.

**Comment by iGreatWhite** [comment]
Wrong format. Remake your issue using the proper format

**Reporter:**
Who is reporting this? Please include discord name and your steam profile.

**Summary:**
Write a short summary of what you're experiencing.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.
