### ISSUE TITLE
[game/inventory] Firearms/Etc. Items Durability

### ISSUE THREAD

**Issue by iGreatWhite** [InZidiuZ/op-framework-issue-tracker#872]
**Name:**
Who is suggesting this? iGreatWhite#0001
**Summary:**
So basically the idea that I am about to pitch can change things within the new inventory system so that guns and such will break over time so they eventually become useless. This system could also be put in place with rare items such as tuner chips, bank chips, food and other items. A gun that you obtain from a store or gun drop would start at the Great condition and gradually go down as time goes on until it is broken. Also, the more the gun is used the faster it breaks. This also brings up the question to add like weapon cleaning kits or gun repair kits or any similar way to repair a gun which could also be plausible.

**Reason:**
Why would your suggestion be a good addition to Legacy?
It would give an effective balance to the economy we have and make the prices for things fluctuate based upon the demand and supply at the current time. This way gun dealers don't sit upon stacks of ARs that never break.

**Comment by DaxterPancake** [comment]
I'd like to see more uses for Aluminum, Scrap Metal, Steel, Copper, Plastic, etc. 
We could do this in a few different ways, we could use those metals to make a 'gun cleaning kit' or 'gun repair kit' or we could just skip the middle man and have a location or a few locations where you can fix your guns using just the metals.
It could mimic the current mechanic script in the sense of, when you USE the gun at a particular location it will tell you what you will need to repair the gun.
For example: You have a Mini SMG that is Extremely Damaged. You USE the Mini SMG at the location and are prompted that you will need 6 Steel, 2 Aluminum, 2 Plastic and 4 Copper to repair it. One you have the materials you go back to the same place and use it again, which would then start the repairing. Once repaired it would only go back up to lets say Slightly Damaged compared to Perfect. Maybe it gets more and more expensive to repair a weapon the more you do it to that weapon.
Food and drinks would degrade and have no way to 'repair' them.
Thermite, USB's, Chips etc. would degrade, meaning that when you get them, you'd be a lot more interested in selling/using them fast, hopefully encouraging more RP when it comes to selling things. 
I love the idea of the more you use a weapon the faster it degrades, which is where in my opinion a 'weapon cleaning kit' would be great to slightly increase the weapon's quality until you're able to repair it.
Drugs would degrade aswell, which means that bigger gangs would have to try and offload their stock a lot faster which adds more risk to the situation aswell.

I'd love some more ideas on this, because I am kinda just vomiting ideas right now.

**Comment by DaxterPancake** [comment]
When food/drink 'breaks' it could turn into 'Fertilizer'.

When a gun breaks it could turn into 'weapon parts' or 'scrap metal'.

When Thermite, USB's, Chips break, it could turn into 'scrap metal' or 'recyclable material'.

**Comment by AdeptCL** [comment]
100%. I definitely think we need to bring in something that utilities the items such as recyclable material, glass, rubber, plastic, etc. When there is little to no use for these items, it can be frustrating when people are doing diving/house robberies/chop shop and these are the items that are being obtained.

**Comment by Nuziatella** [comment]
This idea should really happen soon for the sake of economy and server balance given the time that has passed since the inventory wipe. It prevents stockpiling of goods and forces interaction. @DaxterPancake idea for a repair option gives a creative and interactive route for the mechanic job. So if one happens the other should happen as well.

**Comment by novapurple** [comment]
If we are going to do this, this should also be done to PD weapons etc. make them last a week and then you would have to purchase new equipment.

**Comment by Nuziatella** [comment]
Agreed. With the recent paycheck raise there shouldn't be another balancing issue caused by making all firearms degrade over time including PD weapons.

**Comment by twooot** [comment]
Item durability was added
