### ISSUE TITLE
About Starting Xbox One RP

### ISSUE THREAD

**Issue by shivpatel333** [InZidiuZ/op-framework-issue-tracker#882]
I am A Xbox One Player and Looking for legacy RP in that! Same as it is in PC for we Indians. Actually I have a Discord server ready for it with all perms too. But I don't know how to make changes in game. So I request you to think about this and make some decisions.

**Comment by iGreatWhite** [comment]
This is a community based around FiveM. Which cannot be achieved in consoles. So it would rather hard to even think about starting a console server.

**Comment by shivpatel333** [comment]
Sir it's hard but not impossible...
Even many of gamers would be looking for this and there will be your profit
in starting this project and we gamers will able to play that. Like I have
Xbox One but not gaming pc to play RolePlay as I want to Play Roleplay

**Comment by iGreatWhite** [comment]
When you find a way to load FiveM onto a console and have it hot properly I’m sure the owner would love to hear that. And he could then make the server. But legacy requires more than just GTA V.

**Comment by shivpatel333** [comment]
Hey! Bro I am not a developer and I cannot make changes in Game that's why
I requested you. As I know you guys are developer.

**Comment by AdeptCL** [comment]
My guy, it is realistically not possible to get FIVEM onto a console. Like how do you expect to achieve this?
The developers here are not FIVEM developers, they’re Legacy. 
If you want it soooo badly, go to FIVEM and ask them.

**Comment by shivpatel333** [comment]
How to contact FIVEM?

**Comment by LikeConnorr** [comment]
If you'd like to contact FiveM, you can follow one of the processes here:

**Cfx.re Project Discord**: 
https://discord.gg/fivem

**Cfx.re Forums**:
https://forum.cfx.re/categories

**Cfx.re GitHub**:
https://github.com/citizenfx/fivem

From a personal stance, CitizenFX support isn't worth even approaching, especially asking for them to release FiveM to the console. Grand Theft Auto V is unmodifiable on console, so this would be physically impossible. Even if it was, CFX are lazy, they wouldn't commit the time to work on it, especially with the release of RedM.

For more information, visit rockstar support @ https://support.rockstargames.com/. 
Unfortunately, this issue is irrelevant to the OP-FW Development Team.

**Comment by InZidiuZ** [comment]
Yea, no...
