### ISSUE TITLE
[jobs/transporter] Load dissapearing during delivery

### ISSUE THREAD

**Issue by ABOW402** [InZidiuZ/op-framework-issue-tracker#927]
**Reporter:**
ABOW402#5662 - https://steamcommunity.com/profiles/76561198931068696/

**Summary:**
Transport Job sometimes will let you pick up the trailer, then it just disappears, and vanishes. Making you /canceljob and then your stuck for 10 minutes not being able to pick up a load.

**Steps to Reproduce:**
I have no clue, but it needs to stop making my trailer disappear!

**Expected Results:**
To not have your trailer disappear when doing the job

**Actual Results:**
I have no clue yet.

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
![image](https://user-images.githubusercontent.com/63160997/78817792-54ed0c80-7999-11ea-8ab3-6c4ce20e7927.png)

**Game Resolution:**
1920x 1080

**Player Data:**

**Server:**
Main North America city 1

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This is believed to be a OneSync issue. It may also be assisted by bad management of entities from some of our ancient & also possibly public scripts we use, so we might see improvements as more updates and improvements are made to the framework.

For now, though, I've set the cool-down to 60 seconds to limit the damages this issue is causing.

**InZidiuZ**
*OP-FW Developer*
