### ISSUE TITLE
[jobs/police] More pistols for police

### ISSUE THREAD

**Issue by sahara87** [InZidiuZ/op-framework-issue-tracker#961]
**Name:**
Kiwi#6887

**Summary:**
PD receiving heavy pistols.

**Reason:**
This would allow guns fights to be fair and would balance the skill gap between cop and crims. Right now as it stands, officers are constantly finding it difficult to take down criminals when it comes to pistol fights, especially with the addition of the heavy revolver and marksman pistol. It is also now much easier to obtain these weapons due to the chances of decryption keys being dropped have been increased and there is now a lot more ways to gather them. The combat pistol does not do anywhere near as much damage as we need to be able to take down criminals sometimes taking up to 10 shots depending on the range. Whereas weapons like the pistol .50 or heavy pistol take 3-4. The fact that cars are now very difficult to disable also makes it harder for us because there could be 4 people in 1 vehicle shooting cops with handheld smg's and the only thing we can do it shoot back with a combat pistol and hope we hit head shots. Obviously the heavy pistol would not be used by every trooper and there would have to be some restrictions, for example, sgt+ or swat can carry them but I do believe that they are necessary to even out the playing field.

**Comment by AmokBSN** [comment]
I see where you're coming from however perhaps a slight change could be that rather than the PD having access to the 50 calibres, the PD Combat Pistol has a slight damage buff. So for example, if the .50 takes 3-4 shots, the PD Combat would be 5-6. 

Some additional attachments could also be provided such as an extended magazine/flashlight combination. 

Personally, I always found it slightly odd that PD would restrict the use of the Carbine to specific ranks - I know this has always been in place since I can remember the PD's existence although that could also be further looked at. If someone's shooting at you with a handheld SMG they should know that serious consequences will be enforced and the almighty Carbine may start to fire upon them. 

There's a very fine line in finding the balance but if four/six people are rolling deep and they're starting to fire on me with automatic weapons. I'd be looking at ripping my Carbine out. Not only for my safety but fellow Troopers and Civilians.

**Comment by twooot** [comment]
No
