### ISSUE TITLE
[illegal/*] Bank/Illegal runs rework

### ISSUE THREAD

**Issue by mavroses** [InZidiuZ/op-framework-issue-tracker#977]
**Name:**
MAVROSES#0402

**Summary:**
We want to add different coloured cards that will only be found from drug runs done inside areas controlled by registered gangs. For example, you would get red cards from doing coke runs from the red mafia airstrip up in Sandy. (Black cards from Lester's house, orange cards from Oxy in Paleto etc.)

These cards would then be used to rob banks (you'd need a set amount of different coloured keys (1 blue, 1 red, 1 orange, for example, to get through to the bank vault). This would be done because doing banks is way too easy for even brand new people to the city and people would actually have to RP with the gangs and make deals to purchase or acquire said cards and opportunities to rob banks.

This system could also work with just the normal coloured keys we have now but they would have to be removed from the normal loot pools (garbage, diving etc) and divided into the different gang-controlled illegal runs. 

**Reason:**
It would prevent people that just joined the server from doing banks and add more value in RPing with gangs and it would create tons of interesting RP scenarios and situations.

It would also make gangs interact with each other more and create deals and relationships that actually mean something.

All of us really just want the economy and the "flow" of RP in the server to be smooth and enjoyable for everyone.

Ps. Please contact me for more information, I just want the server to be as enjoyable as possible to everyone. I can even assist in moderating or developing the community.

**Comment by RusuSergiu** [comment]
+1

**Comment by AmokBSN** [comment]
I think adding cards would be a good idea so that banks aren't hit so often. It should take more time to gather materials and overall it means that the Police can focus on other crimes or plan to do other scenarios without always having to go directly to a bank. 

My only problem with your suggestion is that if gangs only have access to these cards from doing runs, it might mean that they're in a constant state of being 'friendly/neutral' if other gangs want to have a war they'd be instantly cut out of cards which, could help them fund a war for example.

**Comment by mavroses** [comment]
I agree with AmokBSN and I get why you think there might be a problem etc.

**Comment by iGreatWhite** [comment]
Rather than cards being specific to an activity. What if, whenever you sell to a ped (selling coke, weed or oxy) there is a chance to get a card of whatever color seems fit. Also getting cards from chopping cars. Ultimately the cards would be numbered to make it the easiest. From here I believe that if there was a system in place where different cards can be used for different banks at one time.
Bank #1 : Security Card #1 
Bank #2 : Security Card #1 
Bank #3 : Security Card #4 
Bank #4 : Security Card #3 
So on until all the banks are listed. This way the crime would have to figure out which bank is which and the cards for said banks would randomize each GTA day cycle. This can be done by adding an item that would decrypt a set of data and give you this list at a laptop down by the docks.

**Comment by mavroses** [comment]
That's actually a sick idea iGreatWhite, I'd love to have that implemented.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
