### ISSUE TITLE
[?] Dirty Money

### ISSUE THREAD

**Issue by mavroses** [InZidiuZ/op-framework-issue-tracker#979]
**Name:**
MAVROSES#0402

**Summary:**
Make banks (maybe even drugs) give people dirty money instead of normal "clean" money, that dirty money would then have to be cleaned by selected members in whitelisted/registered gangs (1 to 2 cleaners per gang), they'd then get a set percentage of clean money in exchange to the dirty money.

**Reason:**
It adds a ton of realism, makes people have to interact with gangs more and just adds a truckload of RP value to the server and to the whole community.

Thank you.

**Comment by RusuSergiu** [comment]
+1

**Comment by Livius99** [comment]
Would definitely love to see this back!

**Comment by iGreatWhite** [comment]
Inzidiuz has stated before that whitelist positions for drugs/guns and other illegal things will not be happening as it doesn’t go with the FFA framework standard he had in mind.

**Comment by mavroses** [comment]
I suppose Gang RP will just remain nonexistent like it is currently then.

**Comment by MrCl0udz** [comment]
There is plenty Gang Rp going on it just won't happen because it wouldn't work with the subdivisions

**Comment by DaxterPancake** [comment]
We can have dirty money without whitelisted gangs. 

If we added a location to clean money, a gang will hold it down. So you'd have to go through a gang wether or not they were whitelisted for that specific reason.
I've actually seen a script before that required you to have a specific item on you like 'Money Wash Ticket' before you could even enter/wash your money. 
We could add that, so that'd mean that there is specific people you'd have to go to as you wouldn't even be able to do it on your own.

Adding dirty money would add another difficult step for criminals and it's also realistic, this idea could be adapted to new features in the future also.

**Comment by rockbrod** [comment]
What about a more breaking bad sort of approach where dirty money has to go through a legal business. This would then create more rp situations because the criminals would need to run a legal business aswell to be able to clean their money. Plus they could also wash other people's money making alot more interaction and less server based interaction. Perhaps have a spot for the business whitelisted that allows wash money. But it takes say 1 game day to wash.

**Comment by Livius99** [comment]
cash shouldn't be "dirty" but we definitely need a system that let cops check where you took the cash from and at that point you need a legal business to "wash them" , but you can also use them as "dirty"

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
