### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by adityadevharkar** [InZidiuZ/op-framework-issue-tracker#985]
**Reporter:**
I am Deadkiller#8914
**Summary:**
I have a house and it had full storage of guns thermites etc. At forum drive.. But some how it hot wiped. I see nothing in the storage it is showing zero. I had collected with much efforts.I think its a bug and it all got vanished.

**Steps to Reproduce:**
See if the bug gets cleared.

**Expected Results:**
I want my Stuff back if you have logs you can check it give. PLEASE 

**Actual Results:**
-

**Server
Legacy India Whitelist server.

**Comment by DaxterPancake** [comment]
Hi,

I am closing this due to the fact you didn't use the template correctly. 
When filling out the template you need to fill in as much information that you can INCLUDING the sections where it requires screenshots and your character info.

Please remake this issue with the relevant changes.

Thanks,
**Daxter.
Project Manager.**
