### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by DeathValleygamingYt** [InZidiuZ/op-framework-issue-tracker#988]
Death Valley Gaming Yt#3225
https://steamcommunity.com/id/DeathValleyGamingYt/

hi , I am death valley gaming 

i just check that when we choice a character of dog so there is issues in pill box  when we go in the roof but we can not come down that's the  issues i ll share a video link
https://drive.google.com/file/d/1tyW6RvHHosncfR_2WGUCx9DNmZzWDONL/view?usp=sharing
 
and my ideas is you have to add some event area and races area.
also important part can you add a work place of wizeal news building same as working station and interview station and many more + helicopter for cover new in high area its got really good rp i hope  because i do work as a reporter

**Comment by DaxterPancake** [comment]
Hi,

I am closing this due to you not using the template.
Please go [HERE](https://github.com/InZidiuZ/op-framework-issue-tracker/issues/new/choose), select bug report and fill in all areas correctly and with as much information as you can.

Though, I feel that dogs not being able to go through a door to the helicopter pad of the hospital isn't a huge issue. Just don't go up there.

Thanks,
**Daxter.
Project Manager.**
